//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DOMHTMLObjectElement.h"

@interface DOMHTMLObjectElement (AttachmentLocator)
- (void)attachment:(id *)arg1 url:(id *)arg2 fromDocument:(id)arg3;
@end

