//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@interface _MUISnapshotView : NSView
{
}

- (id)hitTest:(struct CGPoint)arg1;	// IMP=0x0000000000024cf0
- (BOOL)isFlipped;	// IMP=0x0000000000024ce5

@end

