//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

////#import "NSObject.h"
//
//#import "NSCoding.h"
//#import "NSCopying.h"

@class MUIRemoteImageCollector, NSArray, NSDictionary, NSError, NSMutableDictionary, NSString, NSURL;

@interface MUIWebDocument : NSObject <NSCoding, NSCopying>
{
    NSString *_html;	// 8 = 0x8
    NSMutableDictionary *_jsDocumentContext;	// 16 = 0x10
    BOOL _blockRemoteContent;	// 24 = 0x18
    BOOL _hasBlockedRemoteContent;	// 25 = 0x19
    BOOL _isEncrypted;	// 26 = 0x1a
    BOOL _isSigned;	// 27 = 0x1b
    NSArray *_attachments;	// 32 = 0x20
    Class _webAttachmentClass;	// 40 = 0x28
    long long _imageScale;	// 48 = 0x30
    NSURL *_baseURL;	// 56 = 0x38
    NSDictionary *_dataDetectorsContext;	// 64 = 0x40
    NSError *_parseError;	// 72 = 0x48
    unsigned long long _originalEncoding;	// 80 = 0x50
    MUIRemoteImageCollector *_remoteImageCollector;	// 88 = 0x58
    NSArray *_signers;	// 96 = 0x60
    NSArray *_signerNames;	// 104 = 0x68
}

@property(copy, nonatomic) NSArray *signerNames; // @synthesize signerNames=_signerNames;
@property(copy, nonatomic) NSArray *signers; // @synthesize signers=_signers;
@property(nonatomic) BOOL isSigned; // @synthesize isSigned=_isSigned;
@property(nonatomic) BOOL isEncrypted; // @synthesize isEncrypted=_isEncrypted;
@property(retain, nonatomic) MUIRemoteImageCollector *remoteImageCollector; // @synthesize remoteImageCollector=_remoteImageCollector;
@property(copy, nonatomic) NSString *html; // @synthesize html=_html;
@property(nonatomic) unsigned long long originalEncoding; // @synthesize originalEncoding=_originalEncoding;
@property(nonatomic) BOOL hasBlockedRemoteContent; // @synthesize hasBlockedRemoteContent=_hasBlockedRemoteContent;
@property(nonatomic) BOOL blockRemoteContent; // @synthesize blockRemoteContent=_blockRemoteContent;
@property(retain, nonatomic) NSError *parseError; // @synthesize parseError=_parseError;
@property(copy, nonatomic) NSDictionary *dataDetectorsContext; // @synthesize dataDetectorsContext=_dataDetectorsContext;
@property(retain, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
@property(nonatomic) long long imageScale; // @synthesize imageScale=_imageScale;
@property(nonatomic) Class webAttachmentClass; // @synthesize webAttachmentClass=_webAttachmentClass;
@property(copy, nonatomic) NSArray *attachments; // @synthesize attachments=_attachments;
//- (void).cxx_destruct;	// IMP=0x0000000000024c3d
- (id)attachmentForContentID:(id)arg1;	// IMP=0x0000000000024739
- (id)description;	// IMP=0x00000000000246ac
- (id)_defaultDocumentHTML;	// IMP=0x000000000002468d
- (void)setValueInJsDocumentContext:(id)arg1 forKey:(id)arg2;	// IMP=0x0000000000024640
@property(readonly, copy, nonatomic) NSDictionary *jsDocumentContext;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000000000244c6
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000000002440c
- (void)_muiWebDocumentCommonInit;	// IMP=0x00000000000241f7
- (id)initWithCoder:(id)arg1;	// IMP=0x00000000000240a1
- (id)init;	// IMP=0x0000000000023fab

@end

