//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import <AppKit/NSTokenAttachmentCell.h>
//#import "NSTokenAttachmentCell.h"

@class NSColor;

@interface MUIAddressTokenAttachmentCell /*: NSTokenAttachmentCell*/
{
    BOOL _displayAsExternal;	// 68 = 0x44
    BOOL _neverShowSeparator;	// 69 = 0x45
    NSColor *_foregroundColor;	// 72 = 0x48
}

+ (id)colorForExternalDomain;	// IMP=0x000000000000b30d
@property(retain, nonatomic) NSColor *foregroundColor; // @synthesize foregroundColor=_foregroundColor;
@property BOOL neverShowSeparator; // @synthesize neverShowSeparator=_neverShowSeparator;
@property(nonatomic) BOOL displayAsExternal; // @synthesize displayAsExternal=_displayAsExternal;
//- (void).cxx_destruct;	// IMP=0x000000000000b55a
- (id)_textAttributes;	// IMP=0x000000000000b41a
- (BOOL)_finalizeStyleTextOptions:(id)arg1;	// IMP=0x000000000000b412
- (id)tokenTintColor;	// IMP=0x000000000000b392

@end

