//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//#import <Mail/NSObject-Protocol.h>

@class MFMessageDeliverer;

@protocol MFMessageDelivererDelegate <NSObject>
- (void)messageDeliveryDidFinish:(MFMessageDeliverer *)arg1;

@optional
- (void)messageDeliveryWillBegin:(MFMessageDeliverer *)arg1;
@end

