//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "MUITokenAddressDelegate-Protocol.h"

@class NSString;

@interface MailAddressDelegate : NSObject <MUITokenAddressDelegate>
{
}

- (void)_searchForToken:(id)arg1;
- (void)_removeFromVIPs:(id)arg1;
- (void)_addToVIPs:(id)arg1;
- (void)_openNewMessageForTokenAddress:(id)arg1;
- (BOOL)tokenAddressIsVIP:(id)arg1;
- (void)tokenAddress:(id)arg1 didSelectAction:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

