//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MTMSubMetaMailbox.h"

@interface _MTMStoredSubMetaMailbox : _MTMSubMetaMailbox
{
}

- (void)loadNextMessagesWithControllingMailbox:(id)arg1 andFetcher:(id)arg2;
- (void)_updateMessages:(id)arg1;
- (void)_loadMessages;

@end

