//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BasicComposeContext.h"

@interface _UserActivityComposeContext : BasicComposeContext
{
}

- (void)loadCompleted:(id)arg1;
- (id)initWithMessage:(id)arg1;

@end

