//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"
#import "MCAttachmentDataSource-Protocol.h"

@class MCFileWrapper, MCStationeryCompositeImage, NSData, NSDate, NSError, NSImage, NSNumber, NSProgress, NSString, NSURL;

@interface MCAttachment : NSObject
{
    id _cachedFetchedDataLock;	// 8 = 0x8
    NSData *_cachedFetchedData;	// 16 = 0x10
    id _cachedFetchedFileWrapperLock;	// 24 = 0x18
    MCFileWrapper *_cachedFetchedFileWrapper;	// 32 = 0x20
    NSImage *_iconImage;	// 40 = 0x28
    id _archiveFileWrapperLock;	// 48 = 0x30
    BOOL _isAutoArchiveAttachment;	// 56 = 0x38
    NSURL *_remoteURL;	// 64 = 0x40
    struct CGSize _resizedImageSize;	// 72 = 0x48
    BOOL _hasResourceForkData;	// 88 = 0x58
    BOOL _isCalendarInvitation;	// 89 = 0x59
    BOOL _isUnreferencedAttachment;	// 90 = 0x5a
    BOOL _shouldHideExtension;	// 91 = 0x5b
    BOOL _isMailDropImageArchive;	// 92 = 0x5c
    BOOL _isMailDropImageThumbnail;	// 93 = 0x5d
    BOOL _isMailDropIndividualImage;	// 94 = 0x5e
    BOOL _isMessageExternalBodyWithURL;	// 95 = 0x5f
    BOOL _isPlayableByQTKit;	// 96 = 0x60
    unsigned short _finderFlags;	// 98 = 0x62
    unsigned int _creator;	// 100 = 0x64
    unsigned int _type;	// 104 = 0x68
    id <MCAttachmentDataSource> _dataSource;	// 112 = 0x70
    NSString *_contentID;	// 120 = 0x78
    NSProgress *_downloadProgress;	// 128 = 0x80
    NSString *_extension;	// 136 = 0x88
    NSNumber *_filePermissions;	// 144 = 0x90
    NSNumber *_fileSize;	// 152 = 0x98
    NSString *_filename;	// 160 = 0xa0
    NSString *_filenameForSaving;	// 168 = 0xa8
    long long _imageByteCountFromHeaders;	// 176 = 0xb0
    NSString *_mailSpecialHandlingType;	// 184 = 0xb8
    NSString *_mimeType;	// 192 = 0xc0
    NSNumber *_mimeEncodedContentLength;	// 200 = 0xc8
    NSString *_originalFilename;	// 208 = 0xd0
    MCStationeryCompositeImage *_stationeryCompositeImage;	// 216 = 0xd8
    NSString *_cloudKitRecordName;	// 224 = 0xe0
    NSURL *_downloadURL;	// 232 = 0xe8
    NSDate *_downloadURLExpiration;	// 240 = 0xf0
    NSError *_downloadError;	// 248 = 0xf8
    NSString *_mimePartNumber;	// 256 = 0x100
    NSData *_resizedData;	// 264 = 0x108
    struct CGSize _imageSizeFromHeaders;	// 272 = 0x110
}

+ (id)keyPathsForValuesAffectingIsDataDownloaded;	// IMP=0x0000000000011fc8
+ (id)log;	// IMP=0x00000000000101a1
@property(nonatomic) BOOL isPlayableByQTKit; // @synthesize isPlayableByQTKit=_isPlayableByQTKit;
@property(readonly, copy, nonatomic) NSData *resizedData; // @synthesize resizedData=_resizedData;
@property(readonly, copy, nonatomic) NSString *mimePartNumber; // @synthesize mimePartNumber=_mimePartNumber;
@property(nonatomic) BOOL isAutoArchiveAttachment; // @synthesize isAutoArchiveAttachment=_isAutoArchiveAttachment;
@property(readonly, nonatomic) BOOL isMessageExternalBodyWithURL; // @synthesize isMessageExternalBodyWithURL=_isMessageExternalBodyWithURL;
@property(nonatomic) BOOL isMailDropIndividualImage; // @synthesize isMailDropIndividualImage=_isMailDropIndividualImage;
@property(nonatomic) BOOL isMailDropImageThumbnail; // @synthesize isMailDropImageThumbnail=_isMailDropImageThumbnail;
@property(nonatomic) BOOL isMailDropImageArchive; // @synthesize isMailDropImageArchive=_isMailDropImageArchive;
@property(retain, nonatomic) NSError *downloadError; // @synthesize downloadError=_downloadError;
@property(retain, nonatomic) NSDate *downloadURLExpiration; // @synthesize downloadURLExpiration=_downloadURLExpiration;
@property(retain, nonatomic) NSURL *downloadURL; // @synthesize downloadURL=_downloadURL;
@property(copy, nonatomic) NSString *cloudKitRecordName; // @synthesize cloudKitRecordName=_cloudKitRecordName;
@property(nonatomic) unsigned int type; // @synthesize type=_type;
@property(retain, nonatomic) MCStationeryCompositeImage *stationeryCompositeImage; // @synthesize stationeryCompositeImage=_stationeryCompositeImage;
@property(nonatomic) BOOL shouldHideExtension; // @synthesize shouldHideExtension=_shouldHideExtension;
@property(copy, nonatomic) NSString *originalFilename; // @synthesize originalFilename=_originalFilename;
@property(readonly, nonatomic) NSNumber *mimeEncodedContentLength; // @synthesize mimeEncodedContentLength=_mimeEncodedContentLength;
@property(copy, nonatomic) NSString *mimeType; // @synthesize mimeType=_mimeType;
@property(copy, nonatomic) NSString *mailSpecialHandlingType; // @synthesize mailSpecialHandlingType=_mailSpecialHandlingType;
@property(nonatomic) BOOL isUnreferencedAttachment; // @synthesize isUnreferencedAttachment=_isUnreferencedAttachment;
@property(nonatomic) BOOL isCalendarInvitation; // @synthesize isCalendarInvitation=_isCalendarInvitation;
@property(nonatomic) struct CGSize imageSizeFromHeaders; // @synthesize imageSizeFromHeaders=_imageSizeFromHeaders;
@property(nonatomic) long long imageByteCountFromHeaders; // @synthesize imageByteCountFromHeaders=_imageByteCountFromHeaders;
@property(nonatomic) BOOL hasResourceForkData; // @synthesize hasResourceForkData=_hasResourceForkData;
@property(nonatomic) unsigned short finderFlags; // @synthesize finderFlags=_finderFlags;
@property(copy, nonatomic) NSString *filenameForSaving; // @synthesize filenameForSaving=_filenameForSaving;
@property(copy, nonatomic) NSString *filename; // @synthesize filename=_filename;
@property(retain, nonatomic) NSNumber *fileSize; // @synthesize fileSize=_fileSize;
@property(retain, nonatomic) NSNumber *filePermissions; // @synthesize filePermissions=_filePermissions;
@property(copy, nonatomic) NSString *extension; // @synthesize extension=_extension;
@property(retain, nonatomic) NSProgress *downloadProgress; // @synthesize downloadProgress=_downloadProgress;
@property(nonatomic) unsigned int creator; // @synthesize creator=_creator;
@property(copy, nonatomic) NSString *contentID; // @synthesize contentID=_contentID;
@property(retain, nonatomic) id <MCAttachmentDataSource> dataSource; // @synthesize dataSource=_dataSource;
//- (void).cxx_destruct;	// IMP=0x0000000000015ae7
@property(readonly, nonatomic) BOOL hasPendingBackgroundRead;
- (void)configureWithFileWrapper:(id)arg1;	// IMP=0x000000000001524d
- (BOOL)getCompressedData:(id *)arg1 compressedFileURL:(id *)arg2 archiveType:(long long *)arg3 error:(id *)arg4;	// IMP=0x0000000000014aac
- (id)description;	// IMP=0x00000000000149ab
- (id)debugDescription;	// IMP=0x0000000000014880
- (id)createTemporaryFile;	// IMP=0x0000000000014830
- (BOOL)createEmptyAttachmentAtURL:(id)arg1;	// IMP=0x00000000000147b8
- (void)_setupFileWrapper:(id)arg1;	// IMP=0x0000000000014554
- (id)_freshFileWrapper;	// IMP=0x0000000000014407
- (void)dataForAccessLevel:(long long)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000000013f17
- (id)dataForAccessLevel:(long long)arg1;	// IMP=0x0000000000013bed
@property(retain, nonatomic) NSData *cachedFetchedData;
- (void)fileWrapperForAccessLevel:(long long)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x000000000001353c
- (id)fileWrapperForAccessLevel:(long long)arg1;	// IMP=0x00000000000131ed
@property(retain, nonatomic) MCFileWrapper *cachedFetchedFileWrapper;
@property(readonly, nonatomic) BOOL couldConfuseWindowsClients;
- (void)takeNewDataFromPath:(id)arg1;	// IMP=0x0000000000012ebe
@property(nonatomic) BOOL isPartOfStationery;
@property(readonly, nonatomic) BOOL isRemotelyAccessed;
- (void)isImage:(char *)arg1 isPDF:(char *)arg2 bestMimeType:(id *)arg3;	// IMP=0x00000000000129ef
@property(readonly, nonatomic) BOOL isPDF;
@property(readonly, nonatomic) BOOL isImage;
@property(readonly, nonatomic) BOOL isStationeryCompositeImage;
@property(readonly, nonatomic) BOOL isAudio;
@property(readonly, nonatomic) BOOL isVideo;
- (void)getTypeIdentifier:(id *)arg1 andPedigree:(id *)arg2;	// IMP=0x00000000000126e6
- (void)discardIconImage;	// IMP=0x00000000000126d2
@property(retain, nonatomic) NSImage *iconImage;
@property(readonly, copy, nonatomic) NSString *filenameWithoutHiddenExtension;
- (unsigned long long)approximateSizeForAccessLevel:(long long)arg1;	// IMP=0x0000000000012147
@property(readonly, nonatomic) BOOL isDirectory;
@property(readonly, nonatomic) BOOL isDataDownloaded;
@property(readonly, nonatomic) struct CGSize resizedImageSize; // @synthesize resizedImageSize=_resizedImageSize;
- (void)setFileNameForResizedImage:(id)arg1;	// IMP=0x0000000000011efa
@property(readonly, nonatomic) BOOL isFullSize;
- (void)revertToOriginalData;	// IMP=0x0000000000011eaf
- (void)setResizedData:(id)arg1 imageSize:(struct CGSize)arg2;	// IMP=0x0000000000011d69
@property(retain, nonatomic) NSURL *remoteURL;
- (id)_cleanImageMetadataFromData:(id)arg1;	// IMP=0x0000000000011891
- (id)_privateImageMetadataDescriptors;	// IMP=0x00000000000117ca
- (BOOL)_hasPrivateImageMetadata:(id)arg1;	// IMP=0x000000000001154d
@property(readonly, nonatomic) MCAttachment *uneditableAttachment;
- (void)_mcAttachmentCommonInit;	// IMP=0x00000000000111ce
- (id)init;	// IMP=0x0000000000011189
- (id)initWithFileURL:(id)arg1;	// IMP=0x0000000000010f8e
- (id)initWithMimePart:(id)arg1;	// IMP=0x0000000000010823
- (id)initWithStationeryCompositeImage:(id)arg1;	// IMP=0x0000000000010758
- (id)initWithFileWrapper:(id)arg1;	// IMP=0x00000000000106da
- (id)initWithMailInternalData:(id)arg1;	// IMP=0x00000000000102a4
- (id)initWithData:(id)arg1;	// IMP=0x0000000000010200

@end

