//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface NSAttributedString (FontAdditions)
+ (double)_headerFontSize;	// IMP=0x0000000000080d17
+ (id)headerAttributes;	// IMP=0x0000000000080b75
+ (id)boldGrayHeaderAttributes;	// IMP=0x0000000000080964
+ (void)resetMimeHeaderAttributes;	// IMP=0x0000000000080926
@end

