//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface NSData (MailCoreAdditions)
@property(readonly, copy, nonatomic) NSData *MD5Digest;
- (struct _NSRange)rangeOfCString:(const char *)arg1 options:(unsigned long long)arg2 range:(struct _NSRange)arg3;	// IMP=0x0000000000084a0a
- (struct _NSRange)rangeOfCString:(const char *)arg1 options:(unsigned long long)arg2;	// IMP=0x00000000000849bc
- (struct _NSRange)rangeOfCString:(const char *)arg1;	// IMP=0x0000000000084971
@property(readonly, nonatomic) struct _NSRange rangeOfRFC822HeaderData;
@property(readonly, copy, nonatomic) NSData *quotedFromSpaceDataForMessage;
- (id)unquotedFromSpaceDataWithRange:(struct _NSRange)arg1;	// IMP=0x00000000000845c6
- (id)initWithDataConvertingLineEndingsFromNetworkToUnix:(id)arg1;	// IMP=0x00000000000843c2
- (id)initWithDataConvertingLineEndingsFromUnixToNetwork:(id)arg1;	// IMP=0x00000000000841ce
@end

