//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSImage.h"

@interface NSImage (CompositeImageAdditions)
+ (id)compositeImageWithImageDictionaries:(id)arg1 size:(struct CGSize)arg2;	// IMP=0x000000000008879e
+ (id)drawingDictionaryWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000000000886ef
- (id)flippedImageForLayoutDirection:(long long)arg1;	// IMP=0x00000000000884db
- (id)tintedImageWithColor:(id)arg1 size:(struct CGSize)arg2;	// IMP=0x00000000000882bf
- (id)tintedImageWithColor:(id)arg1;	// IMP=0x000000000008825a
@end

