//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IMAP/IMAPResponse.h>

@class NSArray;

@interface IMAPSearchResponse : IMAPResponse
{
    NSArray *_searchResults;	// 8 = 0x8
}

+ (BOOL)handlesResponseWithName:(const char *)arg1 ofLength:(unsigned long long)arg2;	// IMP=0x0000000000058b8f
@property(copy, nonatomic) NSArray *searchResults; // @synthesize searchResults=_searchResults;
- (void).cxx_destruct;	// IMP=0x0000000000058d0e
- (id)description;	// IMP=0x0000000000058c6e
- (id)debugDescription;	// IMP=0x0000000000058bbe

@end

