//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class MCQuotaUsage, NSString;

@interface IMAPQuotaRoot : NSObject
{
    NSString *_name;	// 8 = 0x8
    MCQuotaUsage *_usage;	// 16 = 0x10
}

@property(retain) MCQuotaUsage *usage; // @synthesize usage=_usage;
@property(copy) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;	// IMP=0x00000000000584f7
- (void)setUsageFromResponse:(id)arg1;	// IMP=0x0000000000057fbc
- (id)description;	// IMP=0x0000000000057f29
- (id)init;	// IMP=0x0000000000057f15
- (id)initWithName:(id)arg1;	// IMP=0x0000000000057eac

@end

