//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IMAP/IMAPMailboxCommand.h>

@interface IMAPGetQuotaRootCommand : IMAPMailboxCommand
{
}

- (BOOL)shouldSendAgainOnError;	// IMP=0x00000000000577db
- (id)activityString;	// IMP=0x000000000005776f
- (id)commandTypeString;	// IMP=0x0000000000057750

@end

