//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IMAP/IMAPFetchResult.h>

@class NSString;

@interface IMAPInternalDateFetchResult : IMAPFetchResult
{
    NSString *_internalDate;	// 8 = 0x8
}

@property(copy, nonatomic) NSString *internalDate; // @synthesize internalDate=_internalDate;
- (void).cxx_destruct;	// IMP=0x000000000002b158
- (id)description;	// IMP=0x000000000002b115

@end

