//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IMAP/IMAPPersistenceTask.h>

#import "IMAPPersistDeletedMessagesOperationDelegate.h"

@class NSMutableIndexSet, NSString;

@interface IMAPPersistDeletedMessagesTask : IMAPPersistenceTask <IMAPPersistDeletedMessagesOperationDelegate>
{
    NSMutableIndexSet *_uids;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000000052de4
- (void)persistDeletedMessagesOperation:(id)arg1 deletedUIDs:(id)arg2;	// IMP=0x0000000000052c8b
- (void)operationFinished:(id)arg1;	// IMP=0x0000000000052c49
- (void)recalculatePriorities;	// IMP=0x0000000000052bf2
- (id)nextPersistenceOperation;	// IMP=0x0000000000052988
- (id)initWithDataSource:(id)arg1;	// IMP=0x00000000000528b9
- (id)initWithUIDs:(id)arg1 dataSource:(id)arg2;	// IMP=0x0000000000052823

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

