//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IMAP/IMAPLocalMessageAction.h>

@class NSDictionary;

@interface IMAPCopyMessageAction : IMAPLocalMessageAction
{
    NSDictionary *_destinationMessagesBySourceUIDs;	// 8 = 0x8
    NSDictionary *_destinationMessagesBySourceMessages;	// 16 = 0x10
}

@property(readonly, copy, nonatomic) NSDictionary *destinationMessagesBySourceMessages; // @synthesize destinationMessagesBySourceMessages=_destinationMessagesBySourceMessages;
@property(readonly, copy, nonatomic) NSDictionary *destinationMessagesBySourceUIDs; // @synthesize destinationMessagesBySourceUIDs=_destinationMessagesBySourceUIDs;
- (void).cxx_destruct;	// IMP=0x00000000000230fd
- (id)newSyncOperationWithDataSource:(id)arg1;	// IMP=0x000000000002306b
- (id)initWithMessageActionID:(long long)arg1 activityType:(id)arg2 mailbox:(id)arg3 userInitiated:(BOOL)arg4;	// IMP=0x0000000000022f9c
- (id)initWithMessageActionID:(long long)arg1 activityType:(id)arg2 mailbox:(id)arg3 userInitiated:(BOOL)arg4 destinationMessagesBySourceUIDs:(id)arg5 destinationMessagesBySourceMessages:(id)arg6;	// IMP=0x0000000000022dbf

@end

