//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSWindowController.h"

@class MCProgressManager;

@interface ActivityWindowController : NSWindowController
{
    MCProgressManager *_progressManager;
}

@property(readonly, nonatomic) MCProgressManager *progressManager; // @synthesize progressManager=_progressManager;
//- (void).cxx_destruct;
- (id)windowNibName;
- (id)initWithCoder:(id)arg1;
- (id)initWithWindow:(id)arg1;
- (id)init;

@end

