//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSPreferences.h"

@class NSMutableArray;

@interface MailPreferences : NSPreferences
{
    NSMutableArray *_preferenceTitles;
    NSMutableArray *_preferenceOwners;
}

//+ (void)restoreWindowWithIdentifier:(id)arg1 state:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
+ (void)_mailApplicationDidFinishLaunching:(id)arg1;
+ (void)initialize;
+ (id)makePreferenceTabViewItems;
//- (void).cxx_destruct;
- (void)windowWillClose:(id)arg1;
- (unsigned long long)validModesForFontPanel:(id)arg1;
- (void)changeFont:(id)arg1;
- (void)addPreferenceNamed:(id)arg1 owner:(id)arg2;
- (id)init;

@end

