//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSOutlineView.h"

@interface NSOutlineView (MailAdditions)
- (id)copyOfItemAndDescendance:(id)arg1;
- (void)_collectDescendants:(id *)arg1 ofItem:(id)arg2;
- (BOOL)item:(id)arg1 isDescendantOf:(id)arg2;
@end

