//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Mail/MFMessageStore.h>

@class NSData, NSString;

@interface MFBerkeleyMbox : MFMessageStore
{
    NSData *_mboxData;	// 16 = 0x10
    NSString *_path;	// 24 = 0x18
}

+ (BOOL)createEmptyStoreForPath:(id)arg1;	// IMP=0x00000000000305b9
+ (BOOL)storeAtPathIsWritable:(id)arg1;	// IMP=0x000000000003053d
+ (BOOL)storeExistsForPath:(id)arg1;	// IMP=0x00000000000304c1
@property(readonly, copy) NSString *path; // @synthesize path=_path;
- (void).cxx_destruct;	// IMP=0x0000000000030776
- (void)fetchSynchronously;	// IMP=0x0000000000030293
- (id)_defaultRouterDestination;	// IMP=0x0000000000030243
- (void)doCompact;	// IMP=0x000000000002f8a8
- (id)_fetchBodyDataForMessage:(id)arg1 andHeaderDataIfReadilyAvailable:(id *)arg2 fetchIfNotAvailable:(BOOL)arg3 allowPartial:(BOOL)arg4;	// IMP=0x000000000002f75c
- (id)_fetchHeaderDataForMessage:(id)arg1 fetchIfNotAvailable:(BOOL)arg2 allowPartial:(BOOL)arg3;	// IMP=0x000000000002f635
- (void)_resetAllMessages;	// IMP=0x000000000002f318
- (id)_mboxData;	// IMP=0x000000000002f120
- (id)lockFilePath;	// IMP=0x000000000002f0c9
- (void)writeUpdatedMessageDataToDisk;	// IMP=0x000000000002f0c3
- (id)initWithAccount:(id)arg1;	// IMP=0x000000000002eff4
- (id)initWithMailbox:(id)arg1 readOnly:(BOOL)arg2 createEmptyStore:(BOOL)arg3;	// IMP=0x000000000002ef25
- (id)init;	// IMP=0x000000000002ee56
- (id)initWithPath:(id)arg1 create:(BOOL)arg2 readOnly:(BOOL)arg3 account:(id)arg4;	// IMP=0x000000000002ecda

@end

