//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Mail/MFRemoveMessagesUpgradeStep.h>

@interface MFDuplicateIMAPMessagesCleanupUpgradeStep : MFRemoveMessagesUpgradeStep
{
}

+ (BOOL)requiredAfterBackbooting;	// IMP=0x0000000000062970
+ (unsigned long long)targetVersion;	// IMP=0x0000000000062965
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x000000000006297b

@end

