//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Mail/MFEWSGateway.h>

#import "NSKeyedUnarchiverDelegate.h"

@class MFEWSConnection, MFEWSResponseOperation, NSMutableDictionary, NSOperationQueue, NSString;

@interface MFEWSOfflineGateway : MFEWSGateway <NSKeyedUnarchiverDelegate>
{
    NSMutableDictionary *_offlineToRealEWSIdStrings;	// 8 = 0x8
    id _offlineToRealEWSIdStringsLock;	// 16 = 0x10
    MFEWSConnection *_offlineConnection;	// 24 = 0x18
    MFEWSResponseOperation *_lastResponseDecoded;	// 32 = 0x20
    NSOperationQueue *_requestResponseQueue;	// 40 = 0x28
}

+ (id)keyPathsForValuesAffectingRequestResponseQueue;	// IMP=0x00000000000ade06
- (id)requestResponseQueue;	// IMP=0x00000000000b0625
@property(retain) MFEWSResponseOperation *lastResponseDecoded; // @synthesize lastResponseDecoded=_lastResponseDecoded;
@property(retain) MFEWSConnection *offlineConnection; // @synthesize offlineConnection=_offlineConnection;
- (void).cxx_destruct;	// IMP=0x00000000000b0636
- (Class)unarchiver:(id)arg1 cannotDecodeObjectOfClassName:(id)arg2 originalClasses:(id)arg3;	// IMP=0x00000000000b0536
- (id)unarchiver:(id)arg1 didDecodeObject:(id)arg2;	// IMP=0x00000000000b045c
- (void)_undeleteMessagesFromFailedDeleteRequest:(id)arg1;	// IMP=0x00000000000b0167
- (void)_undeleteMessagesFromFailedCopyRequest:(id)arg1;	// IMP=0x00000000000afdd8
- (void)_moveMessageFromFailedCreateRequest:(id)arg1 withBackupManager:(id)arg2 toMailboxNamed:(id)arg3 actualName:(id *)arg4;	// IMP=0x00000000000afaa2
- (id)_deleteRequestRemovingUndeletedItems:(id)arg1;	// IMP=0x00000000000af634
- (id)_EWSFolderFromCreateRequestOperation:(id)arg1;	// IMP=0x00000000000af4e1
@property(retain, nonatomic) NSMutableDictionary *offlineToRealEWSIdStrings;
- (id)playbackRequests:(id)arg1 offlineToRealEWSIdStrings:(id *)arg2 error:(id *)arg3;	// IMP=0x00000000000ae14c
- (void)takeRequestOffline:(id)arg1 error:(id)arg2;	// IMP=0x00000000000ae0c1
- (void)addOfflineToRealEWSIdStrings:(id)arg1 forRequest:(id)arg2;	// IMP=0x00000000000adfd2
- (id)resolvedIdStringForIdString:(id)arg1;	// IMP=0x00000000000adeeb
- (void)addRequest:(id)arg1;	// IMP=0x00000000000ade31
- (id)connection;	// IMP=0x00000000000ade1f
- (id)initWithAccount:(id)arg1;	// IMP=0x00000000000add37
- (id)initWithCoder:(id)arg1;	// IMP=0x00000000000add0a
- (id)initWithAccount:(id)arg1 connection:(id)arg2;	// IMP=0x00000000000adbd3

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

