//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Mail/MFEWSRequestOperation.h>

@class MFEWSSyncFolderHierarchyResponseOperation, NSString;

@interface MFEWSSyncFolderHierarchyRequestOperation : MFEWSRequestOperation
{
    NSString *_syncState;	// 24 = 0x18
}

@property(readonly, copy, nonatomic) NSString *syncState; // @synthesize syncState=_syncState;
- (void).cxx_destruct;	// IMP=0x00000000000be33f
- (id)newResponseOperationWithGateway:(id)arg1 errorHandler:(id)arg2;	// IMP=0x00000000000be2ab
@property(retain, nonatomic) MFEWSSyncFolderHierarchyResponseOperation *responseOperation;
- (id)prepareRequest;	// IMP=0x00000000000bdf96
- (id)activityString;	// IMP=0x00000000000bdf29
- (id)initWithGateway:(id)arg1 errorHandler:(id)arg2;	// IMP=0x00000000000bde5a
- (id)initWithSyncState:(id)arg1 createBlock:(CDUnknownBlockType)arg2 updateBlock:(CDUnknownBlockType)arg3 deleteBlock:(CDUnknownBlockType)arg4 gateway:(id)arg5;	// IMP=0x00000000000bdd3c

@end

