//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Mail/MFEWSResponseOperation.h>

@class EWSCreateFolderResponseType, NSString;

@interface MFEWSCreateFolderResponseOperation : MFEWSResponseOperation
{
    NSString *_createdFolderId;	// 24 = 0x18
}

@property(copy) NSString *createdFolderId; // @synthesize createdFolderId=_createdFolderId;
- (void).cxx_destruct;	// IMP=0x000000000007e723
- (void)executeOperation;	// IMP=0x000000000007e21b
- (void)prepareToExecuteWithResponse:(id)arg1 forRequestOperation:(id)arg2;	// IMP=0x000000000007dfde
@property(retain) EWSCreateFolderResponseType *response;

@end

