//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MCAggregateActivity.h"

#import "MFEWSMailboxDataCache.h"

@class MFEWSBackgroundBodyFetchTask, MFEWSFolderHierarchyReconcileTask, MFEWSRetrievePersistedFolderDataTask, NSMutableDictionary, NSString;

@interface MFEWSAccountSyncActivity : MCAggregateActivity <MFEWSMailboxDataCache>
{
    NSMutableDictionary *_mailboxSyncTasksByMailboxURL;	// 8 = 0x8
    BOOL _userInitiated;	// 16 = 0x10
    MFEWSFolderHierarchyReconcileTask *_folderHierarchyReconcileTask;	// 24 = 0x18
    MFEWSRetrievePersistedFolderDataTask *_retrievePersistedFolderDataTask;	// 32 = 0x20
    MFEWSBackgroundBodyFetchTask *_backgroundBodyFetchTask;	// 40 = 0x28
    id <MFEWSAccountSyncActivityDelegate> _mailboxDelegate;	// 48 = 0x30
    id <MFEWSMailboxDataCache> _mailboxDataCache;	// 56 = 0x38
}

@property(nonatomic) __weak id <MFEWSMailboxDataCache> mailboxDataCache; // @synthesize mailboxDataCache=_mailboxDataCache;
@property(nonatomic) __weak id <MFEWSAccountSyncActivityDelegate> mailboxDelegate; // @synthesize mailboxDelegate=_mailboxDelegate;
@property(retain, nonatomic) MFEWSBackgroundBodyFetchTask *backgroundBodyFetchTask; // @synthesize backgroundBodyFetchTask=_backgroundBodyFetchTask;
@property(retain, nonatomic) MFEWSRetrievePersistedFolderDataTask *retrievePersistedFolderDataTask; // @synthesize retrievePersistedFolderDataTask=_retrievePersistedFolderDataTask;
@property(retain, nonatomic) MFEWSFolderHierarchyReconcileTask *folderHierarchyReconcileTask; // @synthesize folderHierarchyReconcileTask=_folderHierarchyReconcileTask;
- (void).cxx_destruct;	// IMP=0x000000000006c1ba
- (void)dataNotFoundForURL:(id)arg1;	// IMP=0x000000000006bff2
- (void)updateCachedFolderID:(id)arg1 andSyncState:(id)arg2 forMailboxURL:(id)arg3;	// IMP=0x000000000006beeb
- (id)cachedSyncStateForMailboxURL:(id)arg1;	// IMP=0x000000000006be65
- (id)cachedFolderIDForMailboxURL:(id)arg1;	// IMP=0x000000000006bddf
- (void)childActivityFinished:(id)arg1;	// IMP=0x000000000006b9d1
- (void)addMailboxURLsToReconcile:(id)arg1;	// IMP=0x000000000006b4e9
- (void)reconcileFolderHierarchyWithSyncState:(id)arg1;	// IMP=0x000000000006b449
@property(nonatomic) BOOL userInitiated;
@property(readonly, nonatomic) BOOL currentlySynchronizingMailboxContents;
- (id)init;	// IMP=0x000000000006b322

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

