//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "NSImmediateActionAnimationController.h"

@class AttachmentViewController, NSString;

@interface _MarkupImmediateActionAnimationController : NSObject <NSImmediateActionAnimationController>
{
    AttachmentViewController *_attachment;	// 8 = 0x8
}

@property(retain, nonatomic) AttachmentViewController *attachment; // @synthesize attachment=_attachment;
- (void).cxx_destruct;	// IMP=0x000000010031b0d7
- (void)recognizerDidCompleteAnimation:(id)arg1;	// IMP=0x000000010031af59

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

