//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "MessageListContentChange.h"

@class NSIndexSet, NSString;

@interface _MessageListAddedIndexesContentChange : NSObject <MessageListContentChange>
{
    NSIndexSet *_indexes;	// 8 = 0x8
    unsigned long long _animationOptions;	// 16 = 0x10
}

@property(readonly, nonatomic) unsigned long long animationOptions; // @synthesize animationOptions=_animationOptions;
@property(readonly, copy, nonatomic) NSIndexSet *indexes; // @synthesize indexes=_indexes;
- (void).cxx_destruct;	// IMP=0x00000001001fdea2
@property(readonly, copy) NSString *description;
- (unsigned long long)shiftIndex:(unsigned long long)arg1;	// IMP=0x00000001001fdc9a
- (void)applyToTableView:(id)arg1;	// IMP=0x00000001001fdc16
- (id)init;	// IMP=0x00000001001fdb47
- (id)initWithIndexes:(id)arg1 animationOptions:(unsigned long long)arg2;	// IMP=0x00000001001fdaba

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

