//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTMSpecialMailbox.h"

@interface _MTMJunkMailbox : MTMSpecialMailbox
{
}

- (BOOL)enabled;	// IMP=0x000000010025b786
- (id)defaultMessageColumnAttributesKey;	// IMP=0x000000010025b767
- (id)displayName;	// IMP=0x000000010025b6fa

@end

