//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class MFMailbox, MFMessageStore, NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSSet;

@interface _TransferOperation : NSObject
{
    NSMutableArray *_sourceMessages;	// 8 = 0x8
    NSMutableArray *_documentIDs;	// 16 = 0x10
    id _messagesForGmailLabelsToRemoveLock;	// 24 = 0x18
    NSMutableDictionary *_messagesForGmailLabelsToRemove;	// 32 = 0x20
    BOOL _editableDocuments;	// 40 = 0x28
    MFMessageStore *_sourceStore;	// 48 = 0x30
    MFMailbox *_destinationMailbox;	// 56 = 0x38
    NSArray *_unreadSourceMessages;	// 64 = 0x40
    NSSet *_destinationLibraryIDs;	// 72 = 0x48
}

@property(readonly, nonatomic) BOOL editableDocuments; // @synthesize editableDocuments=_editableDocuments;
@property(retain) NSSet *destinationLibraryIDs; // @synthesize destinationLibraryIDs=_destinationLibraryIDs;
@property(retain) NSArray *unreadSourceMessages; // @synthesize unreadSourceMessages=_unreadSourceMessages;
@property(readonly, nonatomic) MFMailbox *destinationMailbox; // @synthesize destinationMailbox=_destinationMailbox;
@property(readonly, nonatomic) MFMessageStore *sourceStore; // @synthesize sourceStore=_sourceStore;
- (void).cxx_destruct;	// IMP=0x0000000100221f02
@property(readonly, copy) NSDictionary *popMessagesForGmailLabelsToRemove;
- (void)addMessage:(id)arg1 forLabelsToRemove:(id)arg2;	// IMP=0x0000000100221c92
@property(readonly, copy) NSDictionary *messagesForGmailLabelsToRemove;
- (void)removeSourceMessages:(id)arg1;	// IMP=0x0000000100221b58
- (void)addSourceMessage:(id)arg1;	// IMP=0x000000010008997f
@property(retain, nonatomic) NSArray *sourceMessages;
@property(readonly, nonatomic) NSArray *documentIDs; // @synthesize documentIDs=_documentIDs;
@property(readonly) id <MCMessageDataSource> sourceLibraryStore;
- (id)init;	// IMP=0x000000010022194d
- (id)initWithSourceStore:(id)arg1 destinationMailbox:(id)arg2 editableDocuments:(BOOL)arg3;	// IMP=0x0000000100089838

@end

