//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "NSAccessibilityGroup.h"

@class NSString;

@interface BannerBackgroundView : NSView <NSAccessibilityGroup>
{
    long long _bannerBackgroundStyle;	// 152 = 0x98
}

- (void)setBannerBackgroundStyle:(long long)arg1;	// IMP=0x00000001000e71d0
- (long long)bannerBackgroundStyle;	// IMP=0x00000001000a9de7
- (void)_bannerBackgroundViewCommonInit;	// IMP=0x00000001000a9724
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000e718b
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000a96bc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

