//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class BannerBackgroundView, BannerContainerViewController, ConversationMember, MUIWebDocument, MessageWebDocumentView, NSColor, NSLayoutConstraint, NSLayoutGuide, NSView;

@interface BannerViewController : NSViewController
{
    BOOL _loaded;	// 100 = 0x64
    BOOL _wantsDisplay;	// 101 = 0x65
    BOOL _viewIsLoaded;	// 102 = 0x66
    BannerContainerViewController *_container;	// 104 = 0x68
    NSLayoutGuide *_leadingMarginGuide;	// 112 = 0x70
    NSView *_leadingView;	// 120 = 0x78
    NSLayoutConstraint *_leadingConstraint;	// 128 = 0x80
}

+ (id)keyPathsForValuesAffectingWebDocument;	// IMP=0x00000001000e7845
+ (id)keyPathsForValuesAffectingWebDocumentView;	// IMP=0x00000001000e77d5
@property(nonatomic) __weak NSLayoutConstraint *leadingConstraint; // @synthesize leadingConstraint=_leadingConstraint;
@property(nonatomic) __weak NSView *leadingView; // @synthesize leadingView=_leadingView;
@property(nonatomic) BOOL viewIsLoaded; // @synthesize viewIsLoaded=_viewIsLoaded;
@property(nonatomic) BannerContainerViewController *container; // @synthesize container=_container;
- (void).cxx_destruct;	// IMP=0x00000001000e7ac1
- (void)updateViewConstraints;	// IMP=0x00000001000e791d
@property(nonatomic) __weak NSLayoutGuide *leadingMarginGuide; // @synthesize leadingMarginGuide=_leadingMarginGuide;
- (void)updateWantsDisplay;	// IMP=0x00000001000e786b
- (void)updateBannerContents;	// IMP=0x00000001000e7865
@property(nonatomic) BOOL wantsDisplay;
@property(nonatomic) BOOL loaded;
@property(readonly, nonatomic) MUIWebDocument *webDocument;
@property(readonly, nonatomic) __weak MessageWebDocumentView *webDocumentView;
@property(readonly, nonatomic) NSColor *backgroundColor;
@property(retain) ConversationMember *representedObject;
@property(retain) BannerBackgroundView *view;
@property(readonly, nonatomic) double bannerHeight;
- (void)_bannerViewControllerCommonInit;	// IMP=0x00000001000e7781
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000e773c
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00000001000e76ca

@end

