//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextFieldCell.h"

@interface BannerTextFieldCell : NSTextFieldCell
{
}

- (void)setAttributedStringValue:(id)arg1;	// IMP=0x00000001000a9333
- (void)setStringValue:(id)arg1;	// IMP=0x00000001000e7611
- (id)_stringAttributes;	// IMP=0x00000001000a9415
- (void)setBackgroundStyle:(long long)arg1;	// IMP=0x00000001000e759f
- (void)_bannerTextFieldCellCommonInit;	// IMP=0x00000001000a92a9
- (id)initTextCell:(id)arg1;	// IMP=0x00000001000e755a
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000a9264

@end

