//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "ComposeContext.h"

@class ComposeWindowController, MessageWebDocumentView, NSDictionary, NSSet, NSString;

@interface BasicComposeContext : NSObject <ComposeContext>
{
    BOOL _isMiniaturized;	// 8 = 0x8
    NSSet *_targetMessages;	// 16 = 0x10
    MessageWebDocumentView *_originalContentView;	// 24 = 0x18
    long long _type;	// 32 = 0x20
    NSDictionary *_editorSettings;	// 40 = 0x28
    ComposeWindowController *_windowController;	// 48 = 0x30
}

@property(nonatomic) __weak ComposeWindowController *windowController; // @synthesize windowController=_windowController;
@property(nonatomic) BOOL isMiniaturized; // @synthesize isMiniaturized=_isMiniaturized;
@property(copy, nonatomic) NSDictionary *editorSettings; // @synthesize editorSettings=_editorSettings;
@property(readonly, nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) __weak MessageWebDocumentView *originalContentView; // @synthesize originalContentView=_originalContentView;
@property(readonly, copy, nonatomic) NSSet *targetMessages; // @synthesize targetMessages=_targetMessages;
- (void).cxx_destruct;	// IMP=0x00000001000ea40c
- (void)controllerWillClose:(id)arg1;	// IMP=0x00000001000ea343
- (id)windowControllerWithState:(id)arg1;	// IMP=0x00000001000e9d5a
- (void)presentEditor:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e9d4a
- (void)loadCompleted:(id)arg1;	// IMP=0x00000001000e9d44
- (void)controllerInitialized:(id)arg1;	// IMP=0x00000001000e9d3e
- (void)generateQuotedContentWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000e9afa
@property(readonly, nonatomic) BOOL blockRemoteContent;
@property(readonly, nonatomic) BOOL shouldBlockTermination;
@property(readonly, nonatomic) BOOL isInteractive;
@property(readonly, nonatomic) BOOL shouldTransientlyActivateApplication;
- (struct CGRect)contentScreenPosition;	// IMP=0x00000001000e99fd
- (id)init;	// IMP=0x00000001000e992e
- (id)initWithType:(long long)arg1 targetMessages:(id)arg2;	// IMP=0x00000001000e98b4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

