//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSValueTransformer.h"

@interface DetailsTextValueTransformer : NSValueTransformer
{
}

+ (BOOL)allowsReverseTransformation;	// IMP=0x00000001002d7dfb
+ (Class)transformedValueClass;	// IMP=0x00000001002d7de2
- (id)transformedValue:(id)arg1;	// IMP=0x00000001002d7e03

@end

