//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DOMHTMLImageElement.h"

@interface DOMHTMLImageElement (MailHTMLAttachments)
- (BOOL)getNewElement:(id *)arg1 usingAttachments:(id)arg2 excludeRemoteImages:(BOOL)arg3;	// IMP=0x00000001000e674f
@end

