//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "Assistant.h"

#import "MFLibraryUpgraderDelegate.h"
#import "MFPersistenceVersionUpgraderDelegate.h"

@class MFLibraryUpgrader, MFPersistenceVersionUpgrader, NSButton, NSString, NSView;

@interface LibraryUpgradeAssistant : Assistant <MFLibraryUpgraderDelegate, MFPersistenceVersionUpgraderDelegate>
{
    MFLibraryUpgrader *_libraryUpgrader;	// 8 = 0x8
    NSView *_currentView;	// 16 = 0x10
    long long _state;	// 24 = 0x18
    BOOL _accountsRequireStoragePolicyChange;	// 32 = 0x20
    BOOL _isProgressIndeterminate;	// 33 = 0x21
    NSView *_accountsRequireCachePolicyChangeView;	// 40 = 0x28
    NSView *_patienceView;	// 48 = 0x30
    NSView *_epilogueView;	// 56 = 0x38
    NSView *_errorView;	// 64 = 0x40
    NSButton *_showNewFeaturesButton;	// 72 = 0x48
    MFPersistenceVersionUpgrader *_persistenceVersionUpgrader;	// 80 = 0x50
    NSString *_statusMessage;	// 88 = 0x58
    double _progress;	// 96 = 0x60
}

@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(nonatomic) BOOL isProgressIndeterminate; // @synthesize isProgressIndeterminate=_isProgressIndeterminate;
@property(copy, nonatomic) NSString *statusMessage; // @synthesize statusMessage=_statusMessage;
@property(readonly, nonatomic) MFPersistenceVersionUpgrader *persistenceVersionUpgrader; // @synthesize persistenceVersionUpgrader=_persistenceVersionUpgrader;
@property(nonatomic) BOOL accountsRequireStoragePolicyChange; // @synthesize accountsRequireStoragePolicyChange=_accountsRequireStoragePolicyChange;
@property(nonatomic) __weak NSButton *showNewFeaturesButton; // @synthesize showNewFeaturesButton=_showNewFeaturesButton;
@property(retain, nonatomic) NSView *errorView; // @synthesize errorView=_errorView;
@property(retain, nonatomic) NSView *epilogueView; // @synthesize epilogueView=_epilogueView;
@property(retain, nonatomic) NSView *patienceView; // @synthesize patienceView=_patienceView;
@property(retain, nonatomic) NSView *accountsRequireCachePolicyChangeView; // @synthesize accountsRequireCachePolicyChangeView=_accountsRequireCachePolicyChangeView;
- (void).cxx_destruct;	// IMP=0x00000001001b7177
- (void)upgrader:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x00000001001b6e7d
- (void)upgraderDidFinish:(id)arg1;	// IMP=0x00000001001b6d6c
- (void)persistenceUpgraderDidFinish;	// IMP=0x00000001001b6c72
- (void)showNewFeatures:(id)arg1;	// IMP=0x00000001001b6bfc
- (void)requestUserAttentionWithRequestType:(unsigned long long)arg1;	// IMP=0x00000001001b6b90
- (void)goForward;	// IMP=0x00000001001b6a7c
- (void)stop;	// IMP=0x00000001001b6a34
- (void)start;	// IMP=0x00000001001b6765
@property(retain, nonatomic) NSView *currentView;
@property(nonatomic) long long state;
- (id)windowTitle;	// IMP=0x00000001001b619d
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001001b5c0d
@property(retain, nonatomic) MFLibraryUpgrader *libraryUpgrader;
- (void)dealloc;	// IMP=0x00000001001b59d6
- (id)initWithAssistantManager:(id)arg1;	// IMP=0x00000001001b5808

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

