//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "MailboxOutlineItemControllerDelegate.h"
#import "MailboxSelectionOwner.h"
#import "MailboxesOutlineViewDelegate.h"
#import "NSOutlineViewDataSource.h"

@class MFMailbox, MailboxesOutlineView, NSArray, NSDictionary, NSMapTable, NSString, NSWindow;

@interface MailboxesOutlineViewController : NSObject <MailboxesOutlineViewDelegate, MailboxSelectionOwner, NSOutlineViewDataSource, MailboxOutlineItemControllerDelegate>
{
    double _idealOutlineViewWidth;	// 8 = 0x8
    id <MailboxesOutlineViewControllerDelegate> _delegate;	// 16 = 0x10
    NSMapTable *_itemControllers;	// 24 = 0x18
    MailboxesOutlineView *_outlineView;	// 32 = 0x20
    MFMailbox *_clickedMailbox;	// 40 = 0x28
    long long _reloadingCount;	// 48 = 0x30
    long long _wantsToEditInlineCount;	// 56 = 0x38
    NSDictionary *_accountsByLegacyAccountURLStrings;	// 64 = 0x40
    MFMailbox *_errorMailbox;	// 72 = 0x48
    NSString *_errorMailboxName;	// 80 = 0x50
}

@property(copy) NSString *errorMailboxName; // @synthesize errorMailboxName=_errorMailboxName;
@property(retain) MFMailbox *errorMailbox; // @synthesize errorMailbox=_errorMailbox;
@property(copy) NSDictionary *accountsByLegacyAccountURLStrings; // @synthesize accountsByLegacyAccountURLStrings=_accountsByLegacyAccountURLStrings;
@property long long wantsToEditInlineCount; // @synthesize wantsToEditInlineCount=_wantsToEditInlineCount;
@property long long reloadingCount; // @synthesize reloadingCount=_reloadingCount;
@property(retain) MFMailbox *clickedMailbox; // @synthesize clickedMailbox=_clickedMailbox;
@property(retain) MailboxesOutlineView *outlineView; // @synthesize outlineView=_outlineView;
- (void).cxx_destruct;	// IMP=0x00000001001de8e3
- (void)_didPresentErrorWithRecovery:(BOOL)arg1 contextInfo:(void *)arg2;	// IMP=0x00000001001de67d
- (void)mailbox:(id)arg1 nameUpdated:(id)arg2;	// IMP=0x00000001001de210
- (unsigned long long)badgeCountForItem:(id)arg1;	// IMP=0x000000010001c0da
- (id)mailboxesOutlineView;	// IMP=0x00000001001de1fc
- (void)outlineViewItemDidCollapse:(id)arg1;	// IMP=0x00000001001de153
- (void)outlineViewItemDidExpand:(id)arg1;	// IMP=0x000000010002d696
- (void)didCloseContextMenu:(id)arg1;	// IMP=0x0000000100092834
- (void)willShowContextMenu:(id)arg1;	// IMP=0x000000010008fac0
- (void)setFirstResponderAfterMouseDownOnOutlineView:(id)arg1;	// IMP=0x000000010005af1f
- (void)selectAllInOutlineView:(id)arg1;	// IMP=0x00000001001de116
- (void)outlineView:(id)arg1 didAddRowView:(id)arg2 forRow:(long long)arg3;	// IMP=0x000000010001b8e5
- (void)outlineView:(id)arg1 didRemoveRowView:(id)arg2 forRow:(long long)arg3;	// IMP=0x000000010002d184
- (void)outlineViewSelectionDidChange:(id)arg1;	// IMP=0x000000010002e77d
- (id)outlineView:(id)arg1 selectionIndexesForProposedSelection:(id)arg2;	// IMP=0x000000010005aae8
- (BOOL)outlineView:(id)arg1 shouldCollapseItem:(id)arg2;	// IMP=0x000000010001b23d
- (BOOL)outlineView:(id)arg1 shouldExpandItem:(id)arg2;	// IMP=0x000000010002d3ff
- (double)outlineView:(id)arg1 heightOfRowByItem:(id)arg2;	// IMP=0x00000001000197b6
- (BOOL)outlineView:(id)arg1 isGroupItem:(id)arg2;	// IMP=0x00000001000196d5
- (id)outlineView:(id)arg1 viewForTableColumn:(id)arg2 item:(id)arg3;	// IMP=0x0000000100019dbb
- (id)outlineView:(id)arg1 rowViewForItem:(id)arg2;	// IMP=0x0000000100019c9c
- (unsigned long long)_outlineView:(id)arg1 validateDrop:(id)arg2 proposedItem:(id)arg3 proposedChildIndex:(long long)arg4 allowStoreCreation:(BOOL)arg5;	// IMP=0x00000001000b0bb9
- (unsigned long long)outlineView:(id)arg1 validateDrop:(id)arg2 proposedItem:(id)arg3 proposedChildIndex:(long long)arg4;	// IMP=0x00000001000b0b38
- (BOOL)outlineView:(id)arg1 acceptDrop:(id)arg2 item:(id)arg3 childIndex:(long long)arg4;	// IMP=0x00000001000b1aac
- (void)pasteboard:(id)arg1 provideDataForType:(id)arg2;	// IMP=0x00000001001ddafb
- (void)outlineView:(id)arg1 draggingSession:(id)arg2 endedAtPoint:(struct CGPoint)arg3 operation:(unsigned long long)arg4;	// IMP=0x00000001001ddab5
- (BOOL)outlineView:(id)arg1 writeItems:(id)arg2 toPasteboard:(id)arg3;	// IMP=0x00000001001dd630
- (id)outlineView:(id)arg1 persistentObjectForItem:(id)arg2;	// IMP=0x00000001001dd586
- (void)_accountsDidChange:(id)arg1;	// IMP=0x00000001001dd51a
- (id)_migrateMailboxPersistentID:(id)arg1;	// IMP=0x00000001001dceb1
- (id)outlineView:(id)arg1 itemForPersistentObject:(id)arg2;	// IMP=0x000000010002f08a
- (id)_itemControllerForItem:(id)arg1 makeIfNecessary:(BOOL)arg2;	// IMP=0x00000001001dcdd2
- (id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3;	// IMP=0x000000010001b2ac
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;	// IMP=0x00000001000192ec
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;	// IMP=0x000000010001b0e6
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;	// IMP=0x0000000100018f74
@property(readonly, nonatomic) NSWindow *mailboxSelectionWindow;
- (void)_revealMailbox:(id)arg1;	// IMP=0x000000010002cc71
- (void)revealMailbox:(id)arg1;	// IMP=0x00000001001dccba
@property(readonly, copy, nonatomic) NSArray *sortedSectionItemsForTimeMachine;
@property(readonly, copy, nonatomic) NSArray *expandedItems;
- (BOOL)sectionIsExpanded:(id)arg1;	// IMP=0x00000001001dcae6
- (BOOL)mailboxIsExpanded:(id)arg1;	// IMP=0x00000001001dca30
- (void)selectPathsToMailboxes:(id)arg1 scrollToVisible:(BOOL)arg2;	// IMP=0x000000010002c845
- (void)selectPathsToMailboxes:(id)arg1;	// IMP=0x000000010002f382
@property(readonly, nonatomic) BOOL isSelectedMailboxSpecial;
@property(readonly, nonatomic) MFMailbox *selectedMailbox;
@property(readonly, copy, nonatomic) NSArray *selectedMailboxes;
- (void)_mailboxPendingNameDidChange:(id)arg1;	// IMP=0x00000001001dc7c7
- (void)_viewerPreferencesChanged:(id)arg1;	// IMP=0x00000001000a8e38
- (void)_userInfoDidChange:(id)arg1;	// IMP=0x00000001001dc5f5
- (void)_displayCountDidChange:(id)arg1;	// IMP=0x00000001000390c0
- (void)_mailboxesActivityDidChange:(id)arg1;	// IMP=0x0000000100038577
- (void)_sectionListingDidChange:(id)arg1;	// IMP=0x0000000100035cc4
- (void)_mailboxPublicStatusDidChange:(id)arg1;	// IMP=0x00000001001dc4de
- (void)_mailboxListingDidChange:(id)arg1;	// IMP=0x0000000100036420
- (void)_accountOfflineStatusDidChange:(id)arg1;	// IMP=0x00000001001dc33b
- (void)_accountAdded:(id)arg1;	// IMP=0x00000001001dc1eb
- (void)rowDoubleClicked:(id)arg1;	// IMP=0x00000001001dc0ae
- (void)rowClicked:(id)arg1;	// IMP=0x000000010005ae43
- (void)newMailboxClicked:(id)arg1;	// IMP=0x00000001001dbf21
- (void)alertClicked:(id)arg1;	// IMP=0x00000001001dbe86
- (id)_mailboxForItem:(id)arg1;	// IMP=0x00000001001dbde3
- (id)_itemForSenderView:(id)arg1;	// IMP=0x00000001001dbcb6
- (BOOL)_isTopLevelItem:(id)arg1;	// IMP=0x00000001000196ec
- (void)_saveSelectionAndReloadItem:(id)arg1;	// IMP=0x000000010003601f
- (void)_updateProgressIndicatorForMailbox:(id)arg1;	// IMP=0x00000001001dbc2b
- (id)_copyActivityMonitorsForMailbox:(id)arg1 finishedCount:(unsigned long long *)arg2 includingDescendants:(BOOL)arg3;	// IMP=0x00000001001dbb11
- (void)_redisplayRowsForItems:(id)arg1;	// IMP=0x0000000100038669
- (unsigned long long)_badgeCountForItem:(id)arg1;	// IMP=0x000000010001c0ed
- (id)_firstChildIfCollapsedSpecialMailbox:(id)arg1;	// IMP=0x0000000100034048
- (void)_endWantsToEditInline;	// IMP=0x00000001001dba0f
- (void)_beginWantsToEditInline;	// IMP=0x00000001001db9dd
@property(readonly) BOOL wantsToEditInline;
- (void)_endReloading;	// IMP=0x000000010003618c
- (void)_beginReloading;	// IMP=0x000000010003615a
@property(readonly) BOOL isReloading;
- (void)editNameOfMailbox:(id)arg1;	// IMP=0x00000001001db75e
- (void)makeMailboxesListFirstResponder;	// IMP=0x00000001001db6f1
@property(nonatomic) double idealOutlineViewWidth; // @synthesize idealOutlineViewWidth=_idealOutlineViewWidth;
@property(readonly, nonatomic) double minimumWidthNeededToUseMailboxes;
@property(readonly, nonatomic) double minimizedOutlineViewWidth;
- (void)clearDelegateBecauseWindowIsClosing;	// IMP=0x00000001000b9f6d
- (void)dealloc;	// IMP=0x00000001000ba674
- (void)_migrateAutosaveName;	// IMP=0x00000001001db4be
@property __weak id <MailboxesOutlineViewControllerDelegate> delegate;
- (void)awakeFromNib;	// IMP=0x0000000100019874
- (id)init;	// IMP=0x0000000100018cc4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

