//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTMMessage.h"

@class NSDictionary;

@interface MTMFakeMessage : MTMMessage
{
    NSDictionary *_messageDescription;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100255093
- (unsigned long long)readFlags;	// IMP=0x000000010025503d
- (unsigned long long)messageFlags;	// IMP=0x0000000100254fe7
- (id)valueForKey:(id)arg1;	// IMP=0x0000000100254fca
- (id)init;	// IMP=0x0000000100254efb
- (id)initWithDescription:(id)arg1;	// IMP=0x0000000100254e83

@end

