//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOutlineView.h"

@class MTMFullWindowController;

@interface MTMOutlineView : NSOutlineView
{
    MTMFullWindowController *_windowController;	// 656 = 0x290
}

@property(nonatomic) __weak MTMFullWindowController *windowController; // @synthesize windowController=_windowController;
- (void).cxx_destruct;	// IMP=0x0000000100258134
- (BOOL)becomeFirstResponder;	// IMP=0x0000000100258095
- (void)selectAll:(id)arg1;	// IMP=0x000000010025808f
- (struct CGRect)frameOfOutlineCellAtRow:(long long)arg1;	// IMP=0x0000000100257f72

@end

