//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableView.h"

@class NSArrayController;

@interface MTMTableView : NSTableView
{
    NSArrayController *_messagesController;	// 448 = 0x1c0
}

@property(retain, nonatomic) NSArrayController *messagesController; // @synthesize messagesController=_messagesController;
- (void).cxx_destruct;	// IMP=0x000000010025b961

@end

