//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

////#import "NSObject.h"

@interface MVMailBundle : NSObject
{
}

+ (id)composeAccessoryViewOwnerClassName;	// IMP=0x000000010026399d
+ (BOOL)hasComposeAccessoryViewOwner;	// IMP=0x000000010000a9d0
+ (id)preferencesPanelName;	// IMP=0x0000000100263943
+ (id)preferencesOwnerClassName;	// IMP=0x0000000100263931
+ (BOOL)hasPreferencesPanel;	// IMP=0x000000010000a9d8
+ (id)sharedInstance;	// IMP=0x000000010000a9e0
+ (void)registerBundle;	// IMP=0x000000010000a7cd
+ (id)composeAccessoryViewOwners;	// IMP=0x00000001002636a3
+ (id)allBundles;	// IMP=0x000000010026368a
+ (id)pluginSupportedCompatibilityUUIDsKey;	// IMP=0x0000000100263604
- (void)dealloc;	// IMP=0x00000001002639f7

@end

