//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FilesystemEmailImporter.h"

@interface NetscapeEmailImporter : FilesystemEmailImporter
{
}

+ (id)explanatoryText;	// IMP=0x0000000100263ada
+ (id)name;	// IMP=0x0000000100263a6d
- (char *)fromString;	// IMP=0x0000000100263b67
- (id)pathExtensions;	// IMP=0x0000000100263b47

@end

