//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSScrollView, WebFrameView, WebView;

@interface NSView (LocatingFrameViews)
@property(readonly, nonatomic) NSScrollView *enclosingScrollViewIgnoringWebScrollbars;
@property(readonly, nonatomic) WebView *enclosingWebView;
@property(readonly, nonatomic) WebFrameView *enclosingFrameView;
@end

