//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MessageListCell.h"

@interface RolloverButtonCell : MessageListCell
{
    id _target;	// 64 = 0x40
    SEL _action;	// 72 = 0x48
}

@property(nonatomic) SEL action; // @synthesize action=_action;
@property(nonatomic) __weak id target; // @synthesize target=_target;
- (void).cxx_destruct;	// IMP=0x0000000100287cee
- (BOOL)accessibilityPerformPress;	// IMP=0x0000000100287bb7
- (id)accessibilityLabel;	// IMP=0x0000000100287a6d
- (BOOL)isAccessibilityEnabled;	// IMP=0x0000000100287a20
- (id)accessibilityRole;	// IMP=0x00000001002879a1
- (id)accessibilityValue;	// IMP=0x0000000100287946
- (BOOL)isAccessibilitySelectorAllowed:(SEL)arg1;	// IMP=0x00000001002878f9
- (unsigned long long)hitTestForEvent:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3;	// IMP=0x0000000100287874
@property(readonly, nonatomic) BOOL shouldSendAction;
- (BOOL)_sendActionFrom:(id)arg1;	// IMP=0x0000000100287754
- (BOOL)trackMouse:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3 untilMouseUp:(BOOL)arg4;	// IMP=0x00000001002875ee

@end

