//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPreferencesModule.h"

#import "MailTableViewDelegate.h"
#import "NSTableViewDataSource.h"
#import "NSWindowDelegate.h"

@class AppleScriptPopUpButton, CriteriaUIHelper, MFMessageRule, MUIAddressField, MailTableView, MailboxesChooser, NSButton, NSMenu, NSMutableArray, NSPanel, NSPopUpButton, NSScrollView, NSString, NSTextField, NSTextView, NSView, SoundPopUpButtonController;

@interface RulesPreferences : NSPreferencesModule <NSTableViewDataSource, MailTableViewDelegate, NSWindowDelegate>
{
    NSMutableArray *_actionViews;	// 48 = 0x30
    BOOL _colorPanelShouldBeHidden;	// 56 = 0x38
    BOOL _isDuplicatingRule;	// 57 = 0x39
    BOOL _hasPendingChanges;	// 58 = 0x3a
    MUIAddressField *_forwardRecipientsField;	// 64 = 0x40
    MUIAddressField *_redirectRecipientsField;	// 72 = 0x48
    MailTableView *_rulesTable;	// 80 = 0x50
    NSButton *_editButton;	// 88 = 0x58
    NSButton *_duplicateButton;	// 96 = 0x60
    NSButton *_removeButton;	// 104 = 0x68
    NSPanel *_ruleDetailPanel;	// 112 = 0x70
    NSTextField *_ruleNameField;	// 120 = 0x78
    NSButton *_ruleHelpButton;	// 128 = 0x80
    NSMenu *_actionMenu;	// 136 = 0x88
    NSScrollView *_actionContainer;	// 144 = 0x90
    NSView *_soundActionView;	// 152 = 0x98
    NSView *_colorActionView;	// 160 = 0xa0
    NSView *_transferActionView;	// 168 = 0xa8
    NSView *_makeCopyActionView;	// 176 = 0xb0
    NSView *_autoReplyActionView;	// 184 = 0xb8
    NSView *_autoForwardActionView;	// 192 = 0xc0
    NSView *_autoRedirectActionView;	// 200 = 0xc8
    NSView *_markDeletedActionView;	// 208 = 0xd0
    NSView *_markAsReadActionView;	// 216 = 0xd8
    NSView *_markAsFlaggedActionView;	// 224 = 0xe0
    NSView *_stopEvaluatingRulesActionView;	// 232 = 0xe8
    NSView *_runAppleScriptActionView;	// 240 = 0xf0
    NSView *_notifyUserActionView;	// 248 = 0xf8
    NSView *_sendNotificationActionView;	// 256 = 0x100
    NSPopUpButton *_colorPopup;	// 264 = 0x108
    NSPopUpButton *_colorStylePopup;	// 272 = 0x110
    NSPopUpButton *_flagColorPopup;	// 280 = 0x118
    SoundPopUpButtonController *_soundPopUpController;	// 288 = 0x120
    AppleScriptPopUpButton *_appleScriptPopup;	// 296 = 0x128
    NSPanel *_responseMessageTextPanel;	// 304 = 0x130
    NSTextView *_responseMessageTextView;	// 312 = 0x138
    CriteriaUIHelper *_criteriaUIHelper;	// 320 = 0x140
    MailboxesChooser *_destinationChooser;	// 328 = 0x148
    MailboxesChooser *_makeCopyDestinationChooser;	// 336 = 0x150
    long long _currentlySelectedRow;	// 344 = 0x158
    MFMessageRule *_ruleBeingValidated;	// 352 = 0x160
    MFMessageRule *_ruleBeingEdited;	// 360 = 0x168
}

@property(nonatomic) BOOL hasPendingChanges; // @synthesize hasPendingChanges=_hasPendingChanges;
@property(nonatomic) BOOL isDuplicatingRule; // @synthesize isDuplicatingRule=_isDuplicatingRule;
@property(retain, nonatomic) MFMessageRule *ruleBeingEdited; // @synthesize ruleBeingEdited=_ruleBeingEdited;
@property(retain, nonatomic) MFMessageRule *ruleBeingValidated; // @synthesize ruleBeingValidated=_ruleBeingValidated;
@property(nonatomic) long long currentlySelectedRow; // @synthesize currentlySelectedRow=_currentlySelectedRow;
@property(nonatomic) BOOL colorPanelShouldBeHidden; // @synthesize colorPanelShouldBeHidden=_colorPanelShouldBeHidden;
@property(retain, nonatomic) MailboxesChooser *makeCopyDestinationChooser; // @synthesize makeCopyDestinationChooser=_makeCopyDestinationChooser;
@property(retain, nonatomic) MailboxesChooser *destinationChooser; // @synthesize destinationChooser=_destinationChooser;
@property(retain, nonatomic) CriteriaUIHelper *criteriaUIHelper; // @synthesize criteriaUIHelper=_criteriaUIHelper;
@property(nonatomic) NSTextView *responseMessageTextView; // @synthesize responseMessageTextView=_responseMessageTextView;
@property(retain, nonatomic) NSPanel *responseMessageTextPanel; // @synthesize responseMessageTextPanel=_responseMessageTextPanel;
@property(nonatomic) __weak AppleScriptPopUpButton *appleScriptPopup; // @synthesize appleScriptPopup=_appleScriptPopup;
@property(retain, nonatomic) SoundPopUpButtonController *soundPopUpController; // @synthesize soundPopUpController=_soundPopUpController;
@property(nonatomic) __weak NSPopUpButton *flagColorPopup; // @synthesize flagColorPopup=_flagColorPopup;
@property(nonatomic) __weak NSPopUpButton *colorStylePopup; // @synthesize colorStylePopup=_colorStylePopup;
@property(nonatomic) __weak NSPopUpButton *colorPopup; // @synthesize colorPopup=_colorPopup;
@property(retain, nonatomic) NSView *sendNotificationActionView; // @synthesize sendNotificationActionView=_sendNotificationActionView;
@property(retain, nonatomic) NSView *notifyUserActionView; // @synthesize notifyUserActionView=_notifyUserActionView;
@property(retain, nonatomic) NSView *runAppleScriptActionView; // @synthesize runAppleScriptActionView=_runAppleScriptActionView;
@property(retain, nonatomic) NSView *stopEvaluatingRulesActionView; // @synthesize stopEvaluatingRulesActionView=_stopEvaluatingRulesActionView;
@property(retain, nonatomic) NSView *markAsFlaggedActionView; // @synthesize markAsFlaggedActionView=_markAsFlaggedActionView;
@property(retain, nonatomic) NSView *markAsReadActionView; // @synthesize markAsReadActionView=_markAsReadActionView;
@property(retain, nonatomic) NSView *markDeletedActionView; // @synthesize markDeletedActionView=_markDeletedActionView;
@property(retain, nonatomic) NSView *autoRedirectActionView; // @synthesize autoRedirectActionView=_autoRedirectActionView;
@property(retain, nonatomic) NSView *autoForwardActionView; // @synthesize autoForwardActionView=_autoForwardActionView;
@property(retain, nonatomic) NSView *autoReplyActionView; // @synthesize autoReplyActionView=_autoReplyActionView;
@property(retain, nonatomic) NSView *makeCopyActionView; // @synthesize makeCopyActionView=_makeCopyActionView;
@property(retain, nonatomic) NSView *transferActionView; // @synthesize transferActionView=_transferActionView;
@property(retain, nonatomic) NSView *colorActionView; // @synthesize colorActionView=_colorActionView;
@property(retain, nonatomic) NSView *soundActionView; // @synthesize soundActionView=_soundActionView;
@property(nonatomic) __weak NSScrollView *actionContainer; // @synthesize actionContainer=_actionContainer;
@property(retain, nonatomic) NSMenu *actionMenu; // @synthesize actionMenu=_actionMenu;
@property(nonatomic) __weak NSButton *ruleHelpButton; // @synthesize ruleHelpButton=_ruleHelpButton;
@property(nonatomic) __weak NSTextField *ruleNameField; // @synthesize ruleNameField=_ruleNameField;
@property(retain, nonatomic) NSPanel *ruleDetailPanel; // @synthesize ruleDetailPanel=_ruleDetailPanel;
@property(nonatomic) __weak NSButton *removeButton; // @synthesize removeButton=_removeButton;
@property(nonatomic) __weak NSButton *duplicateButton; // @synthesize duplicateButton=_duplicateButton;
@property(nonatomic) __weak NSButton *editButton; // @synthesize editButton=_editButton;
@property(nonatomic) __weak MailTableView *rulesTable; // @synthesize rulesTable=_rulesTable;
@property(nonatomic) __weak MUIAddressField *redirectRecipientsField; // @synthesize redirectRecipientsField=_redirectRecipientsField;
@property(nonatomic) __weak MUIAddressField *forwardRecipientsField; // @synthesize forwardRecipientsField=_forwardRecipientsField;
- (void).cxx_destruct;	// IMP=0x0000000100290a4f
- (void)_openAppleScriptDirectoryInFinder;	// IMP=0x00000001002900df
- (id)titleForSoundFile:(id)arg1;	// IMP=0x000000010029002c
- (void)_accountMailboxListingDidChange:(id)arg1;	// IMP=0x000000010028ffba
- (void)actionPopupChanged:(id)arg1;	// IMP=0x000000010028fa42
- (void)_actionPopupWillPopup:(id)arg1;	// IMP=0x000000010028f619
- (void)mailboxSelected:(id)arg1;	// IMP=0x000000010028f613
- (void)flagsToApplyChanged:(id)arg1;	// IMP=0x000000010028f5bd
- (void)responseMessageCancelClicked:(id)arg1;	// IMP=0x000000010028f579
- (void)responseMessageOKClicked:(id)arg1;	// IMP=0x000000010028f535
- (void)setResponseMessageClicked:(id)arg1;	// IMP=0x000000010028f4a9
- (void)colorStyleChanged:(id)arg1;	// IMP=0x000000010028f44d
- (void)colorPicked:(id)arg1;	// IMP=0x000000010028f3d7
- (void)colorChanged:(id)arg1;	// IMP=0x000000010028f276
- (void)cancelClicked:(id)arg1;	// IMP=0x000000010028f207
- (void)okClicked:(id)arg1;	// IMP=0x000000010028e2ed
- (void)runRuleDetailPanelForRule:(id)arg1 inWindow:(id)arg2 withHelpButtonTag:(long long)arg3;	// IMP=0x000000010028d49b
- (void)_validateActionMenuItem:(id)arg1 currentTag:(long long)arg2;	// IMP=0x000000010028d00f
- (void)addAction:(id)arg1;	// IMP=0x000000010028ca13
- (void)_configureActionsForRule:(id)arg1;	// IMP=0x000000010028c243
- (void)_configureFlagColorPopup;	// IMP=0x000000010028c033
- (void)_configureColorPopupForColorStyle:(long long)arg1;	// IMP=0x000000010028bea9
- (void)_addActionForTag:(long long)arg1 atIndex:(unsigned long long)arg2;	// IMP=0x000000010028bbce
- (id)_actionViewForTag:(long long)arg1;	// IMP=0x000000010028b885
- (void)removeAction:(id)arg1;	// IMP=0x000000010028b754
- (void)_setOtherColor:(id)arg1;	// IMP=0x000000010028b67a
- (void)_ensureSelection;	// IMP=0x000000010028b612
- (void)tableViewSelectionDidChange:(id)arg1;	// IMP=0x000000010028b600
- (BOOL)tableView:(id)arg1 acceptDrop:(id)arg2 row:(long long)arg3 dropOperation:(unsigned long long)arg4;	// IMP=0x000000010028b477
- (unsigned long long)tableView:(id)arg1 validateDrop:(id)arg2 proposedRow:(long long)arg3 proposedDropOperation:(unsigned long long)arg4;	// IMP=0x000000010028b456
- (BOOL)_validateDrag:(id)arg1 proposedRow:(long long)arg2 dragOperation:(unsigned long long)arg3;	// IMP=0x000000010028b39c
- (BOOL)tableView:(id)arg1 writeRowsWithIndexes:(id)arg2 toPasteboard:(id)arg3;	// IMP=0x000000010028b282
- (BOOL)mailTableView:(id)arg1 doCommandBySelector:(SEL)arg2;	// IMP=0x000000010028b22e
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;	// IMP=0x000000010028b01b
- (long long)mailTableView:(id)arg1 highlightStyleForRow:(long long)arg2 inRect:(struct CGRect *)arg3 color:(id *)arg4;	// IMP=0x000000010028af40
- (void)tableView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;	// IMP=0x000000010028ac31
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;	// IMP=0x000000010028aa55
- (long long)numberOfRowsInTableView:(id)arg1;	// IMP=0x000000010028aa2a
- (void)removeRule:(id)arg1;	// IMP=0x000000010028a329
- (void)editRule:(id)arg1;	// IMP=0x000000010028a25e
- (void)duplicateRule:(id)arg1;	// IMP=0x000000010028a18e
- (void)createRule:(id)arg1;	// IMP=0x000000010028a108
- (void)saveChanges;	// IMP=0x00000001000afc3e
- (void)initializeFromDefaults;	// IMP=0x0000000100289f93
- (void)_validateButtonState;	// IMP=0x0000000100289e82
- (id)imageForPreferenceNamed:(id)arg1;	// IMP=0x000000010009f9ab
- (id)preferencesNibName;	// IMP=0x0000000100289e63
- (id)viewForPreferenceNamed:(id)arg1;	// IMP=0x0000000100289c8d
- (void)awakeFromNib;	// IMP=0x000000010028976a
- (id)titleForIdentifier:(id)arg1;	// IMP=0x000000010009f855
- (void)dealloc;	// IMP=0x00000001002896f4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

