//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSConcreteTextStorage.h"

@interface ScriptableMessageTextStorage : NSConcreteTextStorage
{
}

- (void)setAttributes:(id)arg1 range:(struct _NSRange)arg2;	// IMP=0x00000001001043f3
- (void)addAttribute:(id)arg1 value:(id)arg2 range:(struct _NSRange)arg3;	// IMP=0x000000010010434e
- (void)replaceCharactersInRange:(struct _NSRange)arg1 withAttributedString:(id)arg2;	// IMP=0x00000001001042dc

@end

