//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "StackElementDelegate.h"

@class CALayer, NSArray, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString;

@interface StackController : NSObject <StackElementDelegate>
{
    NSMutableArray *_stackedItems;	// 8 = 0x8
    NSMutableSet *_stackedItemsSet;	// 16 = 0x10
    NSMutableArray *_orderedItems;	// 24 = 0x18
    NSMutableSet *_orderedItemsSet;	// 32 = 0x20
    NSMutableDictionary *_stackElementsByItem;	// 40 = 0x28
    NSMutableDictionary *_loadRequestDatesByItem;	// 48 = 0x30
    BOOL _isAnimating;	// 56 = 0x38
    BOOL _animateStateTransitions;	// 57 = 0x39
    BOOL _updateNeeded;	// 58 = 0x3a
    BOOL _loadingData;	// 59 = 0x3b
    BOOL _waitingForTransitionToStackState;	// 60 = 0x3c
    BOOL _isTerminating;	// 61 = 0x3d
    BOOL _isSuspended;	// 62 = 0x3e
    BOOL _preventStackBeforeOffscreen;	// 63 = 0x3f
    id <StackDataSource> _dataSource;	// 64 = 0x40
    id <StackDelegate> _delegate;	// 72 = 0x48
    NSArray *_itemsToDisplay;	// 80 = 0x50
    CALayer *_stackContainerLayer;	// 88 = 0x58
    double _lastDisplayedItemsUpdateRequest;	// 96 = 0x60
    double _lastTransitionToStackState;	// 104 = 0x68
    unsigned long long _transactionCount;	// 112 = 0x70
    struct CGSize _stackCenterOffset;	// 120 = 0x78
}

@property(nonatomic) BOOL preventStackBeforeOffscreen; // @synthesize preventStackBeforeOffscreen=_preventStackBeforeOffscreen;
@property(nonatomic) BOOL isSuspended; // @synthesize isSuspended=_isSuspended;
@property(nonatomic) BOOL isTerminating; // @synthesize isTerminating=_isTerminating;
@property(nonatomic) BOOL waitingForTransitionToStackState; // @synthesize waitingForTransitionToStackState=_waitingForTransitionToStackState;
@property(nonatomic) BOOL loadingData; // @synthesize loadingData=_loadingData;
@property(nonatomic) BOOL updateNeeded; // @synthesize updateNeeded=_updateNeeded;
@property(nonatomic) unsigned long long transactionCount; // @synthesize transactionCount=_transactionCount;
@property(nonatomic) double lastTransitionToStackState; // @synthesize lastTransitionToStackState=_lastTransitionToStackState;
@property(nonatomic) double lastDisplayedItemsUpdateRequest; // @synthesize lastDisplayedItemsUpdateRequest=_lastDisplayedItemsUpdateRequest;
@property(nonatomic) struct CGSize stackCenterOffset; // @synthesize stackCenterOffset=_stackCenterOffset;
@property(retain, nonatomic) CALayer *stackContainerLayer; // @synthesize stackContainerLayer=_stackContainerLayer;
@property(copy, nonatomic) NSArray *itemsToDisplay; // @synthesize itemsToDisplay=_itemsToDisplay;
@property(nonatomic) BOOL animateStateTransitions; // @synthesize animateStateTransitions=_animateStateTransitions;
@property(nonatomic) __weak id <StackDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <StackDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;	// IMP=0x00000001002b3e36
- (void)stackElement:(id)arg1 targetStateDidChangeFrom:(long long)arg2 to:(long long)arg3;	// IMP=0x00000001002b3b02
- (void)stackElement:(id)arg1 currentStateDidChangeFrom:(long long)arg2 to:(long long)arg3;	// IMP=0x00000001002b3712
- (void)stackElement:(id)arg1 willRemoveLayer:(id)arg2;	// IMP=0x00000001002b350a
- (id)layerForStackElement:(id)arg1;	// IMP=0x00000001002b339a
@property(readonly, nonatomic) BOOL stackIsTerminating;
- (void)cancelPendingActions;	// IMP=0x00000001002b3369
- (void)updateIsAnimating;	// IMP=0x00000001002b31cd
@property(nonatomic) BOOL isAnimating;
- (BOOL)isAnyStackElementBeingStacked;	// IMP=0x00000001002b2f44
- (id)stackElementToReshowUnderneathStackElement:(id)arg1;	// IMP=0x00000001002b2cff
- (id)orderedStackedElementsWithOrientation:(long long)arg1;	// IMP=0x00000001002b2a9d
- (void)stackDataSourceDidLoadItemData:(id)arg1;	// IMP=0x00000001002b298a
- (void)updateOrientationForStackElement:(id)arg1;	// IMP=0x00000001002b256c
- (void)updateStackElement:(id)arg1;	// IMP=0x00000001002b1fa8
- (void)updateStackElements;	// IMP=0x00000001002b1b59
- (void)setNeedsToUpdateStackElements;	// IMP=0x00000001002b1b0d
- (void)endTransaction;	// IMP=0x00000001002b1a7f
- (void)beginTransaction;	// IMP=0x00000001002b1a4d
- (BOOL)isDataAvailableForStackElement:(id)arg1 loadIfNeeded:(BOOL)arg2;	// IMP=0x00000001002b1826
- (void)removeStackElement:(id)arg1;	// IMP=0x00000001002b16f0
- (id)stackElementForItem:(id)arg1 createIfNeeded:(BOOL)arg2 withInitialState:(long long)arg3;	// IMP=0x00000001002b15e6
- (id)stackElementForItem:(id)arg1 createIfNeeded:(BOOL)arg2;	// IMP=0x00000001002b15ce
- (id)keyForItem:(id)arg1;	// IMP=0x00000001002b1577
- (void)removeStackedLayers:(BOOL)arg1;	// IMP=0x00000001002b1312
- (void)updateDisplayedItems;	// IMP=0x00000001002b061c
- (void)addStackedItem:(id)arg1;	// IMP=0x00000001002b046e
- (void)setNeedsToUpdateDisplayedItems:(BOOL)arg1 immediately:(BOOL)arg2;	// IMP=0x00000001002b0306
- (void)displayStackedLayersForItems:(id)arg1 animated:(BOOL)arg2;	// IMP=0x00000001002b0162
- (void)dealloc;	// IMP=0x00000001002aff4f
- (id)init;	// IMP=0x00000001002afd94

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

