//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTMSpecialMailbox.h"

@interface _MTMSubMetaMailbox : MTMSpecialMailbox
{
}

- (id)messageListFont;	// IMP=0x000000010025a911
- (id)messageListColor;	// IMP=0x000000010025a8c1
- (id)severalMessagesFormatString;	// IMP=0x000000010025a871
- (id)oneMesageString;	// IMP=0x000000010025a821
- (id)displayNameInMessageList;	// IMP=0x000000010025a75f
- (id)displayNameForList;	// IMP=0x000000010025a70f
- (id)defaultMessageColumnAttributesKey;	// IMP=0x000000010025a6bf
- (id)messageColumnConfiguration;	// IMP=0x000000010025a66f
- (id)restoreString;	// IMP=0x000000010025a55e
- (id)restoreMode;	// IMP=0x000000010025a50e
- (id)identifier;	// IMP=0x000000010025a4be
- (id)recoverDisplayName;	// IMP=0x000000010025a3f4
- (id)displayName;	// IMP=0x000000010025a3a4

@end

