//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "MCActivityTarget.h"
#import "WebFrameLoadDelegate.h"
#import "WebResourceLoadDelegate.h"

@class EditableWebMessageDocument, NSArray, NSBitmapImageRep, NSString, NSWindow, Stationery, StationeryLoader, WebView;

@interface _StationeryThumbnailCreator : NSObject <MCActivityTarget, WebFrameLoadDelegate, WebResourceLoadDelegate>
{
    StationeryLoader *_delegate;	// 8 = 0x8
    NSArray *_stationeryPaths;	// 16 = 0x10
    unsigned long long _currentStationeryIndex;	// 24 = 0x18
    Stationery *_currentStationery;	// 32 = 0x20
    WebView *_webView;	// 40 = 0x28
    NSWindow *_window;	// 48 = 0x30
    EditableWebMessageDocument *_webMessageDocument;	// 56 = 0x38
    NSBitmapImageRep *_snapshot;	// 64 = 0x40
}

@property(retain, nonatomic) NSBitmapImageRep *snapshot; // @synthesize snapshot=_snapshot;
@property(retain, nonatomic) EditableWebMessageDocument *webMessageDocument; // @synthesize webMessageDocument=_webMessageDocument;
@property(retain, nonatomic) NSWindow *window; // @synthesize window=_window;
@property(retain, nonatomic) WebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) Stationery *currentStationery; // @synthesize currentStationery=_currentStationery;
@property(nonatomic) unsigned long long currentStationeryIndex; // @synthesize currentStationeryIndex=_currentStationeryIndex;
@property(copy, nonatomic) NSArray *stationeryPaths; // @synthesize stationeryPaths=_stationeryPaths;
@property(nonatomic) __weak StationeryLoader *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x00000001002d1535
- (void)scaleSnapshotAndSendToDelegate;	// IMP=0x00000001002d1019
- (void)takeSnapshot;	// IMP=0x00000001002d0e00
- (void)performTakeSnapshot;	// IMP=0x00000001002d0ba5
- (void)webView:(id)arg1 didFinishLoadForFrame:(id)arg2;	// IMP=0x00000001002d0a55
- (void)moveOnToTheNextStationery;	// IMP=0x00000001002d0559
- (void)loadParsedMessage:(id)arg1;	// IMP=0x00000001002d043c
- (void)createWebView;	// IMP=0x00000001002d01a4
- (void)createThumbnailsForCustomStationeriesWithPaths:(id)arg1;	// IMP=0x00000001002d0043
- (void)dealloc;	// IMP=0x00000001002cff8a

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, copy, nonatomic) NSString *displayName;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) BOOL isSmartMailbox;
@property(readonly) Class superclass;

@end

