//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class MCProgressManager;

@interface ActivityWindowController : NSWindowController
{
    MCProgressManager *_progressManager;	// 80 = 0x50
}

@property(readonly, nonatomic) MCProgressManager *progressManager; // @synthesize progressManager=_progressManager;
- (void).cxx_destruct;	// IMP=0x00000001000cd847
- (id)windowNibName;	// IMP=0x00000001000cd817
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000cd748
- (id)initWithWindow:(id)arg1;	// IMP=0x00000001000cd679
- (id)init;	// IMP=0x00000001000cd60c

@end

