//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "AccountStatusDataSourceDelegate.h"

@class AccountStatusDataSource, ComposeViewController, NSButton, NSError, NSPanel, NSString, NSTableView, NSTextField, NSTextView, NSView;

@interface DeliveryFailure : NSObject <AccountStatusDataSourceDelegate>
{
    NSPanel *_panel;	// 8 = 0x8
    NSTextField *_errorLabel;	// 16 = 0x10
    NSTextView *_errorDescriptionLabel;	// 24 = 0x18
    NSView *_contents;	// 32 = 0x20
    NSTableView *_table;	// 40 = 0x28
    NSButton *_tryLaterButton;	// 48 = 0x30
    NSButton *_tryOtherButton;	// 56 = 0x38
    AccountStatusDataSource *_deliveryASDS;	// 64 = 0x40
    ComposeViewController *_composeViewController;	// 72 = 0x48
    NSError *_error;	// 80 = 0x50
}

@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic) __weak ComposeViewController *composeViewController; // @synthesize composeViewController=_composeViewController;
@property(readonly, nonatomic) AccountStatusDataSource *deliveryASDS; // @synthesize deliveryASDS=_deliveryASDS;
@property(nonatomic) __weak NSButton *tryOtherButton; // @synthesize tryOtherButton=_tryOtherButton;
@property(nonatomic) __weak NSButton *tryLaterButton; // @synthesize tryLaterButton=_tryLaterButton;
@property(nonatomic) __weak NSTableView *table; // @synthesize table=_table;
@property(nonatomic) __weak NSView *contents; // @synthesize contents=_contents;
@property(nonatomic) NSTextView *errorDescriptionLabel; // @synthesize errorDescriptionLabel=_errorDescriptionLabel;
@property(nonatomic) __weak NSTextField *errorLabel; // @synthesize errorLabel=_errorLabel;
@property(retain, nonatomic) NSPanel *panel; // @synthesize panel=_panel;
- (void).cxx_destruct;	// IMP=0x000000010014ab89
- (void)_retile;	// IMP=0x000000010014a760
- (void)_tile;	// IMP=0x00000001001499c0
- (void)_postDeliveryFailureHappened;	// IMP=0x0000000100149966
- (void)_deliveryAccountsDidChange:(id)arg1;	// IMP=0x0000000100149884
- (void)_selectedAccountDidChangeFrom:(id)arg1 to:(id)arg2;	// IMP=0x00000001001496ff
- (id)_setDynamicDeliveryAccountForAccount:(id)arg1;	// IMP=0x00000001001495f0
- (void)editServerList:(id)arg1;	// IMP=0x000000010014957d
- (void)tryOtherAccount:(id)arg1;	// IMP=0x00000001001494c2
- (void)editMessage:(id)arg1;	// IMP=0x0000000100149407
- (void)sendLater:(id)arg1;	// IMP=0x000000010014934f
- (void)runChooseAlternateDeliveryAccountSheet;	// IMP=0x0000000100148839
- (void)reportError:(id)arg1;	// IMP=0x0000000100147557
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010014739d
- (void)composeViewControllerWillClose;	// IMP=0x0000000100147339
- (void)dealloc;	// IMP=0x000000010014729f
- (void)awakeFromNib;	// IMP=0x00000001001471ed
- (id)init;	// IMP=0x000000010014711e
- (id)initWithComposeViewController:(id)arg1;	// IMP=0x0000000100146f9f

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

