//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class ImportAssistant, NSArray, NSMutableArray, NSString;

@interface Importer : NSObject
{
    NSMutableArray *_importArray;	// 8 = 0x8
    BOOL _importCanceled;	// 16 = 0x10
    ImportAssistant *_delegate;	// 24 = 0x18
}

@property(nonatomic) BOOL importCanceled; // @synthesize importCanceled=_importCanceled;
@property(retain, nonatomic) ImportAssistant *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x00000001001af94e
@property(readonly, copy, nonatomic) NSString *importFinishedText;
- (void)sortImportArray;	// IMP=0x00000001001af74a
@property(readonly, nonatomic) unsigned long long countOfEnabledItems;
- (void)insertObject:(id)arg1 inImportArrayAtIndex:(unsigned long long)arg2;	// IMP=0x00000001001af5da
- (void)clearImportArray;	// IMP=0x00000001001af5bd
@property(readonly, nonatomic) unsigned long long countOfImportArray;
@property(readonly, copy, nonatomic) NSArray *importArray;
@property(readonly, copy, nonatomic) NSString *name;
- (id)init;	// IMP=0x00000001001af4ed

@end

