//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class NSArray;

@protocol ManagedListSortInfo <NSObject>
- (void)unregisterSortInfoForObject:(id)arg1;
- (void)registerSortInfoForObjects:(NSArray *)arg1;
- (void)registerSortInfoForObject:(id)arg1;
@end

