//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@interface MessageEditor : NSObject
{
}

+ (id)sharedMessageEditor;	// IMP=0x00000001001f871d
+ (void)initialize;	// IMP=0x00000001001f86ca
- (void)setBackEnd:(id)arg1;	// IMP=0x00000001001f898f
- (id)objectSpecifier;	// IMP=0x00000001001f8900
- (void)dealloc;	// IMP=0x00000001001f8852
- (id)init;	// IMP=0x00000001001f872e

@end

