//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "MTMMailboxControllerProtocol.h"
#import "NSToolbarDelegate.h"

@class MTMMailbox, MailToolbar, NSArray, NSAttributedString, NSDictionary, NSMutableDictionary, NSString, NSURL, NSWindow, StarFieldController;

@interface MTMWindowController : NSWindowController <MTMMailboxControllerProtocol, NSToolbarDelegate>
{
    NSURL *_mailLibraryURL;	// 80 = 0x50
    NSURL *_focusURL;	// 88 = 0x58
    NSMutableDictionary *_accounts;	// 96 = 0x60
    BOOL _activated;	// 104 = 0x68
    BOOL _bindingsAreSet;	// 105 = 0x69
    MailToolbar *_toolbar;	// 112 = 0x70
    StarFieldController *_controller;	// 120 = 0x78
    MTMMailbox *_rootMailbox;	// 128 = 0x80
    NSDictionary *_preferences;	// 136 = 0x88
    NSDictionary *_toolbarItems;	// 144 = 0x90
    NSDictionary *_tableOfContents;	// 152 = 0x98
}

+ (void)loadPreferences:(id *)arg1 accounts:(id *)arg2 tableOfContents:(id *)arg3 rootMailbox:(id *)arg4 forLibraryURL:(id)arg5;	// IMP=0x000000010025c7be
+ (BOOL)_loadTableOfContents:(id *)arg1 forLibraryURL:(id)arg2;	// IMP=0x000000010025c68a
+ (id)focusURLInCurrentSnapshotForFocusURL:(id)arg1;	// IMP=0x000000010025c44c
+ (id)baseLibraryURLFromMailLibraryURL:(id)arg1;	// IMP=0x000000010025c359
+ (id)mailLibraryURLFromFocusURL:(id)arg1;	// IMP=0x000000010025bcd2
+ (Class)specialMailboxClass;	// IMP=0x000000010025bcca
@property(copy, nonatomic) NSDictionary *tableOfContents; // @synthesize tableOfContents=_tableOfContents;
@property(copy, nonatomic) NSDictionary *toolbarItems; // @synthesize toolbarItems=_toolbarItems;
@property(readonly, copy, nonatomic) NSDictionary *preferences; // @synthesize preferences=_preferences;
@property(nonatomic) BOOL bindingsAreSet; // @synthesize bindingsAreSet=_bindingsAreSet;
@property(nonatomic) BOOL activated; // @synthesize activated=_activated;
@property(readonly, nonatomic) MTMMailbox *rootMailbox; // @synthesize rootMailbox=_rootMailbox;
@property(nonatomic) __weak StarFieldController *controller; // @synthesize controller=_controller;
@property(nonatomic) __weak MailToolbar *toolbar; // @synthesize toolbar=_toolbar;
- (void).cxx_destruct;	// IMP=0x000000010025f98c
- (void)updateMessageListBindingsWithDisplayedMailbox:(id)arg1 scrollerDelta:(double)arg2;	// IMP=0x000000010025f87e
- (long long)compare:(id)arg1;	// IMP=0x000000010025f710
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010025f5b7
- (void)restore:(id)arg1;	// IMP=0x000000010025f29b
@property(readonly, nonatomic) double fadeDuration;
@property(nonatomic) BOOL showChangedItemsOnly;
@property(readonly, copy, nonatomic) NSArray *restoreMessagePaths;
@property(readonly, copy, nonatomic) NSArray *restoreMailboxPaths;
@property(readonly, nonatomic) BOOL shouldRestoreMailboxPaths;
@property(readonly, copy, nonatomic) NSArray *selectedMessagePaths;
@property(readonly, copy, nonatomic) NSArray *selectedMailboxPaths;
@property(readonly, nonatomic) MTMMailbox *selectedMailbox;
@property(readonly, nonatomic) BOOL mailboxTargeted;
- (void)mailboxListWasUpdated:(id)arg1;	// IMP=0x000000010025f0e3
- (void)mailboxListWillBeUpdated:(id)arg1;	// IMP=0x000000010025f0dd
- (void)updateThumbnailAndGenericThumbnailIfNecessary;	// IMP=0x000000010025f013
@property(readonly, copy, nonatomic) NSAttributedString *placeholderString;
- (void)updateThumbnailAsGenericWindow;	// IMP=0x000000010025ee5c
- (void)updateThumbnail;	// IMP=0x000000010025ec8c
- (id)revisionIDForURL:(id)arg1;	// IMP=0x000000010025e7e9
- (void)adjustDisplayStateAfterTimeMachineStarted;	// IMP=0x000000010025e7e3
@property(copy, nonatomic) NSDictionary *displayState;
- (id)accountForAccountID:(id)arg1;	// IMP=0x000000010025e7b8
- (void)_setupToolbarWithConfigurationDictionary:(id)arg1;	// IMP=0x000000010025e475
- (id)messageWithID:(id)arg1;	// IMP=0x000000010025e37a
- (BOOL)_loadTableOfContentsIfNeeded;	// IMP=0x000000010025e254
@property(readonly, copy, nonatomic) NSArray *mailboxes;
@property(readonly, nonatomic) NSURL *mailLibraryURL;
@property(readonly, nonatomic) NSURL *tocURL;
@property(retain, nonatomic) NSURL *focusURL;
- (void)_updateTimeMachineTargetIfNecessary;	// IMP=0x000000010025ddba
- (void)deactivate;	// IMP=0x000000010025dc21
- (void)activate;	// IMP=0x000000010025dac6
- (BOOL)setupUIWithDisplayState:(id)arg1;	// IMP=0x000000010025da67
@property(readonly, copy) NSString *description;
- (void)dealloc;	// IMP=0x000000010025d8d6
- (void)removeBindings;	// IMP=0x000000010025d6a6
- (void)setupBindings;	// IMP=0x000000010025d5e8
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010025d519
- (id)initWithWindow:(id)arg1;	// IMP=0x000000010025d44a
- (id)initWithFocusURL:(id)arg1 bufferedController:(id)arg2 controller:(id)arg3;	// IMP=0x000000010025d1d3
- (id)initWithFocusURL:(id)arg1 controller:(id)arg2;	// IMP=0x000000010025cf5a
- (id)toolbarAllowedItemIdentifiers:(id)arg1;	// IMP=0x000000010025fd95
- (id)toolbarDefaultItemIdentifiers:(id)arg1;	// IMP=0x000000010025fd3e
- (id)toolbar:(id)arg1 itemForItemIdentifier:(id)arg2 willBeInsertedIntoToolbar:(BOOL)arg3;	// IMP=0x000000010025fa30

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSWindow *window;

@end

