//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOutlineView.h"

@interface NSOutlineView (MailAdditions)
- (id)copyOfItemAndDescendance:(id)arg1;	// IMP=0x0000000100265e8e
- (void)_collectDescendants:(id *)arg1 ofItem:(id)arg2;	// IMP=0x0000000100265cd6
- (BOOL)item:(id)arg1 isDescendantOf:(id)arg2;	// IMP=0x0000000100265c20
@end

