//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSValueTransformer.h"

@interface SignImageValueTransformer : NSValueTransformer
{
}

+ (Class)transformedValueClass;	// IMP=0x000000010018ed43
+ (void)initialize;	// IMP=0x000000010018ecbf
- (id)transformedValue:(id)arg1;	// IMP=0x000000010018ed5c

@end

