//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "MessageTextViewDelegate.h"

@class MCMessage, MessageTextView, NSAttributedString, NSString, NSWindow;

@interface TextMessageDisplay : NSObject <MessageTextViewDelegate>
{
    BOOL _showControlCharacters;	// 8 = 0x8
    MCMessage *_message;	// 16 = 0x10
    NSWindow *_singleWindow;	// 24 = 0x18
    MessageTextView *_textView;	// 32 = 0x20
    NSAttributedString *_rawSourceString;	// 40 = 0x28
}

+ (void)_removeDisplayForMessage:(id)arg1;	// IMP=0x000000010030539e
+ (void)displayRawSourceForMessage:(id)arg1;	// IMP=0x000000010030518d
@property(nonatomic) BOOL showControlCharacters; // @synthesize showControlCharacters=_showControlCharacters;
@property(copy, nonatomic) NSAttributedString *rawSourceString; // @synthesize rawSourceString=_rawSourceString;
@property(nonatomic) MessageTextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) NSWindow *singleWindow; // @synthesize singleWindow=_singleWindow;
@property(retain, nonatomic) MCMessage *message; // @synthesize message=_message;
- (void).cxx_destruct;	// IMP=0x0000000100306245
- (void)saveAs:(id)arg1;	// IMP=0x00000001003060a2
- (void)toggleShowControlCharacters:(id)arg1;	// IMP=0x000000010030605f
- (void)showPrintPanel:(id)arg1;	// IMP=0x0000000100305f41
- (void)setTitle:(id)arg1;	// IMP=0x0000000100305ecf
- (void)windowWillClose:(id)arg1;	// IMP=0x0000000100305e73
- (void)bringToFront;	// IMP=0x0000000100305e27
- (BOOL)validateMenuItem:(id)arg1;	// IMP=0x0000000100305d0c
- (id)messageTextView:(id)arg1 willReturnMenu:(id)arg2 forEvent:(id)arg3;	// IMP=0x0000000100305b36
- (void)_displayRawSource;	// IMP=0x000000010030587d
- (void)_prepareForMessage:(id)arg1;	// IMP=0x000000010030559a
- (void)_beginBackgroundLoad;	// IMP=0x0000000100305501
- (void)dealloc;	// IMP=0x000000010030548b
- (void)awakeFromNib;	// IMP=0x00000001003053be

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

