//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MailCore/MCAuthScheme.h>

@interface MCAppleTokenAuthScheme : MCAuthScheme
{
}

+ (id)appleTokenAuthScheme;	// IMP=0x000000000000c9f7
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x000000000000c93d
- (id)supportedSaslMechanisms;	// IMP=0x000000000000cc2e
- (BOOL)requiresPassword;	// IMP=0x000000000000cc26
- (BOOL)requiresUsername;	// IMP=0x000000000000cc1e
- (unsigned int)applescriptScheme;	// IMP=0x000000000000cc13
- (id)humanReadableName;	// IMP=0x000000000000cba7
- (id)name;	// IMP=0x000000000000cb93
- (void)dealloc;	// IMP=0x000000000000cac2

@end

