//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MailCore/MCProgressEntry.h>

@class NSArray;

@interface MCConnectingProgressEntry : MCProgressEntry
{
    NSArray *_connectingAccountNames;	// 8 = 0x8
}

+ (id)keyPathsForValuesAffectingStatusText;	// IMP=0x0000000000018da0
@property(copy, nonatomic) NSArray *connectingAccountNames; // @synthesize connectingAccountNames=_connectingAccountNames;
- (void).cxx_destruct;	// IMP=0x0000000000018e5f
- (BOOL)indeterminate;	// IMP=0x0000000000018e30
- (id)statusText;	// IMP=0x0000000000018dc0
- (id)progressSlice;	// IMP=0x0000000000018d82
- (id)progressName;	// IMP=0x0000000000018ce0
- (void)refreshValues;	// IMP=0x000000000001885a
- (id)observedProgressKeypaths;	// IMP=0x00000000000187b2

@end

