//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@interface MCDateClassifier : NSObject
{
}

+ (BOOL)isYesterday:(id)arg1;	// IMP=0x00000000000243f4
+ (BOOL)isToday:(id)arg1;	// IMP=0x00000000000243bf
+ (void)_resetDates;	// IMP=0x000000000002428a
+ (void)_dateInvalidated:(id)arg1;	// IMP=0x0000000000024278
+ (void)initialize;	// IMP=0x00000000000241be

@end

