//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "MCAttachmentDataSource-Protocol.h"
//#import "NSURLSessionDownloadDelegate.h"

@class NSDate, NSError, NSNumber, NSPort, NSProgress, NSString, NSURL;

@interface MCRemoteURLAttachmentDataSource : NSObject <NSURLSessionDownloadDelegate, MCAttachmentDataSource>
{
    BOOL _isAutoArchiveAttachment;	// 8 = 0x8
    BOOL _isMailDropIndividualImage;	// 9 = 0x9
    BOOL _isMailDropImageArchive;	// 10 = 0xa
    NSURL *_remoteURL;	// 16 = 0x10
    NSPort *_downloadPort;	// 24 = 0x18
    NSProgress *_downloadProgress;	// 32 = 0x20
    NSError *_downloadError;	// 40 = 0x28
    NSURL *_attachmentsDirectory;	// 48 = 0x30
    NSNumber *_fileSize;	// 56 = 0x38
    NSString *_preferredFilename;	// 64 = 0x40
    NSString *_filename;	// 72 = 0x48
    NSDate *_downloadURLExpiration;	// 80 = 0x50
    CDUnknownBlockType _fileWrapperCompletionBlock;	// 88 = 0x58
}

@property(copy, nonatomic) CDUnknownBlockType fileWrapperCompletionBlock; // @synthesize fileWrapperCompletionBlock=_fileWrapperCompletionBlock;
@property(readonly, nonatomic) BOOL isMailDropImageArchive; // @synthesize isMailDropImageArchive=_isMailDropImageArchive;
@property(readonly, nonatomic) BOOL isMailDropIndividualImage; // @synthesize isMailDropIndividualImage=_isMailDropIndividualImage;
@property(readonly, nonatomic) BOOL isAutoArchiveAttachment; // @synthesize isAutoArchiveAttachment=_isAutoArchiveAttachment;
@property(readonly, nonatomic) NSDate *downloadURLExpiration; // @synthesize downloadURLExpiration=_downloadURLExpiration;
@property(readonly, copy, nonatomic) NSString *filename; // @synthesize filename=_filename;
@property(readonly, copy, nonatomic) NSString *preferredFilename; // @synthesize preferredFilename=_preferredFilename;
@property(readonly, nonatomic) NSNumber *fileSize; // @synthesize fileSize=_fileSize;
@property(readonly, nonatomic) NSURL *attachmentsDirectory; // @synthesize attachmentsDirectory=_attachmentsDirectory;
@property(retain, nonatomic) NSError *downloadError; // @synthesize downloadError=_downloadError;
@property(retain, nonatomic) NSProgress *downloadProgress; // @synthesize downloadProgress=_downloadProgress;
@property(readonly, nonatomic) NSPort *downloadPort; // @synthesize downloadPort=_downloadPort;
@property(retain, nonatomic) NSURL *remoteURL; // @synthesize remoteURL=_remoteURL;
//- (void).cxx_destruct;	// IMP=0x00000000000919ff
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;	// IMP=0x000000000009171e
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didWriteData:(long long)arg3 totalBytesWritten:(long long)arg4 totalBytesExpectedToWrite:(long long)arg5;	// IMP=0x00000000000916bf
- (void)_persistDownloadedFileWrapper:(id)arg1 originalContentsURL:(id)arg2;	// IMP=0x00000000000913d7
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didFinishDownloadingToURL:(id)arg3;	// IMP=0x0000000000091121
- (void)_downloadRemoteAttachment;	// IMP=0x0000000000090e45
- (BOOL)_isExpired;	// IMP=0x0000000000090dee
@property(readonly, nonatomic) BOOL isDirectory;
@property(readonly, nonatomic) BOOL canResultsBeCached;
@property(readonly, nonatomic) BOOL dataIsLocallyAvailable;
- (id)approximateSizeForAccessLevel:(long long)arg1;	// IMP=0x0000000000090db7
- (void)fileWrapperForAccessLevel:(long long)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000000090b11
- (void)dataForAccessLevel:(long long)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000000090974
@property(readonly, copy) NSString *debugDescription;
- (id)_remoteDownloadQueue;	// IMP=0x00000000000907b3
- (void)dealloc;	// IMP=0x0000000000090769
- (id)init;	// IMP=0x000000000009069a
- (id)initWithAttachment:(id)arg1 attachmentsDirectory:(id)arg2;	// IMP=0x00000000000903c4
- (id)initWithRemoteURL:(id)arg1;	// IMP=0x0000000000090322

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

