//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IMAP/IMAPResponse.h>

@class NSArray;

@interface IMAPCapabilityResponse : IMAPResponse
{
    NSArray *_capabilities;	// 8 = 0x8
}

+ (BOOL)handlesResponseWithName:(const char *)arg1 ofLength:(unsigned long long)arg2;	// IMP=0x000000000000daf6
@property(copy, nonatomic) NSArray *capabilities; // @synthesize capabilities=_capabilities;
- (void).cxx_destruct;	// IMP=0x000000000000dc22
- (id)description;	// IMP=0x000000000000db25

@end

