//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IMAP/IMAPTask.h>

#import "IMAPFetchMailboxStatusOperationDelegate.h"
#import "IMAPPersistDeletedMessagesOperationDelegate.h"
#import "IMAPPersistFlagChangesOperationDelegate.h"
#import "IMAPPersistLabelsOperationDelegate.h"
#import "IMAPPersistMessagesOperationDelegate.h"
#import "IMAPSelectMailboxOperationDelegate.h"
#import "IMAPSyncSkeletonsOperationDelegate.h"
#import "IMAPSyncUIDsFlagsAndLabelsOperationDelegate.h"
#import "IMAPVerifyMailboxOperationDelegate.h"

@class IMAPTaskManager, NSMutableArray, NSMutableDictionary, NSMutableIndexSet, NSMutableOrderedSet, NSProgress, NSString;

@interface IMAPMailboxSyncTask : IMAPTask <IMAPFetchMailboxStatusOperationDelegate, IMAPPersistDeletedMessagesOperationDelegate, IMAPPersistFlagChangesOperationDelegate, IMAPPersistLabelsOperationDelegate, IMAPPersistMessagesOperationDelegate, IMAPSelectMailboxOperationDelegate, IMAPSyncSkeletonsOperationDelegate, IMAPSyncUIDsFlagsAndLabelsOperationDelegate, IMAPVerifyMailboxOperationDelegate>
{
    NSMutableIndexSet *_messageNumbersNeedingUIDs;	// 8 = 0x8
    NSMutableIndexSet *_messageNumbersNeedingSkeletons;	// 16 = 0x10
    NSMutableIndexSet *_uidsNeedingSkeletons;	// 24 = 0x18
    NSMutableOrderedSet *_messagesToPersist;	// 32 = 0x20
    NSMutableIndexSet *_uidsToDelete;	// 40 = 0x28
    NSMutableDictionary *_flagChangesByDetails;	// 48 = 0x30
    NSMutableDictionary *_labelsToPersist;	// 56 = 0x38
    NSMutableArray *_messagesNeedingUIDs;	// 64 = 0x40
    NSMutableIndexSet *_uidsAddedLocally;	// 72 = 0x48
    BOOL _userInitiated;	// 80 = 0x50
    BOOL _shouldVerifyLocalCount;	// 81 = 0x51
    BOOL _isGmail;	// 82 = 0x52
    BOOL _dataSourceIsInboxOrAllMail;	// 83 = 0x53
    BOOL _hasUnseen;	// 84 = 0x54
    BOOL _networkPriorityNeedsRecalculation;	// 85 = 0x55
    BOOL _persistencePriorityNeedsRecalculation;	// 86 = 0x56
    BOOL _wasReset;	// 87 = 0x57
    BOOL _needsUpdate;	// 88 = 0x58
    BOOL _isEnding;	// 89 = 0x59
    BOOL _foundNewUnreadInboxMessage;	// 90 = 0x5a
    unsigned int _localHighestUIDToCheck;	// 92 = 0x5c
    unsigned int _uidNext;	// 96 = 0x60
    unsigned int _lastSyncedUIDNext;	// 100 = 0x64
    unsigned int _newUIDValidity;	// 104 = 0x68
    IMAPTaskManager *_taskManager;	// 112 = 0x70
    id <IMAPMessageDataSource> _dataSource;	// 120 = 0x78
    unsigned long long _serverModificationSequence;	// 128 = 0x80
    unsigned long long _lastSyncedModificationSequence;	// 136 = 0x88
    unsigned long long _exists;	// 144 = 0x90
    NSProgress *_checkProgress;	// 152 = 0x98
    long long _verificationState;	// 160 = 0xa0
}

@property(nonatomic) long long verificationState; // @synthesize verificationState=_verificationState;
@property(nonatomic) BOOL foundNewUnreadInboxMessage; // @synthesize foundNewUnreadInboxMessage=_foundNewUnreadInboxMessage;
@property(readonly, nonatomic) NSProgress *checkProgress; // @synthesize checkProgress=_checkProgress;
@property(nonatomic) BOOL isEnding; // @synthesize isEnding=_isEnding;
@property(nonatomic) BOOL needsUpdate; // @synthesize needsUpdate=_needsUpdate;
@property(nonatomic) BOOL wasReset; // @synthesize wasReset=_wasReset;
@property(nonatomic) BOOL persistencePriorityNeedsRecalculation; // @synthesize persistencePriorityNeedsRecalculation=_persistencePriorityNeedsRecalculation;
@property(nonatomic) BOOL networkPriorityNeedsRecalculation; // @synthesize networkPriorityNeedsRecalculation=_networkPriorityNeedsRecalculation;
@property(nonatomic) BOOL hasUnseen; // @synthesize hasUnseen=_hasUnseen;
@property(readonly, nonatomic) BOOL dataSourceIsInboxOrAllMail; // @synthesize dataSourceIsInboxOrAllMail=_dataSourceIsInboxOrAllMail;
@property(readonly, nonatomic) BOOL isGmail; // @synthesize isGmail=_isGmail;
@property(nonatomic) unsigned int newUIDValidity; // @synthesize newUIDValidity=_newUIDValidity;
@property(nonatomic) unsigned int lastSyncedUIDNext; // @synthesize lastSyncedUIDNext=_lastSyncedUIDNext;
@property(nonatomic) unsigned int uidNext; // @synthesize uidNext=_uidNext;
@property(nonatomic) unsigned long long exists; // @synthesize exists=_exists;
@property unsigned int localHighestUIDToCheck; // @synthesize localHighestUIDToCheck=_localHighestUIDToCheck;
@property(nonatomic) BOOL shouldVerifyLocalCount; // @synthesize shouldVerifyLocalCount=_shouldVerifyLocalCount;
@property(nonatomic) unsigned long long lastSyncedModificationSequence; // @synthesize lastSyncedModificationSequence=_lastSyncedModificationSequence;
@property(nonatomic) unsigned long long serverModificationSequence; // @synthesize serverModificationSequence=_serverModificationSequence;
@property(readonly, nonatomic) id <IMAPMessageDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(readonly) IMAPTaskManager *taskManager; // @synthesize taskManager=_taskManager;
- (void).cxx_destruct;	// IMP=0x0000000000040507
- (void)verifyMailboxOperation:(id)arg1 foundInconsistencies:(BOOL)arg2;	// IMP=0x000000000003ff9d
- (void)_finishCheckForMailProgressIfNecessary;	// IMP=0x000000000003ff17
- (void)_setFoundNewUnreadMessageInInbox;	// IMP=0x000000000003fe97
- (void)_incrementFoundMessages:(unsigned long long)arg1;	// IMP=0x000000000003fdb1
- (void)persistDeletedMessagesOperation:(id)arg1 deletedUIDs:(id)arg2;	// IMP=0x000000000003fa9c
- (void)persistLabelsOperation:(id)arg1 persistedLabelsForPersistentIDs:(id)arg2;	// IMP=0x000000000003f78c
- (void)persistFlagChangesOperation:(id)arg1 persistedFlagChangesForUIDs:(id)arg2;	// IMP=0x000000000003f473
- (void)persistMessagesOperation:(id)arg1 persistedMessagesAndGotNewMessages:(id)arg2 missedMessages:(id)arg3;	// IMP=0x000000000003ec86
- (id)_gmailLabelsForNames:(id)arg1;	// IMP=0x000000000003ea22
- (void)_updateLastSyncedModificationSequenceIfNeeded;	// IMP=0x000000000003e9a9
- (void)syncSkeletonsOperationFinished:(id)arg1 withFetchResponses:(id)arg2 serverInterface:(id)arg3;	// IMP=0x000000000003ca31
- (void)syncUIDsOperationFinished:(id)arg1 withFetchResponses:(id)arg2 vanishedUIDs:(id)arg3;	// IMP=0x000000000003b662
- (void)fetchMailboxStatusOperation:(id)arg1 fetchedStatusesForMailboxNames:(id)arg2;	// IMP=0x000000000003b390
- (void)_updateWithIMAPMailboxFromSelectForMailboxName:(id)arg1;	// IMP=0x000000000003b280
- (void)selectMailboxOperation:(id)arg1 selectedMailbox:(id)arg2;	// IMP=0x000000000003b12f
- (void)end;	// IMP=0x000000000003af01
- (void)operationFinished:(id)arg1;	// IMP=0x000000000003a9dd
- (void)recalculatePriorities;	// IMP=0x000000000003a0cb
- (long long)_nextPersistencePriorityAndOperation:(id *)arg1;	// IMP=0x0000000000039c2d
- (id)nextPersistenceOperation;	// IMP=0x0000000000039776
- (void)_checkForOfflineExpungesIfNeeded;	// IMP=0x00000000000394a2
- (id)_batchedUIDsNeedingSkeletonsOfSize:(unsigned long long)arg1;	// IMP=0x00000000000391a7
- (long long)_nextNetworkPriorityAndOperation:(id *)arg1 reservedNetworkPriority:(long long *)arg2;	// IMP=0x00000000000382ff
- (id)nextNetworkOperation;	// IMP=0x0000000000037e1c
- (void)cancel;	// IMP=0x0000000000037c52
- (void)didAddMessagesWithUnknownUID:(id)arg1;	// IMP=0x0000000000037c35
- (void)newUIDsAddedLocally:(id)arg1;	// IMP=0x0000000000037b50
- (void)reset;	// IMP=0x0000000000037a65
- (void)_updateStateForFullSyncRecalculatingPrioritiesIfNecessary:(BOOL)arg1;	// IMP=0x0000000000037958
- (void)syncUIDsIgnoringModificationSequence;	// IMP=0x0000000000037923
- (void)fetchFlagsForMessageNumbers:(id)arg1;	// IMP=0x00000000000375e5
- (BOOL)_uidIsBeingPersisted:(unsigned int)arg1 inRange:(struct _NSRange)arg2;	// IMP=0x0000000000037517
- (BOOL)uidIsBeingPersisted:(unsigned int)arg1;	// IMP=0x00000000000374ca
- (BOOL)handleVanishedMessageWithUID:(unsigned int)arg1 range:(struct _NSRange)arg2;	// IMP=0x00000000000371b3
- (BOOL)handleExpungedMessageWithMessageNumber:(unsigned long long)arg1 uid:(unsigned int)arg2;	// IMP=0x0000000000037080
- (void)updateWithExists:(unsigned long long)arg1;	// IMP=0x0000000000036b6d
- (BOOL)_checkForWorkWithIMAPMailbox:(id)arg1 canTrustExists:(BOOL)arg2 canTrustUnseen:(BOOL)arg3 allowUpdate:(BOOL)arg4 forceUpdate:(BOOL)arg5;	// IMP=0x00000000000359a8
@property(nonatomic) BOOL userInitiated;
- (id)initWithMailboxName:(id)arg1;	// IMP=0x0000000000035828
- (void)_imapMailboxSyncTaskCommonInitWithDataSource:(id)arg1 taskManager:(id)arg2;	// IMP=0x000000000003547a
- (id)initWithDataSource:(id)arg1 taskManager:(id)arg2 exists:(unsigned long long)arg3;	// IMP=0x000000000003512f
- (id)initWithDataSource:(id)arg1 taskManager:(id)arg2 messageNumbersNeedingFlags:(id)arg3;	// IMP=0x0000000000034e22
- (id)initWithDataSource:(id)arg1 taskManager:(id)arg2 imapMailbox:(id)arg3 fromStatus:(BOOL)arg4 forceFullSync:(BOOL)arg5;	// IMP=0x00000000000349b7

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

