//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IMAP/IMAPResponse.h>

@class NSString;

@interface IMAPListResponse : IMAPResponse
{
    unsigned long long _mailboxAttributes;	// 8 = 0x8
    NSString *_separator;	// 16 = 0x10
    NSString *_mailboxName;	// 24 = 0x18
}

+ (BOOL)handlesResponseWithName:(const char *)arg1 ofLength:(unsigned long long)arg2;	// IMP=0x000000000002f794
@property(copy, nonatomic) NSString *mailboxName; // @synthesize mailboxName=_mailboxName;
@property(copy, nonatomic) NSString *separator; // @synthesize separator=_separator;
@property(nonatomic) unsigned long long mailboxAttributes; // @synthesize mailboxAttributes=_mailboxAttributes;
- (void).cxx_destruct;	// IMP=0x000000000002fc60
- (unsigned long long)mailboxAttributesFromSet:(id)arg1;	// IMP=0x000000000002f9f7
- (id)_newStringForMailboxAttributes;	// IMP=0x000000000002f918
- (id)description;	// IMP=0x000000000002f7d0
- (const char *)_responseName;	// IMP=0x000000000002f7c3

@end

