//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IMAP/IMAPTask.h>

@interface IMAPPersistenceTask : IMAPTask
{
    id <IMAPMessageDataSource> _dataSource;	// 8 = 0x8
}

@property(readonly, nonatomic) id <IMAPMessageDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;	// IMP=0x0000000000053834
- (long long)networkPriority;	// IMP=0x000000000005381b
- (id)nextNetworkOperation;	// IMP=0x0000000000053813
- (id)description;	// IMP=0x000000000005374c
- (id)initWithMailboxName:(id)arg1;	// IMP=0x000000000005367d
- (id)initWithDataSource:(id)arg1;	// IMP=0x00000000000535e3

@end

