//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IMAP/IMAPFetchCommand.h>

@interface IMAPFetchUIDCommand : IMAPFetchCommand
{
}

- (BOOL)shouldSendAgainOnError;	// IMP=0x0000000000028c05
- (id)commandTypeString;	// IMP=0x0000000000028be6
- (BOOL)_isLegalRange:(CDStruct_f792af56)arg1;	// IMP=0x0000000000028bb8

@end

