//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IMAP/IMAPSingleCommand.h>

@class NSString;

@interface IMAPGetQuotaCommand : IMAPSingleCommand
{
    NSString *_quotaRoot;	// 8 = 0x8
}

@property(readonly, copy, nonatomic) NSString *quotaRoot; // @synthesize quotaRoot=_quotaRoot;
- (void).cxx_destruct;	// IMP=0x0000000000057b24
- (long long)maxAllowedConnectionState;	// IMP=0x0000000000057b06
- (long long)minRequiredConnectionState;	// IMP=0x0000000000057afb
- (id)newCommandDataForLiteralPlus:(BOOL)arg1;	// IMP=0x0000000000057a09
- (BOOL)shouldSendAgainOnError;	// IMP=0x00000000000579fe
- (id)activityString;	// IMP=0x0000000000057992
- (id)commandTypeString;	// IMP=0x0000000000057973
- (id)init;	// IMP=0x000000000005795f
- (id)initWithQuotaRoot:(id)arg1;	// IMP=0x0000000000057892

@end

