//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IMAP/IMAPUnselectCommand.h>

@interface IMAPCloseCommand : IMAPUnselectCommand
{
}

- (id)activityString;	// IMP=0x000000000000fd3a
- (id)commandTypeString;	// IMP=0x000000000000fd1b

@end

