//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IMAP/IMAPSingleCommand.h>

@interface IMAPExpungeCommand : IMAPSingleCommand
{
}

- (long long)maxAllowedConnectionState;	// IMP=0x000000000000fc54
- (long long)minRequiredConnectionState;	// IMP=0x000000000000fc49
- (BOOL)shouldSendAgainOnError;	// IMP=0x000000000000fc3e
- (id)activityString;	// IMP=0x000000000000fbd2
- (id)commandTypeString;	// IMP=0x000000000000fbb3

@end

