//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IMAP/IMAPResponse.h>

@class NSIndexSet;

@interface IMAPVanishedResponse : IMAPResponse
{
    BOOL _earlier;	// 8 = 0x8
    NSIndexSet *_uids;	// 16 = 0x10
}

+ (BOOL)handlesResponseWithName:(const char *)arg1 ofLength:(unsigned long long)arg2;	// IMP=0x000000000007242b
@property(copy, nonatomic) NSIndexSet *uids; // @synthesize uids=_uids;
@property(nonatomic) BOOL earlier; // @synthesize earlier=_earlier;
- (void).cxx_destruct;	// IMP=0x00000000000725fc
- (id)description;	// IMP=0x000000000007245a

@end

