//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject-Protocol.h"

@class IMAPGetMessageDetailsOperation, NSArray, NSIndexSet;

@protocol IMAPGetMessageDetailsOperationDelegate <NSObject>
- (void)getMessageDetailsOperation:(IMAPGetMessageDetailsOperation *)arg1 gotDetails:(NSArray *)arg2 uidsNotFound:(NSIndexSet *)arg3;
@end

