//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Mail/MFMessageSortingValue.h>

@class NSString;

@interface _MFMessageSortingValueSubject : MFMessageSortingValue
{
    unsigned char _subjectPrefixLength;	// 8 = 0x8
    NSString *_subject;	// 16 = 0x10
}

@property(nonatomic) unsigned char subjectPrefixLength; // @synthesize subjectPrefixLength=_subjectPrefixLength;
@property(copy, nonatomic) NSString *subject; // @synthesize subject=_subject;
- (id)description;	// IMP=0x00000000001e1c6b
- (void)dealloc;	// IMP=0x00000000001e1c21

@end

