//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class NSString;

@interface _MFRedundantTextIdentifierAttachmentContext : NSObject
{
    BOOL _attachmentIsDownloaded;	// 8 = 0x8
    NSString *_attachmentName;	// 16 = 0x10
    NSString *_attachmentExtension;	// 24 = 0x18
    unsigned long long _attachmentSize;	// 32 = 0x20
}

@property(readonly, nonatomic) BOOL attachmentIsDownloaded; // @synthesize attachmentIsDownloaded=_attachmentIsDownloaded;
@property(readonly, nonatomic) unsigned long long attachmentSize; // @synthesize attachmentSize=_attachmentSize;
@property(readonly, copy, nonatomic) NSString *attachmentExtension; // @synthesize attachmentExtension=_attachmentExtension;
@property(readonly, copy, nonatomic) NSString *attachmentName; // @synthesize attachmentName=_attachmentName;
- (void).cxx_destruct;	// IMP=0x00000000002327d6
- (BOOL)isEqualTo:(id)arg1;	// IMP=0x00000000002325a6
- (id)description;	// IMP=0x00000000002324be
- (id)init;	// IMP=0x00000000002323ef
- (id)initWithAttachmentName:(id)arg1 attachmentSize:(unsigned long long)arg2 attachmentIsDownloaded:(BOOL)arg3;	// IMP=0x0000000000232108

@end

