//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EWSPathToExtendedFieldType.h"

@interface EWSPathToExtendedFieldType (MessageAdditions)
+ (id)newExtendedFieldTypeForPropertyId:(long long)arg1;	// IMP=0x00000000000b096c
+ (id)newExtendedFieldTypeForPropertyTag:(id)arg1;	// IMP=0x00000000000b070f
+ (id)_newExtendedFieldTypeForPropertyTag:(id)arg1 propertyType:(long long)arg2;	// IMP=0x00000000000b069a
@end

