//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MCFileWrapper.h"

@interface MCFileWrapper (MailAdditions)
- (void)setPreferredFilename:(id)arg1;	// IMP=0x0000000000003a00
- (BOOL)writeToURL:(id)arg1 options:(unsigned long long)arg2 originalContentsURL:(id)arg3 error:(id *)arg4;	// IMP=0x0000000000003815
- (id)sharedKeySetForQuarantineProperties;	// IMP=0x00000000000036f1
- (void)configureWithMessage:(id)arg1 headers:(id)arg2;	// IMP=0x0000000000002a6b
@property(nonatomic) long long attachmentMailboxType;
@end

