//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Mail/MFEWSLocalMessageAction.h>

@class NSArray;

@interface MFEWSFlagChangeMessageAction : MFEWSLocalMessageAction
{
    NSArray *_messages;	// 8 = 0x8
    long long _flags;	// 16 = 0x10
    long long _mask;	// 24 = 0x18
}

@property(readonly, nonatomic) long long mask; // @synthesize mask=_mask;
@property(readonly, nonatomic) long long flags; // @synthesize flags=_flags;
@property(readonly, copy, nonatomic) NSArray *messages; // @synthesize messages=_messages;
- (void).cxx_destruct;	// IMP=0x0000000000089a27
- (id)newSyncOperation;	// IMP=0x00000000000899ba
- (id)initWithMessageActionID:(long long)arg1 activityType:(id)arg2 mailbox:(id)arg3 userInitiated:(BOOL)arg4;	// IMP=0x00000000000898eb
- (id)initWithMessageActionID:(long long)arg1 activityType:(id)arg2 mailbox:(id)arg3 userInitiated:(BOOL)arg4 messages:(id)arg5 flags:(long long)arg6 mask:(long long)arg7;	// IMP=0x00000000000897fe

@end

