//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MCTaskHandlerOperation.h"

@class NSArray;

@interface MFEWSRetrievePersistedFolderDataOperation : MCTaskHandlerOperation
{
    id <MFEWSRetrievePersistedFolderDataDelegate> _delegate;	// 24 = 0x18
    NSArray *_mailboxURLs;	// 32 = 0x20
}

@property(readonly, copy, nonatomic) NSArray *mailboxURLs; // @synthesize mailboxURLs=_mailboxURLs;
@property(nonatomic) __weak id <MFEWSRetrievePersistedFolderDataDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x00000000000b6d9d
- (void)main;	// IMP=0x00000000000b6a44
- (id)init;	// IMP=0x00000000000b6975
- (id)initWithMailboxURLs:(id)arg1;	// IMP=0x00000000000b68fa

@end

