//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Mail/MFEWSNetworkTaskOperation.h>

@class NSString;

@interface MFEWSMailboxReconcileTaskOperation : MFEWSNetworkTaskOperation
{
    id <MFEWSMailboxReconcileTaskOperationDelegate> _delegate;	// 24 = 0x18
    NSString *_folderIDString;	// 32 = 0x20
    NSString *_currentSyncState;	// 40 = 0x28
}

+ (long long)_maxChangesReturned;	// IMP=0x00000000000a25a4
+ (id)_newRequestWithFolderID:(id)arg1 syncState:(id)arg2;	// IMP=0x00000000000a244d
+ (id)log;	// IMP=0x00000000000a0ec1
@property(copy, nonatomic) NSString *currentSyncState; // @synthesize currentSyncState=_currentSyncState;
@property(readonly, copy, nonatomic) NSString *folderIDString; // @synthesize folderIDString=_folderIDString;
@property(nonatomic) __weak id <MFEWSMailboxReconcileTaskOperationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x00000000000a276b
- (Class)_supportedClassForItem:(id)arg1;	// IMP=0x00000000000a2640
- (void)main;	// IMP=0x00000000000a10b7
- (id)init;	// IMP=0x00000000000a0fe8
- (id)initWithFolderIDString:(id)arg1 initialSyncState:(id)arg2;	// IMP=0x00000000000a0f20

@end

