//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MCTask.h"

#import "MFEWSFetchMessageMetadataOperationDelegate.h"
#import "MFEWSMailboxReconcileTaskOperationDelegate.h"
#import "MFEWSPersistMessageMetadataOperationDelegate.h"

@class MFEWSDeleteMailboxTaskOperation, MFEWSMailboxReconcileTaskOperation, MFEWSPersistMessageMetadataOperation, NSMutableArray, NSMutableDictionary, NSMutableSet, NSProgress, NSString;

@interface MFEWSMailboxSyncTask : MCTask <MFEWSMailboxReconcileTaskOperationDelegate, MFEWSFetchMessageMetadataOperationDelegate, MFEWSPersistMessageMetadataOperationDelegate>
{
    MFEWSMailboxReconcileTaskOperation *_reconcileOperation;	// 8 = 0x8
    MFEWSPersistMessageMetadataOperation *_persistMetadataOperation;	// 16 = 0x10
    NSMutableArray *_batchesNeedingFetch;	// 24 = 0x18
    NSMutableSet *_currentFetchOperations;	// 32 = 0x20
    NSMutableDictionary *_batchesToPersistByInitialSyncState;	// 40 = 0x28
    BOOL _userInitiated;	// 48 = 0x30
    BOOL _needsDelete;	// 49 = 0x31
    BOOL _isPrimaryMailbox;	// 50 = 0x32
    BOOL _foundNewUnreadInboxMessage;	// 51 = 0x33
    NSString *_folderIDString;	// 56 = 0x38
    NSString *_mailboxURL;	// 64 = 0x40
    id <MFEWSMailboxDataCache> _mailboxDataCache;	// 72 = 0x48
    NSString *_syncStateToReconcile;	// 80 = 0x50
    NSString *_syncStateToPersist;	// 88 = 0x58
    MFEWSDeleteMailboxTaskOperation *_deleteMailboxOperation;	// 96 = 0x60
    NSProgress *_checkProgress;	// 104 = 0x68
}

@property(nonatomic) BOOL foundNewUnreadInboxMessage; // @synthesize foundNewUnreadInboxMessage=_foundNewUnreadInboxMessage;
@property(nonatomic) BOOL isPrimaryMailbox; // @synthesize isPrimaryMailbox=_isPrimaryMailbox;
@property(nonatomic) BOOL needsDelete; // @synthesize needsDelete=_needsDelete;
@property(readonly, nonatomic) NSProgress *checkProgress; // @synthesize checkProgress=_checkProgress;
@property(retain, nonatomic) MFEWSDeleteMailboxTaskOperation *deleteMailboxOperation; // @synthesize deleteMailboxOperation=_deleteMailboxOperation;
@property(copy, nonatomic) NSString *syncStateToPersist; // @synthesize syncStateToPersist=_syncStateToPersist;
@property(copy, nonatomic) NSString *syncStateToReconcile; // @synthesize syncStateToReconcile=_syncStateToReconcile;
@property(nonatomic) __weak id <MFEWSMailboxDataCache> mailboxDataCache; // @synthesize mailboxDataCache=_mailboxDataCache;
@property(readonly, copy, nonatomic) NSString *mailboxURL; // @synthesize mailboxURL=_mailboxURL;
@property(copy, nonatomic) NSString *folderIDString; // @synthesize folderIDString=_folderIDString;
- (void).cxx_destruct;	// IMP=0x00000000000a4f8c
- (void)_finishCheckingForMailProgress;	// IMP=0x00000000000a4ded
- (void)_setFoundNewUnreadMessageInInbox;	// IMP=0x00000000000a4d6d
- (void)_incrementFoundMessages:(unsigned long long)arg1;	// IMP=0x00000000000a4c25
- (void)persistMessageMetadataOperation:(id)arg1 didPersistBatch:(id)arg2;	// IMP=0x00000000000a440e
- (void)fetchMessageMetadataOperation:(id)arg1 didPopulateBatch:(id)arg2;	// IMP=0x00000000000a3fc4
- (void)mailboxReconcileTaskOperationFolderIsInvalid:(id)arg1;	// IMP=0x00000000000a3dd5
- (void)mailboxReconcileTaskOperation:(id)arg1 receivedBatch:(id)arg2;	// IMP=0x00000000000a37e0
- (void)end;	// IMP=0x00000000000a37a1
- (void)recalculatePriorities;	// IMP=0x00000000000a359a
- (id)nextPersistenceOperation;	// IMP=0x00000000000a33a9
- (id)nextNetworkOperation;	// IMP=0x00000000000a31e7
- (void)operationFinished:(id)arg1;	// IMP=0x00000000000a2fc8
- (void)_removeFetchOperation:(id)arg1;	// IMP=0x00000000000a2e23
- (void)_addFetchOperation:(id)arg1;	// IMP=0x00000000000a2ce5
@property(nonatomic) BOOL userInitiated;
@property(retain, nonatomic) MFEWSPersistMessageMetadataOperation *persistMetadataOperation;
@property(retain, nonatomic) MFEWSMailboxReconcileTaskOperation *reconcileOperation;
- (void)reconcileMailboxWithSyncState:(id)arg1;	// IMP=0x00000000000a2a95
- (id)init;	// IMP=0x00000000000a29c6
- (id)initWithMailboxURL:(id)arg1;	// IMP=0x00000000000a27ab

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

