//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Mail/MFEWSResponseOperation.h>

@class EWSGetItemResponseType, NSArray, NSMutableArray;

@interface MFEWSGetItemsResponseOperation : MFEWSResponseOperation
{
    NSMutableArray *_EWSItems;	// 24 = 0x18
    NSArray *_EWSItemIdsRequested;	// 32 = 0x20
}

@property(retain) NSArray *EWSItemIdsRequested; // @synthesize EWSItemIdsRequested=_EWSItemIdsRequested;
@property(retain) NSMutableArray *EWSItems; // @synthesize EWSItems=_EWSItems;
- (void).cxx_destruct;	// IMP=0x0000000000096853
- (void)executeOperation;	// IMP=0x000000000009631d
- (void)prepareToExecuteWithResponse:(id)arg1 forRequestOperation:(id)arg2;	// IMP=0x00000000000960a8
@property(retain) EWSGetItemResponseType *response;

@end

