//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Mail/MFEWSRequestOperation.h>

#import "NSCoding.h"

@class NSString;

@interface MFEWSDeleteFolderRequestOperation : MFEWSRequestOperation <NSCoding>
{
    NSString *_folderIdString;	// 24 = 0x18
}

@property(readonly, copy, nonatomic) NSString *folderIdString; // @synthesize folderIdString=_folderIdString;
- (void).cxx_destruct;	// IMP=0x0000000000081696
- (void)setupOfflineResponse;	// IMP=0x0000000000081611
- (id)prepareRequest;	// IMP=0x00000000000814be
- (BOOL)isFolderRequest;	// IMP=0x00000000000814b3
- (id)activityString;	// IMP=0x0000000000081446
- (id)initWithGateway:(id)arg1 errorHandler:(id)arg2;	// IMP=0x0000000000081377
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000000000812da
- (id)initWithCoder:(id)arg1;	// IMP=0x00000000000810dc
- (void)_ewsDeleteFolderRequestOperationCommonInitWithEWSFolderIdString:(id)arg1;	// IMP=0x00000000000810a8
- (id)initWithEWSFolderIdString:(id)arg1 gateway:(id)arg2;	// IMP=0x0000000000080f04

@end

