//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Mail/MFLibraryUpgradeStep.h>

@interface MFForeignKeyUpgradeStep : MFLibraryUpgradeStep
{
}

+ (unsigned long long)targetVersion;	// IMP=0x00000000000c5792
- (void)_addForeignKeysForTable:(id)arg1 createSQL:(const char *)arg2 insertSQL:(const char *)arg3;	// IMP=0x00000000000c5958
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x00000000000c579d

@end

