//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

//#import "NSCopying.h"

@class MFMailbox, NSArray, NSColor, NSDictionary, NSMutableArray, NSString;

@interface MFMessageRule : NSObject <NSCopying>
{
    MFMailbox *_copyDestinationMailbox;	// 8 = 0x8
    NSString *_copyDestinationMailboxURL;	// 16 = 0x10
    MFMailbox *_destinationMailbox;	// 24 = 0x18
    NSString *_destinationMailboxURL;	// 32 = 0x20
    NSColor *_color;	// 40 = 0x28
    NSString *_playSound;	// 48 = 0x30
    NSString *_appleScriptPath;	// 56 = 0x38
    NSArray *_recipients;	// 64 = 0x40
    NSString *_responseMessage;	// 72 = 0x48
    int _autoResponseType;	// 80 = 0x50
    NSString *_ruleName;	// 88 = 0x58
    NSMutableArray *_criteria;	// 96 = 0x60
    long long _flags;	// 104 = 0x68
    unsigned int _isActive:1;	// 112 = 0x70
    unsigned int _ruleWasAutoDeactivated:1;	// 112 = 0x70
    unsigned int _allCriteriaMustBeSatisfied:1;	// 112 = 0x70
    unsigned int _shouldTransferMessage:1;	// 112 = 0x70
    unsigned int _shouldCopyMessage:1;	// 112 = 0x70
    unsigned int _shouldStopEvaluatingRules:1;	// 112 = 0x70
    unsigned int _highlightTextUsingColor:1;	// 112 = 0x70
    unsigned int _shouldNotifyUser:1;	// 112 = 0x70
    unsigned int _addInvitationAttachmentToCalendar:1;	// 113 = 0x71
    unsigned int _shouldSendNotification:1;	// 113 = 0x71
    BOOL _isJunkMailRule;	// 114 = 0x72
    BOOL _isSafeToMarkAsNotJunkRule;	// 115 = 0x73
    BOOL _isCalendarRule;	// 116 = 0x74
    BOOL _didChange;	// 117 = 0x75
    NSString *_uniqueId;	// 120 = 0x78
    NSDictionary *_otherInfo;	// 128 = 0x80
}

+ (id)appleScriptLock;	// IMP=0x00000000001d38af
+ (void)initialize;	// IMP=0x00000000001d3858
@property(nonatomic) BOOL didChange; // @synthesize didChange=_didChange;
@property(nonatomic) BOOL isCalendarRule; // @synthesize isCalendarRule=_isCalendarRule;
@property(nonatomic) BOOL isSafeToMarkAsNotJunkRule; // @synthesize isSafeToMarkAsNotJunkRule=_isSafeToMarkAsNotJunkRule;
@property(nonatomic) BOOL isJunkMailRule; // @synthesize isJunkMailRule=_isJunkMailRule;
@property(readonly, copy, nonatomic) NSDictionary *otherInfo; // @synthesize otherInfo=_otherInfo;
@property(copy, nonatomic) NSString *uniqueId; // @synthesize uniqueId=_uniqueId;
//- (void).cxx_destruct;	// IMP=0x00000000001dd989
- (id)objectSpecifier;	// IMP=0x00000000001dd80f
- (BOOL)isEqualToRule:(id)arg1;	// IMP=0x00000000001dd4c3
@property(nonatomic) BOOL shouldSendNotification;
@property(nonatomic) BOOL addInvitationAttachmentToCalendar;
@property(nonatomic) BOOL shouldNotifyUser;
@property(nonatomic) BOOL shouldStopEvaluatingRules;
@property(copy, nonatomic) NSString *playSound;
@property(copy, nonatomic) NSString *responseMessage;
- (void)handleDidChange;	// IMP=0x00000000001dd122
- (void)handleDidChangeIfNeeded;	// IMP=0x00000000001dd0eb
@property(copy, nonatomic) NSArray *autoResponseRecipients;
@property(nonatomic) int autoResponseType;
@property(readonly, nonatomic) BOOL affectsColorEvaluation;
@property(nonatomic) BOOL highlightTextUsingColor;
@property(retain, nonatomic) NSColor *color;
@property(copy, nonatomic) NSString *appleScriptPath;
@property(nonatomic) long long flagsToApply;
- (void)setAppleScriptDestinationMailbox:(id)arg1;	// IMP=0x00000000001dcc84
- (void)setAppleScriptCopyDestinationMailbox:(id)arg1;	// IMP=0x00000000001dcbbb
- (void)_evaluateIfNeeded:(id)arg1 andSetUsingBlock:(CDUnknownBlockType)arg2;	// IMP=0x00000000001dcae2
- (id)appleScriptCopyDestinationMailbox;	// IMP=0x00000000001dcad0
- (id)appleScriptDestinationMailbox;	// IMP=0x00000000001dcabe
- (BOOL)invalidateDestinationMailboxesForURLString:(id)arg1;	// IMP=0x00000000001dc9ee
- (void)tryToReconnectDestinationIfNeeded;	// IMP=0x00000000001dc86d
- (id)_tryToGetMailboxForURLString:(id)arg1;	// IMP=0x00000000001dc747
@property(retain, nonatomic) MFMailbox *copyDestinationMailbox;
- (id)_copyDestinationMailboxCreateIfNeeded:(BOOL)arg1;	// IMP=0x00000000001dc626
@property(retain, nonatomic) MFMailbox *destinationMailbox;
- (id)_destinationMailboxCreateIfNeeded:(BOOL)arg1;	// IMP=0x00000000001dc509
- (void)_setDestinationIvar:(id *)arg1 toDestinationMailbox:(id)arg2 destinationURLIvar:(id *)arg3;	// IMP=0x00000000001dc42c
- (id)_destinationMailbox:(id)arg1 withURL:(id)arg2 createIfNeeded:(BOOL)arg3 setUsingBlock:(CDUnknownBlockType)arg4;	// IMP=0x00000000001dc2af
@property(nonatomic) BOOL shouldCopyMessage;
@property(nonatomic) BOOL shouldTransferMessage;
- (void)removeObjectFromCriteriaAtIndex:(unsigned long long)arg1;	// IMP=0x00000000001dc151
- (void)insertObject:(id)arg1 inCriteriaAtIndex:(unsigned long long)arg2;	// IMP=0x00000000001dc0be
@property(copy, nonatomic) NSArray *criteria;
@property(nonatomic) BOOL allCriteriaMustBeSatisfied;
@property(nonatomic) BOOL isActive;
@property(readonly, nonatomic) BOOL isTerminalAction;
@property(copy, nonatomic) NSString *ruleName;
- (BOOL)isValid:(id *)arg1 options:(unsigned int)arg2;	// IMP=0x00000000001dae34
- (BOOL)doesMessageSatisfyCriteria:(id)arg1 fetchBody:(BOOL)arg2 needsBody:(char *)arg3 successfullyEvaluated:(char *)arg4;	// IMP=0x00000000001da738
- (void)addHeadersRequiredForRoutingToArray:(id)arg1;	// IMP=0x00000000001da70e
- (void)_performAddInvitationAttachmentToCalendarActionOnMessages:(id)arg1;	// IMP=0x00000000001d9d47
- (void)_performAppleScriptActionWithMessages:(id)arg1;	// IMP=0x00000000001d972e
- (void)_performAutoResponseActionOnMessages:(id)arg1;	// IMP=0x00000000001d9353
- (id)_performAutoResponseActionOnMessage:(id)arg1 encrypt:(BOOL)arg2 includeOrignalMessageText:(BOOL)arg3;	// IMP=0x00000000001d8274
- (void)_performUserNotificationAction:(id)arg1;	// IMP=0x00000000001d8181
- (void)performActionsOnMessages:(id)arg1 sourceStores:(id)arg2 destinationStores:(id)arg3 transferredOrDeleted:(id)arg4 rejectedMessages:(id)arg5 messagesToBeDeleted:(id)arg6;	// IMP=0x00000000001d6c01
- (void)_appendMessages:(id)arg1 fromSourceMailbox:(id)arg2 toDestinationMailbox:(id)arg3 destinationStores:(id)arg4 rejectedMessages:(id)arg5 messagesToBeDeleted:(id)arg6;	// IMP=0x00000000001d65ab
- (void)_updateDefaultAppleEmailAddressRule;	// IMP=0x00000000001d6150
- (id)dictionaryRepresentationIncludePII:(BOOL)arg1;	// IMP=0x00000000001d5517
- (id)dictionaryRepresentation;	// IMP=0x00000000001d5500
- (id)initWithDictionaryRepresentation:(id)arg1;	// IMP=0x00000000001d4620
- (id)mailboxPathForMailboxURL:(id)arg1 createIfNeeded:(BOOL)arg2;	// IMP=0x00000000001d44a2
- (id)_syncableMailboxURLStringForMailbox:(id)arg1;	// IMP=0x00000000001d4433
- (id)initWithRule:(id)arg1;	// IMP=0x00000000001d437b
- (id)init;	// IMP=0x00000000001d422b
- (BOOL)isEquivalentExceptForTitleAndIDs:(id)arg1;	// IMP=0x00000000001d3e97
- (unsigned long long)hash;	// IMP=0x00000000001d3e53
- (BOOL)isEqual:(id)arg1;	// IMP=0x00000000001d3d94
- (id)description;	// IMP=0x00000000001d3ca5
- (id)debugDescription;	// IMP=0x00000000001d3aa9
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000000001d38c0
- (void)setAddress:(id)arg1 forResponseType:(int)arg2;	// IMP=0x00000000001d3645
- (void)removeFromCriteriaAtIndex:(unsigned long long)arg1;	// IMP=0x00000000001d3617
- (void)insertInCriteria:(id)arg1;	// IMP=0x00000000001d358d
- (void)insertInCriteria:(id)arg1 atIndex:(unsigned long long)arg2;	// IMP=0x00000000001d34fe
- (void)setRuleDescription:(id)arg1;	// IMP=0x00000000001d3441
- (id)ruleDescription;	// IMP=0x00000000001d342f
- (void)setActionRunApplescript:(id)arg1;	// IMP=0x00000000001d329e
- (id)actionRunApplescript;	// IMP=0x00000000001d31fd
- (void)setActionReplyText:(id)arg1;	// IMP=0x00000000001d3085
- (id)actionReplyText;	// IMP=0x00000000001d3022
- (void)setActionRedirectToAddress:(id)arg1;	// IMP=0x00000000001d2fe2
- (id)actionRedirectToAddress;	// IMP=0x00000000001d2f4b
- (void)setActionMarkAsRead:(BOOL)arg1;	// IMP=0x00000000001d2ee2
- (BOOL)actionMarkAsRead;	// IMP=0x00000000001d2ecc
- (void)setActionMarkAsFlaggedStatus:(long long)arg1;	// IMP=0x00000000001d2cbd
- (long long)actionMarkAsFlaggedStatus;	// IMP=0x00000000001d2c8b
- (void)setActionMarkAsFlagged:(BOOL)arg1;	// IMP=0x00000000001d2c22
- (BOOL)actionMarkAsFlagged;	// IMP=0x00000000001d2c09
- (void)setActionForwardText:(id)arg1;	// IMP=0x00000000001d2b24
- (id)actionForwardText;	// IMP=0x00000000001d2ac1
- (void)setActionForwardToAddress:(id)arg1;	// IMP=0x00000000001d2a81
- (id)actionForwardToAddress;	// IMP=0x00000000001d29ea
- (void)setActionDeleteMessage:(BOOL)arg1;	// IMP=0x00000000001d2981
- (BOOL)actionDeleteMessage;	// IMP=0x00000000001d2969
- (unsigned int)highlightColorValue:(id)arg1;	// IMP=0x00000000001d2931
- (void)setActionColorMessage:(unsigned int)arg1;	// IMP=0x00000000001d28b9
- (unsigned int)actionColorMessage;	// IMP=0x00000000001d2862
- (void)updateIsActive;	// IMP=0x00000000001d2822

@end

