//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Mail/MFLibraryUpgradeStep.h>

@interface MFResetEWSFolderHierarchyUpgradeStep : MFLibraryUpgradeStep
{
}

+ (BOOL)requiredAfterBackbooting;	// IMP=0x000000000024989c
+ (unsigned long long)targetVersion;	// IMP=0x0000000000249891
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x00000000002498a7

@end

