//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class MFQuoteParser, NSMutableArray, NSOperationQueue;

@interface MFSnippetCalculator : NSObject
{
    NSMutableArray *_messagesToCalculate;	// 8 = 0x8
    BOOL _isCalculating;	// 16 = 0x10
    id <MFSnippetCalculatorDelegate> _delegate;	// 24 = 0x18
    MFQuoteParser *_quoteParser;	// 32 = 0x20
    NSOperationQueue *_calculationQueue;	// 40 = 0x28
}

+ (id)localizeSnippet:(id)arg1;	// IMP=0x000000000026a0aa
@property(readonly, nonatomic) NSOperationQueue *calculationQueue; // @synthesize calculationQueue=_calculationQueue;
@property(readonly, nonatomic) MFQuoteParser *quoteParser; // @synthesize quoteParser=_quoteParser;
@property __weak id <MFSnippetCalculatorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x000000000026a245
- (id)_snippetFromAttachments:(id)arg1;	// IMP=0x0000000000269f70
- (id)_snippetForMessage:(id)arg1;	// IMP=0x0000000000269cdc
- (void)_performSnippetCalculation;	// IMP=0x0000000000269a37
- (void)_queueCalculationIfNecessary;	// IMP=0x0000000000269972
- (void)calculateSnippetsForMessages:(id)arg1;	// IMP=0x00000000002698b0
- (id)immediatelyCalculateSnippetForMessage:(id)arg1;	// IMP=0x00000000002697cc
- (id)init;	// IMP=0x00000000002696e6

@end

