//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "MCActivityTarget.h"

@class MCInvocationQueue, NSConditionLock, NSMutableDictionary, NSMutableSet, NSString;

@interface MFSpotlightManager : NSObject <MCActivityTarget>
{
    NSConditionLock *_attachmentIndexingLock;	// 8 = 0x8
    NSMutableSet *_messsagesScheduledForAttachmentIndexing;	// 16 = 0x10
    NSMutableDictionary *_queryObserverDictionary;	// 24 = 0x18
    MCInvocationQueue *_indexQueue;	// 32 = 0x20
}

+ (id)_log;	// IMP=0x000000000026f1eb
+ (id)sharedInstance;	// IMP=0x000000000026ef48
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x000000000026ee8e
@property(readonly, nonatomic) MCInvocationQueue *indexQueue; // @synthesize indexQueue=_indexQueue;
- (void).cxx_destruct;	// IMP=0x0000000000270cd2
- (id)acquireQueryObserver:(long long)arg1;	// IMP=0x0000000000270c19
- (void)unregisterQueryObserver:(long long)arg1;	// IMP=0x0000000000270b7e
- (long long)registerQueryObserver:(id)arg1;	// IMP=0x0000000000270aa0
- (void)immediatelyIndexAttachmentsForMessage:(id)arg1;	// IMP=0x0000000000270947
- (void)indexAttachmentsForMessage:(id)arg1;	// IMP=0x000000000027084a
- (void)_synchronouslyIndexAttachmentsForMessages:(id)arg1 messageCount:(unsigned long long)arg2;	// IMP=0x0000000000270297
- (void)_indexAttachmentsForScheduledMessages;	// IMP=0x000000000026ffe0
- (void)_triggerNowAttachmentIndexing;	// IMP=0x000000000026fe79
- (void)_triggerDelayedAttachmentIndexing;	// IMP=0x000000000026fdcc
- (void)markMessagesAsPrinted:(id)arg1;	// IMP=0x000000000026fd12
- (void)_markMessagesAsPrinted:(id)arg1;	// IMP=0x000000000026f997
- (void)setAttributesForFileWrapper:(id)arg1 atFile:(id)arg2;	// IMP=0x000000000026f8e3
- (void)_setAttributesForFileWrapper:(id)arg1 atFile:(id)arg2;	// IMP=0x000000000026f350
- (id)sharedKeySetForFileWrapperSpotlightAttributes;	// IMP=0x000000000026f24a
- (void)dealloc;	// IMP=0x000000000026f11a
- (id)init;	// IMP=0x000000000026f013

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, copy, nonatomic) NSString *displayName;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) BOOL isSmartMailbox;
@property(readonly) Class superclass;

@end

