//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSMutableArray.h"

@interface NSMutableArray (Convenience)
- (BOOL)addObjectIfAbsentAccordingToEquals:(id)arg1;
- (BOOL)addObjectIfAbsent:(id)arg1;
- (void)addAbsentObjectsFromArrayAccordingToEquals:(id)arg1;
- (void)addAbsentObjectsFromArray:(id)arg1;
//- (unsigned long long)insertObjectIfAbsent:(id)arg1 usingComparator:(CDUnknownBlockType)arg2;
@end

