
typedef enum { 
    GPGErrorNoError = 0, 
    GPGErrorGeneralError = 1, 
    GPGErrorUnknownPacket = 2, 
    GPGErrorUnknownVersion = 3, 
    GPGErrorInvalidPublicKeyAlgorithm = 4, 
    GPGErrorInvalidDigestAlgorithm = 5, 
    GPGErrorBadPublicKey = 6, 
    GPGErrorBadSecretKey = 7, 
    GPGErrorBadSignature = 8, 
    GPGErrorNoPublicKey = 9, 
    GPGErrorChecksumError = 10, 
    GPGErrorBadPassphrase = 11, 
    GPGErrorInvalidCipherAlgorithm = 12, 
    GPGErrorOpenKeyring = 13, 
    GPGErrorInvalidPacket = 14, 
    GPGErrorInvalidArmor = 15, 
    GPGErrorNoUserID = 16, 
    GPGErrorNoSecretKey = 17, 
    GPGErrorWrongSecretKey = 18, 
    GPGErrorBadSessionKey = 19, 
    GPGErrorUnknownCompressionAlgorithm = 20, 
    GPGErrorNoPrime = 21, 
    GPGErrorNoEncodingMethod = 22, 
    GPGErrorNoEncryptionScheme = 23, 
    GPGErrorNoSignatureScheme = 24, 
    GPGErrorInvalidAttribute = 25, 
    GPGErrorNoValue = 26, 
    GPGErrorNotFound = 27, 
    GPGErrorValueNotFound = 28, 
    GPGErrorSyntax = 29, 
    GPGErrorBadMPI = 30, 
    GPGErrorInvalidPassphrase = 31, 
    GPGErrorSignatureClass = 32, 
    GPGErrorResourceLimit = 33, 
    GPGErrorInvalidKeyring = 34, 
    GPGErrorTrustDBError = 35, 
    GPGErrorBadCertificate = 36, 
    GPGErrorInvalidUserID = 37, 
    GPGErrorUnexpected = 38, 
    GPGErrorTimeConflict = 39, 
    GPGErrorKeyServerError = 40, 
    GPGErrorWrongPublicKeyAlgorithm = 41, 
    GPGErrorTributeToDA = 42, 
    GPGErrorWeakKey = 43, 
    GPGErrorInvalidKeyLength = 44, 
    GPGErrorInvalidArgument = 45, 
    GPGErrorBadURI = 46, 
    GPGErrorInvalidURI = 47, 
    GPGErrorNetworkError = 48, 
    GPGErrorUnknownHost = 49, 
    GPGErrorSelfTestFailed = 50, 
    GPGErrorNotEncrypted = 51, 
    GPGErrorNotProcessed = 52, 
    GPGErrorUnusablePublicKey = 53, 
    GPGErrorUnusableSecretKey = 54, 
    GPGErrorInvalidValue = 55, 
    GPGErrorBadCertificateChain = 56, 
    GPGErrorMissingCertificate = 57, 
    GPGErrorNoData = 58, 
    GPGErrorBug = 59, 
    GPGErrorNotSupported = 60, 
    GPGErrorInvalidOperationCode = 61, 
    GPGErrorTimeout = 62, 
    GPGErrorInternalError = 63, 
    GPGErrorEOFInGCrypt = 64, 
    GPGErrorInvalidObject = 65, 
    GPGErrorObjectTooShort = 66, 
    GPGErrorObjectTooLarge = 67, 
    GPGErrorNoObject = 68, 
    GPGErrorNotImplemented = 69, 
    GPGErrorConflict = 70, 
    GPGErrorInvalidCipherMode = 71, 
    GPGErrorInvalidFlag = 72, 
    GPGErrorInvalidHandle = 73, 
    GPGErrorTruncatedResult = 74, 
    GPGErrorIncompleteLine = 75, 
    GPGErrorInvalidResponse = 76, 
    GPGErrorNoAgent = 77, 
    GPGErrorAgentError = 78, 
    GPGErrorInvalidData = 79, 
    GPGErrorAssuanServerFault = 80, 
    GPGErrorAssuanError = 81, 
    GPGErrorInvalidSessionKey = 82, 
    GPGErrorInvalidSEXP = 83, 
    GPGErrorUnsupportedAlgorithm = 84, 
    GPGErrorNoPINEntry = 85, 
    GPGErrorPINEntryError = 86, 
    GPGErrorBadPIN = 87, 
    GPGErrorInvalidName = 88, 
    GPGErrorBadData = 89, 
    GPGErrorInvalidParameter = 90, 
    GPGErrorWrongCard = 91, 
    GPGErrorNoDirManager = 92, 
    GPGErrorDirManagerError = 93, 
    GPGErrorCertificateRevoked = 94, 
    GPGErrorNoCRLKnown = 95, 
    GPGErrorCRLTooOld = 96, 
    GPGErrorLineTooLong = 97, 
    GPGErrorNotTrusted = 98, 
    GPGErrorCancelled = 99, 
    GPGErrorBadCACertificate = 100, 
    GPGErrorCertificateExpired = 101, 
    GPGErrorCertificateTooYoung = 102, 
    GPGErrorUnsupportedCertificate = 103, 
    GPGErrorUnknownSEXP = 104, 
    GPGErrorUnsupportedProtection = 105, 
    GPGErrorCorruptedProtection = 106, 
    GPGErrorAmbiguousName = 107, 
    GPGErrorCardError = 108, 
    GPGErrorCardReset = 109, 
    GPGErrorCardRemoved = 110, 
    GPGErrorInvalidCard = 111, 
    GPGErrorCardNotPresent = 112, 
    GPGErrorNoPKCS15Application = 113, 
    GPGErrorNotConfirmed = 114, 
    GPGErrorConfigurationError = 115, 
    GPGErrorNoPolicyMatch = 116, 
    GPGErrorInvalidIndex = 117, 
    GPGErrorInvalidID = 118, 
    GPGErrorNoSCDaemon = 119, 
    GPGErrorSCDaemonError = 120, 
    GPGErrorUnsupportedProtocol = 121, 
    GPGErrorBadPINMethod = 122, 
    GPGErrorCardNotInitialized = 123, 
    GPGErrorUnsupportedOperation = 124, 
    GPGErrorWrongKeyUsage = 125, 
    GPGErrorNothingFound = 126, 
    GPGErrorWrongBLOBType = 127, 
    GPGErrorMissingValue = 128, 
    GPGErrorHardware = 129, 
    GPGErrorPINBlocked = 130, 
    GPGErrorUseConditions = 131, 
    GPGErrorPINNotSynced = 132, 
    GPGErrorInvalidCRL = 133, 
    GPGErrorBadBER = 134, 
    GPGErrorInvalidBER = 135, 
    GPGErrorElementNotFound = 136, 
    GPGErrorIdentifierNotFound = 137, 
    GPGErrorInvalidTag = 138, 
    GPGErrorInvalidLength = 139, 
    GPGErrorInvalidKeyInfo = 140, 
    GPGErrorUnexpectedTag = 141, 
    GPGErrorNotDEREncoded = 142, 
    GPGErrorNoCMSObject = 143, 
    GPGErrorInvalidCMSObject = 144, 
    GPGErrorUnknownCMSObject = 145, 
    GPGErrorUnsupportedCMSObject = 146, 
    GPGErrorUnsupportedEncoding = 147, 
    GPGErrorUnsupportedCMSVersion = 148, 
    GPGErrorUnknownAlgorithm = 149, 
    GPGErrorInvalidEngine = 150, 
    GPGErrorPublicKeyNotTrusted = 151, 
    GPGErrorDecryptionFailed = 152, 
    GPGErrorKeyExpired = 153, 
    GPGErrorSignatureExpired = 154, 
    GPGErrorEncodingProblem = 155, 
    GPGErrorInvalidState = 156, 
    GPGErrorDuplicateValue = 157, 
    GPGErrorMissingAction = 158, 
    GPGErrorModuleNotFound = 159, 
    GPGErrorInvalidOIDString = 160, 
    GPGErrorInvalidTime = 161, 
    GPGErrorInvalidCRLObject = 162, 
    GPGErrorUnsupportedCRLVersion = 163, 
    GPGErrorInvalidCertObject = 164, 
    GPGErrorUnknownName = 165, 
    GPGErrorLocaleProblem = 166, 
    GPGErrorNotLocked = 167, 
    GPGErrorProtocolViolation = 168, 
    GPGErrorInvalidMac = 169, 
    GPGErrorInvalidRequest = 170,
	GPGErrorUnknownExtn = 171,
	GPGErrorUnknownCritExtn = 172,
	GPGErrorLocked = 173,
	GPGErrorUnknownOption = 174,
	GPGErrorUnknownCommand = 175,
	GPGErrorNotOperational = 176,
	GPGErrorNoPassphrase = 177,
	GPGErrorNoPin = 178,
	GPGErrorNotEnabled = 179,
	GPGErrorNoEngine = 180,
	GPGErrorMissingKey = 181,
	GPGErrorTooMany = 182,
	GPGErrorLimitReached = 183,
	GPGErrorNotInitialized = 184,
	GPGErrorMissingIssuerCert = 185,
	GPGErrorNoKeyserver = 186,
	GPGErrorInvCurve = 187,
	GPGErrorUnknownCurve = 188,
	GPGErrorDupKey = 189,
	GPGErrorAmbiguous = 190,
	GPGErrorNoCryptCtx = 191,
	GPGErrorWrongCryptCtx = 192,
	GPGErrorBadCryptCtx = 193,
	GPGErrorCryptCtxConflict = 194,
	GPGErrorBrokenPubkey = 195,
	GPGErrorBrokenSeckey = 196,
	GPGErrorMacAlgo = 197,
	GPGErrorFullyCanceled = 198,
	GPGErrorUnfinished = 199,
    GPGErrorBufferTooShort = 200,
    GPGErrorSEXPInvalidLengthSpec = 201, 
    GPGErrorSEXPStringTooLong = 202, 
    GPGErrorSEXPUnmatchedParenthese = 203, 
    GPGErrorSEXPNotCanonical = 204, 
    GPGErrorSEXPBadCharacter = 205, 
    GPGErrorSEXPBadQuotation = 206, 
    GPGErrorSEXPZeroPrefix = 207, 
    GPGErrorSEXPNestedDisplayHint = 208, 
    GPGErrorSEXPUnmatchedDisplayHint = 209, 
    GPGErrorSEXPUnexpectedPunctuation = 210, 
    GPGErrorSEXPBadHexCharacter = 211, 
    GPGErrorSEXPOddHexNumbers = 212, 
    GPGErrorSEXPBadOctalCharacter = 213,  
	GPGErrorSubkeysExpOrRev = 217, // All subkeys are expired or revoked
	GPGErrorDbCorrupted = 218, // Database is corrupted
	GPGErrorServerFailed = 219, // Server indicated a failure
	GPGErrorNoName = 220, // No name
	GPGErrorNoKey = 221, // No key
	GPGErrorLegacyKey = 222, // Legacy key
	GPGErrorRequestTooShort = 223, // Request too short
	GPGErrorRequestTooLong = 224, // Request too long
	GPGErrorObjTermState = 225, // Object is in termination state
	GPGErrorNoCertChain = 226, // No certificate chain
	GPGErrorCertTooLarge = 227, // Certificate is too large
	GPGErrorInvRecord = 228, // Invalid record
	GPGErrorBadMac = 229, // The MAC does not verify
	GPGErrorUnexpectedMsg = 230, // Unexpected message
	GPGErrorComprFailed = 231, // Compression or decompression failed
	GPGErrorWouldWrap = 232, // A counter would wrap
	GPGErrorFatalAlert = 233, // Fatal alert message received
	GPGErrorNoCipher = 234, // No cipher algorithm
	GPGErrorMissingClientCert = 235, // Missing client certificate
	GPGErrorCloseNotify = 236, // Close notification received
	GPGErrorTicketExpired = 237, // Ticket expired
	GPGErrorBadTicket = 238, // Bad ticket
	GPGErrorUnknownIdentity = 239, // Unknown identity
	GPGErrorBadHsCert = 240, // Bad certificate message in handshake
	GPGErrorBadHsCertReq = 241, // Bad certificate request message in handshake
	GPGErrorBadHsCertVer = 242, // Bad certificate verify message in handshake
	GPGErrorBadHsChangeCipher = 243, // Bad change cipher message in handshake
	GPGErrorBadHsClientHello = 244, // Bad client hello message in handshake
	GPGErrorBadHsServerHello = 245, // Bad server hello message in handshake
	GPGErrorBadHsServerHelloDone = 246, // Bad server hello done message in handshake
	GPGErrorBadHsFinished = 247, // Bad finished message in handshake
	GPGErrorBadHsServerKex = 248, // Bad server key exchange message in handshake
	GPGErrorBadHsClientKex = 249, // Bad client key exchange message in handshake
	GPGErrorBogusString = 250, // Bogus string
	GPGErrorForbidden = 251, // Forbidden
	GPGErrorKeyDisabled = 252, // Key disabled
	GPGErrorKeyOnCard = 253, // Not possible with a card based key
	GPGErrorInvLockObj = 254, // Invalid lock object
	GPGErrorTrue = 255, // True
	GPGErrorFalse = 256, // False
	GPGErrorAssGeneral = 257, // General IPC error
	GPGErrorAssAcceptFailed = 258, // IPC accept call failed
	GPGErrorAssConnectFailed = 259, // IPC connect call failed
	GPGErrorAssInvResponse = 260, // Invalid IPC response
	GPGErrorAssInvValue = 261, // Invalid value passed to IPC
	GPGErrorAssIncompleteLine = 262, // Incomplete line passed to IPC
	GPGErrorAssLineTooLong = 263, // Line passed to IPC too long
	GPGErrorAssNestedCommands = 264, // Nested IPC commands
	GPGErrorAssNoDataCb = 265, // No data callback in IPC
	GPGErrorAssNoInquireCb = 266, // No inquire callback in IPC
	GPGErrorAssNotAServer = 267, // Not an IPC server
	GPGErrorAssNotAClient = 268, // Not an IPC client
	GPGErrorAssServerStart = 269, // Problem starting IPC server
	GPGErrorAssReadError = 270, // IPC read error
	GPGErrorAssWriteError = 271, // IPC write error
	GPGErrorAssTooMuchData = 273, // Too much data for IPC layer
	GPGErrorAssUnexpectedCmd = 274, // Unexpected IPC command
	GPGErrorAssUnknownCmd = 275, // Unknown IPC command
	GPGErrorAssSyntax = 276, // IPC syntax error
	GPGErrorAssCanceled = 277, // IPC call has been cancelled
	GPGErrorAssNoInput = 278, // No input source for IPC
	GPGErrorAssNoOutput = 279, // No output source for IPC
	GPGErrorAssParameter = 280, // IPC parameter error
	GPGErrorAssUnknownInquire = 281, // Unknown IPC inquire
	GPGErrorEngineTooOld = 300, // Crypto engine too old
	GPGErrorWindowTooSmall = 301, // Screen or window too small
	GPGErrorWindowTooLarge = 302, // Screen or window too large
	GPGErrorMissingEnvvar = 303, // Required environment variable not set
	GPGErrorUserIdExists = 304, // User ID already exists
	GPGErrorNameExists = 305, // Name already exists
	GPGErrorDupName = 306, // Duplicated name
	GPGErrorTooYoung = 307, // Object is too young
	GPGErrorTooOld = 308, // Object is too old
	GPGErrorUnknownFlag = 309, // Unknown flag
	GPGErrorInvOrder = 310, // Invalid execution order
	GPGErrorAlreadyFetched = 311, // Already fetched
	GPGErrorTryLater = 312, // Try again later
	GPGErrorWrongName = 313, // Wrong name
	GPGErrorSystemBug = 666, // System bug detected
	GPGErrorDnsUnknown = 711, // Unknown DNS error
	GPGErrorDnsSection = 712, // Invalid DNS section
	GPGErrorDnsAddress = 713, // Invalid textual address form
	GPGErrorDnsNoQuery = 714, // Missing DNS query packet
	GPGErrorDnsNoAnswer = 715, // Missing DNS answer packet
	GPGErrorDnsClosed = 716, // Connection closed in DNS
	GPGErrorDnsVerify = 717, // Verification failed in DNS
	GPGErrorDnsTimeout = 718, // DNS Timeout
	GPGErrorLdapGeneral = 721, // General LDAP error
	GPGErrorLdapAttrGeneral = 722, // General LDAP attribute error
	GPGErrorLdapNameGeneral = 723, // General LDAP name error
	GPGErrorLdapSecurityGeneral = 724, // General LDAP security error
	GPGErrorLdapServiceGeneral = 725, // General LDAP service error
	GPGErrorLdapUpdateGeneral = 726, // General LDAP update error
	GPGErrorLdapEGeneral = 727, // Experimental LDAP error code
	GPGErrorLdapXGeneral = 728, // Private LDAP error code
	GPGErrorLdapOtherGeneral = 729, // Other general LDAP error
	GPGErrorLdapXConnecting = 750, // LDAP connecting failed (X)
	GPGErrorLdapReferralLimit = 751, // LDAP referral limit exceeded
	GPGErrorLdapClientLoop = 752, // LDAP client loop
	GPGErrorLdapNoResults = 754, // No LDAP results returned
	GPGErrorLdapControlNotFound = 755, // LDAP control not found
	GPGErrorLdapNotSupported = 756, // Not supported by LDAP
	GPGErrorLdapConnect = 757, // LDAP connect error
	GPGErrorLdapNoMemory = 758, // Out of memory in LDAP
	GPGErrorLdapParam = 759, // Bad parameter to an LDAP routine
	GPGErrorLdapUserCancelled = 760, // User cancelled LDAP operation
	GPGErrorLdapFilter = 761, // Bad LDAP search filter
	GPGErrorLdapAuthUnknown = 762, // Unknown LDAP authentication method
	GPGErrorLdapTimeout = 763, // Timeout in LDAP
	GPGErrorLdapDecoding = 764, // LDAP decoding error
	GPGErrorLdapEncoding = 765, // LDAP encoding error
	GPGErrorLdapLocal = 766, // LDAP local error
	GPGErrorLdapServerDown = 767, // Cannot contact LDAP server
	GPGErrorLdapSuccess = 768, // LDAP success
	GPGErrorLdapOperations = 769, // LDAP operations error
	GPGErrorLdapProtocol = 770, // LDAP protocol error
	GPGErrorLdapTimelimit = 771, // Time limit exceeded in LDAP
	GPGErrorLdapSizelimit = 772, // Size limit exceeded in LDAP
	GPGErrorLdapCompareFalse = 773, // LDAP compare false
	GPGErrorLdapCompareTrue = 774, // LDAP compare true
	GPGErrorLdapUnsupportedAuth = 775, // LDAP authentication method not supported
	GPGErrorLdapStrongAuthRqrd = 776, // Strong(er) LDAP authentication required
	GPGErrorLdapPartialResults = 777, // Partial LDAP results+referral received
	GPGErrorLdapReferral = 778, // LDAP referral
	GPGErrorLdapAdminlimit = 779, // Administrative LDAP limit exceeded
	GPGErrorLdapUnavailCritExtn = 780, // Critical LDAP extension is unavailable
	GPGErrorLdapConfidentRqrd = 781, // Confidentiality required by LDAP
	GPGErrorLdapSaslBindInprog = 782, // LDAP SASL bind in progress
	GPGErrorLdapNoSuchAttribute = 784, // No such LDAP attribute
	GPGErrorLdapUndefinedType = 785, // Undefined LDAP attribute type
	GPGErrorLdapBadMatching = 786, // Inappropriate matching in LDAP
	GPGErrorLdapConstViolation = 787, // Constraint violation in LDAP
	GPGErrorLdapTypeValueExists = 788, // LDAP type or value exists
	GPGErrorLdapInvSyntax = 789, // Invalid syntax in LDAP
	GPGErrorLdapNoSuchObj = 800, // No such LDAP object
	GPGErrorLdapAliasProblem = 801, // LDAP alias problem
	GPGErrorLdapInvDnSyntax = 802, // Invalid DN syntax in LDAP
	GPGErrorLdapIsLeaf = 803, // LDAP entry is a leaf
	GPGErrorLdapAliasDeref = 804, // LDAP alias dereferencing problem
	GPGErrorLdapXProxyAuthFail = 815, // LDAP proxy authorization failure (X)
	GPGErrorLdapBadAuth = 816, // Inappropriate LDAP authentication
	GPGErrorLdapInvCredentials = 817, // Invalid LDAP credentials
	GPGErrorLdapInsufficientAcc = 818, // Insufficient access for LDAP
	GPGErrorLdapBusy = 819, // LDAP server is busy
	GPGErrorLdapUnavailable = 820, // LDAP server is unavailable
	GPGErrorLdapUnwillToPerform = 821, // LDAP server is unwilling to perform
	GPGErrorLdapLoopDetect = 822, // Loop detected by LDAP
	GPGErrorLdapNamingViolation = 832, // LDAP naming violation
	GPGErrorLdapObjClsViolation = 833, // LDAP object class violation
	GPGErrorLdapNotAllowNonleaf = 834, // LDAP operation not allowed on non-leaf
	GPGErrorLdapNotAllowOnRdn = 835, // LDAP operation not allowed on RDN
	GPGErrorLdapAlreadyExists = 836, // Already exists (LDAP)
	GPGErrorLdapNoObjClassMods = 837, // Cannot modify LDAP object class
	GPGErrorLdapResultsTooLarge = 838, // LDAP results too large
	GPGErrorLdapAffectsMultDsas = 839, // LDAP operation affects multiple DSAs
	GPGErrorLdapVlv = 844, // Virtual LDAP list view error
	GPGErrorLdapOther = 848, // Other LDAP error
	GPGErrorLdapCupResourceLimit = 881, // Resources exhausted in LCUP
	GPGErrorLdapCupSecViolation = 882, // Security violation in LCUP
	GPGErrorLdapCupInvData = 883, // Invalid data in LCUP
	GPGErrorLdapCupUnsupScheme = 884, // Unsupported scheme in LCUP
	GPGErrorLdapCupReload = 885, // Reload required in LCUP
	GPGErrorLdapCancelled = 886, // LDAP cancelled
	GPGErrorLdapNoSuchOperation = 887, // No LDAP operation to cancel
	GPGErrorLdapTooLate = 888, // Too late to cancel LDAP
	GPGErrorLdapCannotCancel = 889, // Cannot cancel LDAP
	GPGErrorLdapAssertionFailed = 890, // LDAP assertion failed
	GPGErrorLdapProxAuthDenied = 891, // Proxied authorization denied by LDAP
	GPGErrorTruncatedKeyListing = 1024,
	GPGErrorUser2 = 1025,
	GPGErrorUser3 = 1026,
	GPGErrorUser4 = 1027,
	GPGErrorUser5 = 1028,
	GPGErrorUser6 = 1029,
	GPGErrorUser7 = 1030,
	GPGErrorUser8 = 1031,
	GPGErrorUser9 = 1032,
	GPGErrorUser10 = 1033,
	GPGErrorUser11 = 1034,
	GPGErrorUser12 = 1035,
	GPGErrorUser13 = 1036,
	GPGErrorUser14 = 1037,
	GPGErrorUser15 = 1038,
	GPGErrorUser16 = 1039,
	GPGErrorSubkeyNotFound = 1040, // GPGTools specific code.
	GPGErrorBadMDC = 1041, // GPGTools specific code.
	GPGErrorNoMDC = 1042, // GPGTools specific code.
	GPGErrorMissingErrno = 16381,
	GPGErrorUnknownErrno = 16382,
	GPGErrorEOF = 16383,
	// The following error codes are used to map system errors.
	GPGError_E2BIG = 16384, 
    GPGError_EACCES = 16385, 
    GPGError_EADDRINUSE = 16386, 
    GPGError_EADDRNOTAVAIL = 16387, 
    GPGError_EADV = 16388, 
    GPGError_EAFNOSUPPORT = 16389, 
    GPGError_EAGAIN = 16390, 
    GPGError_EALREADY = 16391, 
    GPGError_EAUTH = 16392, 
    GPGError_EBACKGROUND = 16393, 
    GPGError_EBADE = 16394, 
    GPGError_EBADF = 16395, 
    GPGError_EBADFD = 16396, 
    GPGError_EBADMSG = 16397, 
    GPGError_EBADR = 16398, 
    GPGError_EBADRPC = 16399, 
    GPGError_EBADRQC = 16400, 
    GPGError_EBADSLT = 16401, 
    GPGError_EBFONT = 16402, 
    GPGError_EBUSY = 16403, 
    GPGError_ECANCELLED = 16404, 
    GPGError_ECHILD = 16405, 
    GPGError_ECHRNG = 16406, 
    GPGError_ECOMM = 16407, 
    GPGError_ECONNABORTED = 16408, 
    GPGError_ECONNREFUSED = 16409, 
    GPGError_ECONNRESET = 16410, 
    GPGError_ED = 16411, 
    GPGError_EDEADLK = 16412, 
    GPGError_EDEADLOCK = 16413, 
    GPGError_EDESTADDRREQ = 16414, 
    GPGError_EDIED = 16415, 
    GPGError_EDOM = 16416, 
    GPGError_EDOTDOT = 16417, 
    GPGError_EDQUOT = 16418, 
    GPGError_EEXIST = 16419, 
    GPGError_EFAULT = 16420, 
    GPGError_EFBIG = 16421, 
    GPGError_EFTYPE = 16422, 
    GPGError_EGRATUITOUS = 16423, 
    GPGError_EGREGIOUS = 16424, 
    GPGError_EHOSTDOWN = 16425, 
    GPGError_EHOSTUNREACH = 16426, 
    GPGError_EIDRM = 16427, 
    GPGError_EIEIO = 16428, 
    GPGError_EILSEQ = 16429, 
    GPGError_EINPROGRESS = 16430, 
    GPGError_EINTR = 16431, 
    GPGError_EINVAL = 16432, 
    GPGError_EIO = 16433, 
    GPGError_EISCONN = 16434, 
    GPGError_EISDIR = 16435, 
    GPGError_EISNAM = 16436, 
    GPGError_EL2HLT = 16437, 
    GPGError_EL2NSYNC = 16438, 
    GPGError_EL3HLT = 16439, 
    GPGError_EL3RST = 16440, 
    GPGError_ELIBACC = 16441, 
    GPGError_ELIBBAD = 16442, 
    GPGError_ELIBEXEC = 16443, 
    GPGError_ELIBMAX = 16444, 
    GPGError_ELIBSCN = 16445, 
    GPGError_ELNRNG = 16446, 
    GPGError_ELOOP = 16447, 
    GPGError_EMEDIUMTYPE = 16448, 
    GPGError_EMFILE = 16449, 
    GPGError_EMLINK = 16450, 
    GPGError_EMSGSIZE = 16451, 
    GPGError_EMULTIHOP = 16452, 
    GPGError_ENAMETOOLONG = 16453, 
    GPGError_ENAVAIL = 16454, 
    GPGError_ENEEDAUTH = 16455, 
    GPGError_ENETDOWN = 16456, 
    GPGError_ENETRESET = 16457, 
    GPGError_ENETUNREACH = 16458, 
    GPGError_ENFILE = 16459, 
    GPGError_ENOANO = 16460, 
    GPGError_ENOBUFS = 16461, 
    GPGError_ENOCSI = 16462, 
    GPGError_ENODATA = 16463, 
    GPGError_ENODEV = 16464, 
    GPGError_ENOENT = 16465, 
    GPGError_ENOEXEC = 16466, 
    GPGError_ENOLCK = 16467, 
    GPGError_ENOLINK = 16468, 
    GPGError_ENOMEDIUM = 16469, 
    GPGError_ENOMEM = 16470, 
    GPGError_ENOMSG = 16471, 
    GPGError_ENONET = 16472, 
    GPGError_ENOPKG = 16473, 
    GPGError_ENOPROTOOPT = 16474, 
    GPGError_ENOSPC = 16475, 
    GPGError_ENOSR = 16476, 
    GPGError_ENOSTR = 16477, 
    GPGError_ENOSYS = 16478, 
    GPGError_ENOTBLK = 16479, 
    GPGError_ENOTCONN = 16480, 
    GPGError_ENOTDIR = 16481, 
    GPGError_ENOTEMPTY = 16482, 
    GPGError_ENOTNAM = 16483, 
    GPGError_ENOTSOCK = 16484, 
    GPGError_ENOTSUP = 16485, 
    GPGError_ENOTTY = 16486, 
    GPGError_ENOTUNIQ = 16487, 
    GPGError_ENXIO = 16488, 
    GPGError_EOPNOTSUPP = 16489, 
    GPGError_EOVERFLOW = 16490, 
    GPGError_EPERM = 16491, 
    GPGError_EPFNOSUPPORT = 16492, 
    GPGError_EPIPE = 16493, 
    GPGError_EPROCLIM = 16494, 
    GPGError_EPROCUNAVAIL = 16495, 
    GPGError_EPROGMISMATCH = 16496, 
    GPGError_EPROGUNAVAIL = 16497, 
    GPGError_EPROTO = 16498, 
    GPGError_EPROTONOSUPPORT = 16499, 
    GPGError_EPROTOTYPE = 16500, 
    GPGError_ERANGE = 16501, 
    GPGError_EREMCHG = 16502, 
    GPGError_EREMOTE = 16503, 
    GPGError_EREMOTEIO = 16504, 
    GPGError_ERESTART = 16505, 
    GPGError_EROFS = 16506, 
    GPGError_ERPCMISMATCH = 16507, 
    GPGError_ESHUTDOWN = 16508, 
    GPGError_ESOCKTNOSUPPORT = 16509, 
    GPGError_ESPIPE = 16510, 
    GPGError_ESRCH = 16511, 
    GPGError_ESRMNT = 16512, 
    GPGError_ESTALE = 16513, 
    GPGError_ESTRPIPE = 16514, 
    GPGError_ETIME = 16515, 
    GPGError_ETIMEDOUT = 16516, 
    GPGError_ETOOMANYREFS = 16517, 
    GPGError_ETXTBSY = 16518, 
    GPGError_EUCLEAN = 16519, 
    GPGError_EUNATCH = 16520, 
    GPGError_EUSERS = 16521, 
    GPGError_EWOULDBLOCK = 16522, 
    GPGError_EXDEV = 16523, 
    GPGError_EXFULL = 16524,
	
	// Libmacgpg XPC related errors
	GPGErrorXPCConnectionError = 20500,
	GPGErrorXPCBinaryError = 20501,
	GPGErrorXPCConnectionInterruptedError = 20502,
	
	GPGErrorNoKeyserverURL,
	GPGErrorParseError
} GPGErrorCode;


@class GPGTask;

@interface GPGException : NSException {
	GPGTask *gpgTask;
	GPGErrorCode errorCode;
	NSString *description;
}

@property (nonatomic, readonly, retain) GPGTask *gpgTask;
@property (nonatomic, readonly) GPGErrorCode errorCode;

extern NSString *GPGExceptionName;
extern NSString * const GPGErrorDomain;


- (id)initWithName:(NSString *)aName reason:(NSString *)aReason userInfo:(NSDictionary *)aUserInfo errorCode:(GPGErrorCode)aErrorCode gpgTask:(GPGTask *)aGPGTask;

+ (GPGException *)exceptionWithReason:(NSString *)aReason userInfo:(NSDictionary *)aUserInfo errorCode:(GPGErrorCode)aErrorCode gpgTask:(GPGTask *)aGPGTask;
+ (GPGException *)exceptionWithReason:(NSString *)aReason errorCode:(GPGErrorCode)aErrorCode gpgTask:(GPGTask *)aGPGTask;
+ (GPGException *)exceptionWithReason:(NSString *)aReason gpgTask:(GPGTask *)aGPGTask;
+ (GPGException *)exceptionWithReason:(NSString *)aReason errorCode:(GPGErrorCode)aErrorCode;

@end
