//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class MCMessageHeaders, MFMessageWritePreparedStatements, NSArray, NSData, NSString, NSUUID;

@interface MFDatabaseWritableMessage : NSObject
{
    char *_color;	// 8 = 0x8
    BOOL _messageType;	// 16 = 0x10
    int _automatedConversationType;	// 20 = 0x14
    int _rootStatus;	// 24 = 0x18
    int _conversationPosition;	// 28 = 0x1c
    int _dateReceived;	// 32 = 0x20
    int _dateSent;	// 36 = 0x24
    int _dateViewed;	// 40 = 0x28
    MFMessageWritePreparedStatements *_preparedStatements;	// 48 = 0x30
    long long _subjectID;	// 56 = 0x38
    long long _senderID;	// 64 = 0x40
    NSString *_sender;	// 72 = 0x48
    NSString *_subjectPrefixString;	// 80 = 0x50
    NSString *_subject;	// 88 = 0x58
    NSData *_messageIDHeaderDigest;	// 96 = 0x60
    NSString *_remoteMailboxIDString;	// 104 = 0x68
    long long _conversationID;	// 112 = 0x70
    long long _mailboxID;	// 120 = 0x78
    long long _fuzzyAncestor;	// 128 = 0x80
    NSArray *_toRecipients;	// 136 = 0x88
    NSUUID *_documentID;	// 144 = 0x90
    NSData *_inReplyToHeaderDigest;	// 152 = 0x98
    MCMessageHeaders *_headers;	// 160 = 0xa0
    NSArray *_references;	// 168 = 0xa8
    unsigned long long _size;	// 176 = 0xb0
    long long _flags;	// 184 = 0xb8
}

@property(nonatomic) long long flags; // @synthesize flags=_flags;
@property(nonatomic) unsigned long long size; // @synthesize size=_size;
@property(nonatomic) BOOL messageType; // @synthesize messageType=_messageType;
@property(nonatomic) int dateViewed; // @synthesize dateViewed=_dateViewed;
@property(nonatomic) int dateSent; // @synthesize dateSent=_dateSent;
@property(nonatomic) int dateReceived; // @synthesize dateReceived=_dateReceived;
@property(copy, nonatomic) NSArray *references; // @synthesize references=_references;
@property(retain, nonatomic) MCMessageHeaders *headers; // @synthesize headers=_headers;
@property(copy, nonatomic) NSData *inReplyToHeaderDigest; // @synthesize inReplyToHeaderDigest=_inReplyToHeaderDigest;
@property(retain, nonatomic) NSUUID *documentID; // @synthesize documentID=_documentID;
@property(copy, nonatomic) NSArray *toRecipients; // @synthesize toRecipients=_toRecipients;
@property(nonatomic) int conversationPosition; // @synthesize conversationPosition=_conversationPosition;
@property(nonatomic) int rootStatus; // @synthesize rootStatus=_rootStatus;
@property(nonatomic) int automatedConversationType; // @synthesize automatedConversationType=_automatedConversationType;
@property(nonatomic) long long fuzzyAncestor; // @synthesize fuzzyAncestor=_fuzzyAncestor;
@property(nonatomic) long long mailboxID; // @synthesize mailboxID=_mailboxID;
@property(nonatomic) long long conversationID; // @synthesize conversationID=_conversationID;
@property(copy, nonatomic) NSString *remoteMailboxIDString; // @synthesize remoteMailboxIDString=_remoteMailboxIDString;
@property(copy, nonatomic) NSData *messageIDHeaderDigest; // @synthesize messageIDHeaderDigest=_messageIDHeaderDigest;
@property(copy, nonatomic) NSString *subject; // @synthesize subject=_subject;
@property(copy, nonatomic) NSString *subjectPrefixString; // @synthesize subjectPrefixString=_subjectPrefixString;
@property(copy, nonatomic) NSString *sender; // @synthesize sender=_sender;
@property(nonatomic) long long senderID; // @synthesize senderID=_senderID;
@property(nonatomic) long long subjectID; // @synthesize subjectID=_subjectID;
@property(readonly, nonatomic) MFMessageWritePreparedStatements *preparedStatements; // @synthesize preparedStatements=_preparedStatements;
- (void).cxx_destruct;	// IMP=0x000000000005f357
- (long long)_rowIDForSubject:(id)arg1 subjectRowIDsCache:(id)arg2 cacheIsExhaustive:(BOOL)arg3;	// IMP=0x000000000005ec1e
- (id)propertyListFromMessage:(id)arg1 remoteID:(id)arg2 gmailLabels:(id)arg3;	// IMP=0x000000000005e980
- (void)setupLibraryMessage:(id)arg1 fromMessage:(id)arg2;	// IMP=0x000000000005e3bd
- (void)bindFieldsToPreparedStatement:(id)arg1 isUpdate:(BOOL)arg2;	// IMP=0x000000000005db87
- (BOOL)updateFieldsFromMessage:(id)arg1 subjectRowIDsCache:(id)arg2 addressRowIDsCache:(id)arg3 cacheIsExhaustive:(BOOL)arg4;	// IMP=0x000000000005d0d8
- (long long)_rowIDForAddressText:(id)arg1 cache:(id)arg2 cacheIsExhaustive:(BOOL)arg3;	// IMP=0x000000000005c900
- (BOOL)_insertRecipientsWithMessageID:(long long)arg1 recipients:(id)arg2 recipientType:(BOOL)arg3 position:(unsigned long long)arg4 addressRowIDsCache:(id)arg5 cacheIsExhaustive:(BOOL)arg6;	// IMP=0x000000000005c529
- (BOOL)insertRecpientsWithMessageID:(long long)arg1 fromMessage:(id)arg2 addressRowIDsCache:(id)arg3 cacheIsExhaustive:(BOOL)arg4;	// IMP=0x000000000005c179
- (void)insertCalendarEvent:(id)arg1 withMessageID:(long long)arg2;	// IMP=0x000000000005c087
- (void)insertAttachmentsWithMessageID:(long long)arg1 fromMessage:(id)arg2;	// IMP=0x000000000005bd07
- (BOOL)insertReferencesWithMessageID:(long long)arg1;	// IMP=0x000000000005b6ef
- (void)updateFieldsFromLibraryWithMessageRowID:(long long)arg1;	// IMP=0x000000000005afd4
@property(nonatomic) char *color;
- (void)dealloc;	// IMP=0x000000000005aefb
- (id)init;	// IMP=0x000000000005ae2c
- (id)initWithPreparedStatements:(id)arg1;	// IMP=0x000000000005ad3e

@end

