//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "NSCoding.h"

@class MFEWSAccount, MFEWSConnection, NSDictionary, NSMutableArray, NSOperationQueue;

@interface MFEWSGateway : NSObject <NSCoding>
{
    NSMutableArray *_offlineRequests;	// 8 = 0x8
    MFEWSAccount *_account;	// 16 = 0x10
    NSOperationQueue *_syncOperationQueue;	// 24 = 0x18
    NSDictionary *_savedOfflineToRealEWSIdStrings;	// 32 = 0x20
}

+ (id)newTemporaryItemId;	// IMP=0x0000000000093100
+ (id)keyPathsForValuesAffectingRequestResponseQueue;	// IMP=0x000000000008ce7a
+ (id)operationActivityLog;	// IMP=0x000000000008cc3f
@property(copy, nonatomic) NSDictionary *savedOfflineToRealEWSIdStrings; // @synthesize savedOfflineToRealEWSIdStrings=_savedOfflineToRealEWSIdStrings;
@property(readonly, nonatomic) NSOperationQueue *syncOperationQueue; // @synthesize syncOperationQueue=_syncOperationQueue;
@property(readonly, nonatomic) __weak MFEWSAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;	// IMP=0x00000000000931e2
@property(readonly, nonatomic) unsigned long long maxRequestsToSend;
- (void)_chunkItemsToSend:(id)arg1 applyToBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000000092eea
- (void)setOofState:(long long)arg1 internalReply:(id)arg2 externalReply:(id)arg3 startTime:(id)arg4 endTime:(id)arg5 externalAudienceType:(long long)arg6;	// IMP=0x0000000000092a4c
- (void)getOofSettings;	// IMP=0x0000000000092369
- (BOOL)fetchUsageInfo:(CDStruct_1dee9796 *)arg1 forEWSFolderIdString:(id)arg2;	// IMP=0x0000000000091ece
- (void)addOfflineToRealEWSIdStrings:(id)arg1 forRequest:(id)arg2;	// IMP=0x0000000000091ec8
- (id)resolvedIdStringForIdString:(id)arg1;	// IMP=0x0000000000091e29
- (BOOL)deleteMailboxWithEWSFolderIdString:(id)arg1 error:(id *)arg2;	// IMP=0x0000000000091d31
- (BOOL)moveMailboxWithEWSFolderIdString:(id)arg1 to:(id)arg2 error:(id *)arg3;	// IMP=0x0000000000091bc1
- (BOOL)renameMailboxWithEWSFolderIdString:(id)arg1 to:(id)arg2 error:(id *)arg3;	// IMP=0x0000000000091aa5
- (id)createMailboxWithParentEWSFolderIdString:(id)arg1 name:(id)arg2 mailboxType:(int)arg3 error:(id *)arg4;	// IMP=0x0000000000091972
- (void)undeleteMessageForFailedCreateEventResponse:(id)arg1;	// IMP=0x000000000009182e
- (void)sendResponseType:(BOOL)arg1 forMeetingMessage:(id)arg2 inStore:(id)arg3 errorHandler:(id)arg4;	// IMP=0x00000000000915ed
- (id)copyMessagesWithEWSItemIds:(id)arg1 fromFolderWithIdString:(id)arg2 toFolderWithIdString:(id)arg3 errorHandler:(id)arg4;	// IMP=0x00000000000911de
- (void)deleteMessagesWithEWSItemIds:(id)arg1 fromFolderWithEWSIdString:(id)arg2 synchronously:(BOOL)arg3;	// IMP=0x0000000000090e13
- (id)appendMessage:(id)arg1 withData:(id)arg2 toEWSFolderWithIdString:(id)arg3 messageType:(BOOL)arg4 flags:(long long)arg5 sender:(id)arg6 recipientsByHeaderKey:(id)arg7 send:(BOOL)arg8 errorHandler:(id)arg9;	// IMP=0x0000000000090c09
- (id)fetchMimeDataForMessage:(id)arg1 errorHandler:(id)arg2;	// IMP=0x000000000009044f
- (void)_saveData:(id)arg1 forMessage:(id)arg2 isPartial:(BOOL)arg3 updateMetadata:(BOOL)arg4;	// IMP=0x00000000000902fc
@property(readonly, nonatomic) MFEWSConnection *connection;
- (id)_offlineCachePathForDataWithItemIdString:(id)arg1;	// IMP=0x0000000000090117
- (id)_offlineCachePathForMessageWithItemIdString:(id)arg1;	// IMP=0x0000000000090049
- (id)_offlineCachePath;	// IMP=0x000000000008ffc8
- (void)removeMessageAndDataFromOfflineCacheForEWSItemIdString:(id)arg1;	// IMP=0x000000000008fe54
- (void)retrieveMessageFromOfflineCache:(id *)arg1 data:(id *)arg2 forItemIdString:(id)arg3;	// IMP=0x000000000008fc80
- (BOOL)writeMessageToOfflineCache:(id)arg1 data:(id)arg2 forItemIdString:(id)arg3;	// IMP=0x000000000008f86d
- (BOOL)playbackRequestsFromOfflineCacheWithConnection:(id)arg1 error:(id *)arg2;	// IMP=0x000000000008f312
- (void)_addDeleteRequestToOfflineCache:(id)arg1;	// IMP=0x000000000008e979
- (void)_addCreateRequestToOfflineCache:(id)arg1;	// IMP=0x000000000008e6dd
- (void)_saveOfflineCache;	// IMP=0x000000000008e27f
- (void)saveRequestToOfflineCache:(id)arg1;	// IMP=0x000000000008e134
- (id)fetchDistinguishedFolderIdsWithConnection:(id)arg1;	// IMP=0x000000000008d8d2
- (void)takeRequestOffline:(id)arg1 error:(id)arg2;	// IMP=0x000000000008d89f
- (void)sendMessage:(id)arg1 forRequest:(id)arg2;	// IMP=0x000000000008d40a
- (void)addError:(id)arg1 withHandler:(id)arg2;	// IMP=0x000000000008d0c0
- (void)addResponse:(id)arg1;	// IMP=0x000000000008d04e
- (void)addRequest:(id)arg1;	// IMP=0x000000000008ceea
@property(readonly, nonatomic) NSOperationQueue *requestResponseQueue;
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000000008ce74
- (id)initWithCoder:(id)arg1;	// IMP=0x000000000008ce47
- (id)init;	// IMP=0x000000000008cd78
- (id)initWithAccount:(id)arg1;	// IMP=0x000000000008cc9e

@end

