//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Mail/MFEWSResponseOperation.h>

@class EWSSetUserOofSettingsResponseType;

@interface MFEWSSetUserOofSettingsResponseOperation : MFEWSResponseOperation
{
}

- (void)executeOperation;	// IMP=0x00000000000b84c6
- (void)prepareToExecuteWithResponse:(id)arg1 forRequestOperation:(id)arg2;	// IMP=0x00000000000b8289
@property(retain) EWSSetUserOofSettingsResponseType *response;

@end

