//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Mail/MFEWSResponseOperation.h>

@class EWSCreateItemResponseType, NSString;

@interface MFEWSCreateItemResponseOperation : MFEWSResponseOperation
{
    NSString *_itemId;	// 24 = 0x18
}

@property(copy) NSString *itemId; // @synthesize itemId=_itemId;
- (void).cxx_destruct;	// IMP=0x0000000000080039
- (void)executeOperation;	// IMP=0x000000000007fc0d
- (void)prepareToExecuteWithResponse:(id)arg1 forRequestOperation:(id)arg2;	// IMP=0x000000000007f9d0
@property(retain) EWSCreateItemResponseType *response;

@end

