//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "MCBodyFetchContext.h"

@class NSMutableDictionary, NSOperationQueue, NSString;

@interface MFGlobalBodyFetchContext : NSObject <MCBodyFetchContext>
{
    NSMutableDictionary *_fetchContextsByAccountIdentifier;	// 8 = 0x8
    NSOperationQueue *_workQueue;	// 16 = 0x10
}

@property(readonly, nonatomic) NSOperationQueue *workQueue; // @synthesize workQueue=_workQueue;
- (void).cxx_destruct;	// IMP=0x00000000000c79b7
- (void)cacheBodiesForMessages:(id)arg1;	// IMP=0x00000000000c7266
- (id)init;	// IMP=0x00000000000c71b6

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

