//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Mail/MFIMAPCopyMessagesOperation.h>

@class NSMutableArray, NSPointerArray;

@interface MFIMAPOfflineCopyOnStupidServerOperation : MFIMAPCopyMessagesOperation
{
    NSMutableArray *_messageIds;	// 48 = 0x30
    NSPointerArray *_internalDates;	// 56 = 0x38
}

@property(retain, nonatomic) NSPointerArray *internalDates; // @synthesize internalDates=_internalDates;
@property(retain, nonatomic) NSMutableArray *messageIds; // @synthesize messageIds=_messageIds;
- (void).cxx_destruct;	// IMP=0x00000000000ffb7b
- (void)_deserializeOpSpecificValuesFromData:(id)arg1 cursor:(unsigned long long *)arg2;	// IMP=0x00000000000ffa39
- (unsigned char)_magic;	// IMP=0x00000000000ffa2e
- (void)serializeIntoData:(id)arg1;	// IMP=0x00000000000ff974

@end

