//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "NSFilePresenter.h"

@class NSOperationQueue, NSString, NSURL;

@interface MFSyncedFile : NSObject <NSFilePresenter>
{
    NSURL *_cloudURL;	// 8 = 0x8
    id _cloudURLLock;	// 16 = 0x10
    id _cloudFileLock;	// 24 = 0x18
    NSURL *_url;	// 32 = 0x20
    long long _syncState;	// 40 = 0x28
}

+ (void)_checkForiCloudMetadata;	// IMP=0x0000000000278826
+ (id)_metadataURL;	// IMP=0x00000000002758a3
+ (void)_setMetadata:(id)arg1;	// IMP=0x000000000027582c
+ (id)_metadata;	// IMP=0x00000000002755e2
+ (id)_currentiCloudAccount;	// IMP=0x000000000027558b
+ (id)syncedFileForRelativePath:(id)arg1;	// IMP=0x0000000000274247
+ (void)initialize;	// IMP=0x0000000000273c5c
+ (id)log;	// IMP=0x0000000000273bfd
@property long long syncState; // @synthesize syncState=_syncState;
@property(readonly, nonatomic) NSURL *URL; // @synthesize URL=_url;
- (void).cxx_destruct;	// IMP=0x000000000027da96
- (void)_handleIdentityChange:(id)arg1;	// IMP=0x000000000027d59a
- (void)_resolveConflicts;	// IMP=0x000000000027cd3a
- (id)_ubiquitousFileForVersion:(long long)arg1;	// IMP=0x000000000027cac5
@property(readonly) NSURL *cloudURL;
- (BOOL)_fileExistsInCloud;	// IMP=0x000000000027c853
- (BOOL)_writeDataToCloud:(id)arg1 options:(unsigned long long)arg2 error:(id *)arg3;	// IMP=0x000000000027b011
- (id)_upgradedLegacyDataIsReachable:(char *)arg1;	// IMP=0x000000000027ac5f
- (BOOL)_updateLocalPostNotification:(BOOL)arg1 didUpdate:(char *)arg2 error:(id *)arg3;	// IMP=0x000000000027a139
- (BOOL)_mergeUpdateLocal:(char *)arg1 error:(id *)arg2;	// IMP=0x00000000002791c9
- (BOOL)_waitForMetadata;	// IMP=0x0000000000278e5b
- (BOOL)_syncWithCloudPostNotification:(BOOL)arg1 error:(id *)arg2;	// IMP=0x00000000002789d0
- (BOOL)_deleteLocalFileAndReturnError:(id *)arg1;	// IMP=0x0000000000278641
- (void)deleteFile;	// IMP=0x0000000000277c93
- (id)_readPlistWithOptions:(unsigned long long)arg1 error:(id *)arg2;	// IMP=0x0000000000277bd4
- (id)readPlistWithOptions:(unsigned long long)arg1;	// IMP=0x00000000002774e6
- (void)writePlist:(id)arg1 options:(unsigned long long)arg2;	// IMP=0x0000000000276e0f
- (id)readDataWithOptions:(unsigned long long)arg1;	// IMP=0x00000000002768cc
- (BOOL)_writeDataLocally:(id)arg1 options:(unsigned long long)arg2 setMetadata:(BOOL)arg3 postNotification:(BOOL)arg4 error:(id *)arg5;	// IMP=0x000000000027660e
- (BOOL)_writeDataAfterResolvingConflict:(id)arg1 options:(unsigned long long)arg2 error:(id *)arg3;	// IMP=0x0000000000276377
- (BOOL)_writeData:(id)arg1 options:(unsigned long long)arg2 error:(id *)arg3;	// IMP=0x0000000000275d88
- (void)writeData:(id)arg1 options:(unsigned long long)arg2;	// IMP=0x0000000000275903
- (void)_clearMetadata;	// IMP=0x0000000000275483
@property(nonatomic) BOOL hasMigratedFromLegacy;
- (BOOL)_signedInState;	// IMP=0x000000000027510b
- (void)_setiCloudAccount;	// IMP=0x0000000000274e4c
- (id)_iCloudAccount;	// IMP=0x0000000000274cda
- (void)presentedItemDidResolveConflictVersion:(id)arg1;	// IMP=0x0000000000274cd4
- (void)presentedItemDidMoveToURL:(id)arg1;	// IMP=0x00000000002749a1
- (void)presentedItemDidGainVersion:(id)arg1;	// IMP=0x0000000000274804
- (void)presentedItemDidChange;	// IMP=0x00000000002744fd
- (void)accommodatePresentedItemDeletionWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000000027434c
@property(readonly, retain) NSOperationQueue *presentedItemOperationQueue;
@property(readonly, copy) NSURL *presentedItemURL;
- (void)dealloc;	// IMP=0x00000000002740ba
- (id)init;	// IMP=0x0000000000273feb
- (id)initWithRelativePath:(id)arg1;	// IMP=0x0000000000273d86

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, copy) NSURL *primaryPresentedItemURL;
@property(readonly) Class superclass;

@end

