//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ABMailRecent.h"

@class NSDate;

@interface ABMailRecent (MailCoreAdditions)
- (id)_fullName;	// IMP=0x0000000000002e5e
- (BOOL)isGroup;	// IMP=0x0000000000002daa
@property(readonly, nonatomic) BOOL hasRelatedAddressBookRecord;
@property(readonly, nonatomic) NSDate *mostRecentDate;
- (id)extension;	// IMP=0x0000000000002cf5
- (id)nickname;	// IMP=0x0000000000002ced
- (id)middleName;	// IMP=0x0000000000002ce5
@end

