//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "MCAttachmentDataSource-Protocol.h"

@class NSMutableSet, NSString, NSURL;

@interface MCFileURLAttachmentDataSource : NSObject <MCAttachmentDataSource>
{
    NSMutableSet *_operations;	// 8 = 0x8
    NSURL *_fileURL;	// 16 = 0x10
}

@property(retain, nonatomic) NSURL *fileURL; // @synthesize fileURL=_fileURL;
//- (void).cxx_destruct;	// IMP=0x000000000002a995
@property(readonly, nonatomic) BOOL isDirectory;
@property(readonly, nonatomic) BOOL canResultsBeCached;
@property(readonly, nonatomic) BOOL dataIsLocallyAvailable;
- (id)approximateSizeForAccessLevel:(long long)arg1;	// IMP=0x0000000000029df9
- (void)fileWrapperForAccessLevel:(long long)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000000029833
- (void)dataForAccessLevel:(long long)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x000000000002926a
- (id)_backgroundFileReadingQueue;	// IMP=0x00000000000291d4
- (void)dealloc;	// IMP=0x0000000000029183
- (id)init;	// IMP=0x00000000000290b4
- (id)initWithFileURL:(id)arg1;	// IMP=0x0000000000029012

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

