//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MailCore/MCAuthScheme.h>

@interface MCGssapiAuthScheme : MCAuthScheme
{
}

+ (id)gssApiAuthScheme;	// IMP=0x00000000000320f5
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x000000000003203b
- (id)supportedSaslMechanisms;	// IMP=0x0000000000032324
- (BOOL)requiresPassword;	// IMP=0x000000000003231c
- (unsigned int)applescriptScheme;	// IMP=0x0000000000032311
- (id)humanReadableName;	// IMP=0x00000000000322a5
- (id)name;	// IMP=0x0000000000032291
- (void)dealloc;	// IMP=0x00000000000321c0

@end

