//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@interface MCImageJunkMetadata : NSObject
{
    unsigned long long _pixelCount;	// 8 = 0x8
    unsigned long long _byteCount;	// 16 = 0x10
    BOOL _isAnimated;	// 24 = 0x18
    long long _type;	// 32 = 0x20
    double _density;	// 40 = 0x28
    unsigned long long _frameCount;	// 48 = 0x30
    struct CGSize _size;	// 56 = 0x38
}

+ (id)lsmMarkerForImageDensityCategory:(long long)arg1;	// IMP=0x0000000000035750
+ (id)lsmMarkerForImageSizeCategory:(long long)arg1;	// IMP=0x00000000000355ec
+ (id)stringForImageType:(long long)arg1;	// IMP=0x000000000003548c
@property(nonatomic) unsigned long long frameCount; // @synthesize frameCount=_frameCount;
@property(nonatomic) BOOL isAnimated; // @synthesize isAnimated=_isAnimated;
@property(nonatomic) double density; // @synthesize density=_density;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(nonatomic) long long type; // @synthesize type=_type;
- (id)description;	// IMP=0x0000000000035bda
@property(readonly, nonatomic) long long densityCategory;
@property(readonly, nonatomic) long long sizeCategory;
@property(nonatomic) unsigned long long pixelCount;
@property(nonatomic) unsigned long long byteCount;
- (void)_computeDensity;	// IMP=0x0000000000035a05
- (id)init;	// IMP=0x00000000000359ec
- (id)initWithImage:(id)arg1 name:(id)arg2 type:(long long)arg3;	// IMP=0x00000000000358b4

@end

