//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@interface MCKeychainManager : NSObject
{
}

+ (struct OpaqueSecPolicyRef *)createSMIMEPolicyForAddress:(id)arg1 keyUsage:(void *)arg2;	// IMP=0x00000000000373ee
+ (struct OpaqueSecCertificateRef *)copyEncryptionCertificateForAddress:(id)arg1;	// IMP=0x0000000000036daa
+ (struct OpaqueSecIdentityRef *)copySigningIdentityForAddress:(id)arg1;	// IMP=0x0000000000036594
+ (id)copyTLSClientIdentities;	// IMP=0x0000000000036358
+ (void)setSessionTrustedCertificates:(id)arg1 forHost:(id)arg2;	// IMP=0x0000000000036269
+ (id)sessionTrustedCertificatesForHost:(id)arg1;	// IMP=0x00000000000361ce

@end

