//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@interface MCMessageTracer : NSObject
{
}

+ (id)bucketSignatureForValue:(long long)arg1;	// IMP=0x0000000000058b7c
+ (void)messageTraceDomain:(id)arg1 withCustomKeysAndValues:(id)arg2;	// IMP=0x00000000000588cf
+ (void)messageTraceResult:(const char *)arg1 domain:(id)arg2 signature:(id)arg3;	// IMP=0x0000000000058882
+ (void)messageTraceResult:(const char *)arg1 domain:(id)arg2 signature:(id)arg3 extraStatus:(id)arg4;	// IMP=0x0000000000058809
+ (void)messageTraceResult:(const char *)arg1 domain:(id)arg2 uuid:(id)arg3 signature:(id)arg4 extraStatus:(id)arg5;	// IMP=0x0000000000058663
+ (void)messageTraceResult:(const char *)arg1 count:(unsigned long long)arg2 domainPrefix:(id)arg3 domainSuffix:(id)arg4 signature:(id)arg5 extraStatus:(id)arg6;	// IMP=0x0000000000058443
+ (void)messageTraceDomainPrefix:(id)arg1 domainSuffix:(id)arg2 signature:(id)arg3 signature2:(id)arg4 extraStatus:(id)arg5;	// IMP=0x0000000000058261
+ (void)messageTraceOperationError:(id)arg1 domainPrefix:(id)arg2 domainSuffix:(id)arg3 uuid:(id)arg4 duration:(double)arg5 count:(unsigned long long)arg6 size:(unsigned long long)arg7;	// IMP=0x0000000000057ecd

@end

