//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class MCActivityMonitor, NSString;

@interface MCMonitoredOperation : NSOperation
{
    MCActivityMonitor *_parentMonitor;	// 24 = 0x18
    MCActivityMonitor *_monitor;	// 32 = 0x20
}

@property(retain, nonatomic) MCActivityMonitor *monitor; // @synthesize monitor=_monitor;
@property(retain, nonatomic) MCActivityMonitor *parentMonitor; // @synthesize parentMonitor=_parentMonitor;
- (void).cxx_destruct;	// IMP=0x0000000000078e61
- (void)executeOperation;	// IMP=0x0000000000078de1
@property(readonly, copy, nonatomic) NSString *activityString;
- (void)main;	// IMP=0x0000000000078cbb
- (void)dealloc;	// IMP=0x0000000000078c26
- (id)init;	// IMP=0x0000000000078ba8

@end

