//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MailCore/MCMessage.h>

@class MCMutableMessageHeaders, NSData, NSString, _MCOutgoingMimeBody;

@interface MCOutgoingMessage : MCMessage
{
    _MCOutgoingMimeBody *_mimeBody;	// 88 = 0x58
    unsigned long long _localAttachmentsSize;	// 96 = 0x60
    MCMutableMessageHeaders *_mutableHeaders;	// 104 = 0x68
    NSString *_existingRemoteID;	// 112 = 0x70
    NSString *_remoteID;	// 120 = 0x78
    NSData *_rawData;	// 128 = 0x80
}

@property(retain, nonatomic) NSData *rawData; // @synthesize rawData=_rawData;
@property(copy, nonatomic) NSString *remoteID; // @synthesize remoteID=_remoteID;
@property(retain, nonatomic) NSString *existingRemoteID; // @synthesize existingRemoteID=_existingRemoteID;
@property(retain, nonatomic) MCMutableMessageHeaders *mutableHeaders; // @synthesize mutableHeaders=_mutableHeaders;
//- (void).cxx_destruct;	// IMP=0x000000000004cb66
- (void)setLocalAttachmentsSize:(unsigned long long)arg1;	// IMP=0x000000000004ca7a
- (unsigned long long)messageSize;	// IMP=0x000000000004c9b8
- (id)headersIfAvailable;	// IMP=0x000000000004c9a6
- (id)headers;	// IMP=0x000000000004c994
- (id)messageDataIncludingFromSpace:(BOOL)arg1 newDocumentID:(id)arg2 fetchIfNotAvailable:(BOOL)arg3;	// IMP=0x000000000004c851
@property(retain, nonatomic) _MCOutgoingMimeBody *mimeBody;
- (id)dataSource;	// IMP=0x000000000004c7e3
- (id)bodyDataFetchIfNotAvailable:(BOOL)arg1 allowPartial:(BOOL)arg2;	// IMP=0x000000000004c7c6
- (id)bodyData;	// IMP=0x000000000004c7ad
- (id)init;	// IMP=0x000000000004c74a

@end

