//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class NSMutableDictionary, NSMutableString, NSString;

@interface MCSAXHTMLParsing : NSObject
{
    NSMutableString *string;	// 8 = 0x8
    NSMutableDictionary *attributes;	// 16 = 0x10
    NSString *metaName;	// 24 = 0x18
    NSString *metaHttpEquiv;	// 32 = 0x20
    NSString *metaContent;	// 40 = 0x28
    unsigned long long encoding;	// 48 = 0x30
    unsigned int indexingLimit;	// 56 = 0x38
    const char *titleStart;	// 64 = 0x40
    unsigned int titleLength;	// 72 = 0x48
    BOOL inHead;	// 76 = 0x4c
    BOOL inTitle;	// 77 = 0x4d
    BOOL inScript;	// 78 = 0x4e
    BOOL inStyle;	// 79 = 0x4f
}

- (void).cxx_destruct;	// IMP=0x000000000009488a
- (id)initWithEncoding:(unsigned long long)arg1;	// IMP=0x00000000000947e4

@end

