//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class NSString;

@interface MCURLMatch : NSObject
{
    NSString *_urlString;	// 8 = 0x8
    struct _NSRange _range;	// 16 = 0x10
}

@property(readonly, copy, nonatomic) NSString *urlString; // @synthesize urlString=_urlString;
@property(readonly, nonatomic) struct _NSRange range; // @synthesize range=_range;
- (void).cxx_destruct;	// IMP=0x00000000000ad611
- (id)description;	// IMP=0x00000000000ad52d
- (id)debugDescription;	// IMP=0x00000000000ad44d
- (id)init;	// IMP=0x00000000000ad37e
- (id)initWithRange:(struct _NSRange)arg1 urlString:(id)arg2;	// IMP=0x00000000000ad2e5

@end

