//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSValueTransformer.h"

@interface _ConnectionURLTransformer : NSValueTransformer
{
}

+ (Class)transformedValueClass;	// IMP=0x0000000100174b97
- (id)reverseTransformedValue:(id)arg1;	// IMP=0x0000000100174c1f
- (id)transformedValue:(id)arg1;	// IMP=0x0000000100174bb0

@end

