//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableHeaderView.h"

@class MailTableView;

@interface _MailTableHeaderView : NSTableHeaderView
{
    BOOL _didLazyLoadMenu;	// 216 = 0xd8
}

@property(nonatomic) BOOL didLazyLoadMenu; // @synthesize didLazyLoadMenu=_didLazyLoadMenu;
- (id)menu;	// IMP=0x00000001001ec158
@property MailTableView *tableView;

@end

