//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPopUpButtonCell.h"

@interface _RolloverPopUpButtonCell : NSPopUpButtonCell
{
}

- (struct CGRect)_indicatorFrameForCellFrame:(struct CGRect)arg1 inView:(id)arg2;	// IMP=0x000000010028821c
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;	// IMP=0x00000001002880b1
- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;	// IMP=0x0000000100287fc1

@end

