//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComposeViewControllerDelegate-Protocol.h"
#import "MailFullScreenWindowDelegate-Protocol.h"
#import "PopoutAnimationContentProvider-Protocol.h"
#import "TabBarViewDelegate-Protocol.h"

@class ComposeViewController, FullScreenModalCapableWindow, MailInspectorBar, NSArray, NSDictionary, NSMenu, NSString, NSTitlebarAccessoryViewController, TabBarView, TabBarViewController;

@interface ComposeWindowController : NSWindowController <TabBarViewDelegate, ComposeViewControllerDelegate, NSAnimationDelegate, NSToolbarDelegate, NSWindowRestoration, MailFullScreenWindowDelegate, PopoutAnimationContentProvider>
{
    MailInspectorBar *_inspectorBar;	// 80 = 0x50
    BOOL _sendAnimationCancelled;	// 88 = 0x58
    BOOL _sendAnimationIsInProgress;	// 89 = 0x59
    BOOL _shouldCloseWindowWhenAnimationCompletes;	// 90 = 0x5a
    BOOL _inspectorBarDisplayed;	// 91 = 0x5b
    TabBarView *_tabBarView;	// 96 = 0x60
    TabBarViewController *_tabBarViewController;	// 104 = 0x68
    NSTitlebarAccessoryViewController *_toolbarNewTabButtonViewController;	// 112 = 0x70
    NSDictionary *_toolbarItems;	// 120 = 0x78
    NSMenu *_disclosureMenu;	// 128 = 0x80
//    CDUnknownBlockType _loadCompletionHandler;	// 136 = 0x88
    struct CGPoint _animationStartFrameOrigin;	// 144 = 0x90
}

//+ (void)restoreWindowWithIdentifier:(id)arg1 state:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100122943
+ (id)keyPathsForValuesAffectingTitle;	// IMP=0x000000010011eb35
@property(nonatomic) struct CGPoint animationStartFrameOrigin; // @synthesize animationStartFrameOrigin=_animationStartFrameOrigin;
//@property(copy, nonatomic) CDUnknownBlockType loadCompletionHandler; // @synthesize loadCompletionHandler=_loadCompletionHandler;
@property(retain, nonatomic) NSMenu *disclosureMenu; // @synthesize disclosureMenu=_disclosureMenu;
@property(nonatomic) BOOL inspectorBarDisplayed; // @synthesize inspectorBarDisplayed=_inspectorBarDisplayed;
@property(nonatomic) BOOL shouldCloseWindowWhenAnimationCompletes; // @synthesize shouldCloseWindowWhenAnimationCompletes=_shouldCloseWindowWhenAnimationCompletes;
@property(nonatomic) BOOL sendAnimationIsInProgress; // @synthesize sendAnimationIsInProgress=_sendAnimationIsInProgress;
@property(nonatomic) BOOL sendAnimationCancelled; // @synthesize sendAnimationCancelled=_sendAnimationCancelled;
@property(retain, nonatomic) NSDictionary *toolbarItems; // @synthesize toolbarItems=_toolbarItems;
@property(retain, nonatomic) NSTitlebarAccessoryViewController *toolbarNewTabButtonViewController; // @synthesize toolbarNewTabButtonViewController=_toolbarNewTabButtonViewController;
@property(retain, nonatomic) TabBarViewController *tabBarViewController; // @synthesize tabBarViewController=_tabBarViewController;
@property(retain, nonatomic) TabBarView *tabBarView; // @synthesize tabBarView=_tabBarView;
//- (void).cxx_destruct;	// IMP=0x0000000100124cd4
- (void)flushRecordedKeystrokes;	// IMP=0x0000000100124a66
- (void)beginRecordingKeystrokes;	// IMP=0x0000000100124a01
- (struct CGRect)_toolbarRect;	// IMP=0x0000000100124824
- (id)getContentGeometryData;	// IMP=0x0000000100124656
//- (void)getSnapshotParts:(CDUnknownBlockType)arg1;	// IMP=0x00000001001245fa
- (void)selectPreviousTab:(id)arg1;	// IMP=0x000000010012450d
- (void)selectNextTab:(id)arg1;	// IMP=0x000000010012441e
- (id)supplementalTargetForAction:(SEL)arg1 sender:(id)arg2;	// IMP=0x00000001001243ca
- (void)closeAll:(id)arg1;	// IMP=0x0000000100124354
- (void)performClose:(id)arg1;	// IMP=0x00000001001242e2
- (void)closeTab:(id)arg1;	// IMP=0x0000000100124270
@property(readonly, nonatomic) MailInspectorBar *inspectorBar;
- (void)_updateInspectorBar:(BOOL)arg1;	// IMP=0x000000010012407f
- (void)updateInspectorBar;	// IMP=0x000000010012404e
@property(nonatomic) BOOL shouldDisplayInspectorBar;
- (void)toggleComposeFormatInspectorBar:(id)arg1;	// IMP=0x0000000100123ec5
- (void)composeViewControllerDidFinishLoading:(id)arg1;	// IMP=0x0000000100123c73
- (void)composeViewControllerShouldShow:(id)arg1;	// IMP=0x0000000100123ad9
- (void)composeViewControllerShouldClose:(id)arg1;	// IMP=0x0000000100123971
- (void)composeViewControllerDidSend:(id)arg1;	// IMP=0x00000001001237f8
//- (void)prepareComposeViewController:(id)arg1 forSendingWithCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010012364d
- (void)restoreFrame;	// IMP=0x0000000100123609
- (id)_dictionaryRepresentation;	// IMP=0x0000000100123190
- (void)window:(id)arg1 willEncodeRestorableState:(id)arg2;	// IMP=0x0000000100123046
- (void)windowDidMove:(id)arg1;	// IMP=0x0000000100123002
- (void)windowDidResize:(id)arg1;	// IMP=0x0000000100122fbe
- (void)windowDidResignKey:(id)arg1;	// IMP=0x0000000100122f70
- (void)windowDidBecomeKey:(id)arg1;	// IMP=0x0000000100122f5e
- (void)_closeTabViewItems:(id)arg1;	// IMP=0x0000000100122cac
- (BOOL)windowShouldClose:(id)arg1;	// IMP=0x0000000100122bcf
- (void)windowWillClose:(id)arg1;	// IMP=0x0000000100122b45
- (void)animationDidEnd:(id)arg1;	// IMP=0x0000000100122925
- (void)cancelSendAnimation;	// IMP=0x0000000100122870
- (void)_sendAnimationCompleted;	// IMP=0x00000001001227a2
//- (void)_performSendAnimationWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001001220d7
- (BOOL)tabBarView:(id)arg1 acceptDrop:(id)arg2 index:(unsigned long long)arg3;	// IMP=0x00000001001220cf
- (unsigned long long)tabBarView:(id)arg1 validateDrop:(id)arg2;	// IMP=0x00000001001220c7
- (void)tabBarView:(id)arg1 didFinishTransitionAnimationForWindow:(id)arg2;	// IMP=0x00000001001220b0
- (id)tabBarView:(id)arg1 destinationWindowForDetachedTabBarViewItem:(id)arg2;	// IMP=0x000000010012209b
- (id)tabBarView:(id)arg1 detachedWindowImageForDraggedTabBarViewItem:(id)arg2;	// IMP=0x0000000100121fc1
- (BOOL)tabBarView:(id)arg1 acceptTabDrop:(id)arg2 index:(unsigned long long)arg3;	// IMP=0x0000000100121fb9
- (unsigned long long)tabBarView:(id)arg1 validateTabDrop:(id)arg2;	// IMP=0x0000000100121fb1
- (id)_windowImageInRect:(struct CGRect)arg1;	// IMP=0x0000000100121ee2
- (id)_createComposeWindowForTabBarViewItem:(id)arg1;	// IMP=0x0000000100121de9
- (void)moveComposeViewControllersTo:(id)arg1;	// IMP=0x0000000100121b49
- (void)mergeAllWindows:(id)arg1;	// IMP=0x000000010012196e
- (void)moveTabToNewWindowFromMenu:(id)arg1;	// IMP=0x00000001001218fa
- (void)closeOtherTabsFromMenu:(id)arg1;	// IMP=0x00000001001217c8
- (void)closeTabFromMenu:(id)arg1;	// IMP=0x0000000100121753
- (id)tabBarView:(id)arg1 menuForTabBarViewItem:(id)arg2 event:(id)arg3;	// IMP=0x00000001001213fd
- (void)tabBarView:(id)arg1 didMoveTabBarViewItem:(id)arg2 toIndex:(unsigned long long)arg3;	// IMP=0x00000001001213f7
- (void)_tabBarView:(id)arg1 forceCloseTabBarViewItem:(id)arg2;	// IMP=0x000000010012126e
- (void)_tabBarView:(id)arg1 didSendTabBarViewItem:(id)arg2;	// IMP=0x00000001001211b6
//- (void)_tabBarView:(id)arg1 performSendAnimationOfTabBarViewItem:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100120e27
- (void)tabBarView:(id)arg1 closeOtherTabsExceptTabBarViewItem:(id)arg2;	// IMP=0x0000000100120d20
- (void)tabBarView:(id)arg1 closeTabBarViewItem:(id)arg2;	// IMP=0x0000000100120b98
- (id)_removeTabBarViewItem:(id)arg1;	// IMP=0x0000000100120a73
- (id)_selectedTabBarViewItemAfterClosingItem:(id)arg1 inTabBarView:(id)arg2;	// IMP=0x000000010012097d
- (id)selectedTabBarViewItemAfterClosingCurrentTabInTabBarView:(id)arg1;	// IMP=0x00000001001208f1
- (void)tabBarView:(id)arg1 selectTabBarViewItem:(id)arg2;	// IMP=0x000000010012078f
- (void)createNewTabInTabBarView:(id)arg1;	// IMP=0x000000010012069a
- (void)tabBarViewDidZoomIn:(id)arg1;	// IMP=0x0000000100120694
@property(readonly, copy, nonatomic) NSArray *tabNames;
- (void)addComposeViewController:(id)arg1;	// IMP=0x0000000100120242
- (void)newTabWithinWindow:(id)arg1;	// IMP=0x000000010012014d
- (id)_menuForListsItem;	// IMP=0x000000010012003e
- (id)toolbarAllowedItemIdentifiers:(id)arg1;	// IMP=0x000000010011ffe7
- (id)toolbarDefaultItemIdentifiers:(id)arg1;	// IMP=0x000000010011ff90
- (id)toolbar:(id)arg1 itemForItemIdentifier:(id)arg2 willBeInsertedIntoToolbar:(BOOL)arg3;	// IMP=0x000000010011fd51
- (id)animationContentProvider:(id)arg1;	// IMP=0x000000010011fd48
- (void)synchronizeIncludeAttachmentsToolbarItem:(id)arg1;	// IMP=0x000000010011facb
- (void)configureSegmentedItem:(id)arg1 withDictionary:(id)arg2 forSegment:(long long)arg3;	// IMP=0x000000010011fa11
- (void)toolbarWillAddItem:(id)arg1;	// IMP=0x000000010011f924
- (void)updateSendButtonStateInToolbar;	// IMP=0x000000010011f88f
- (void)_resetCloseMenus;	// IMP=0x000000010011f7cc
- (void)_updateCloseMenus;	// IMP=0x000000010011f650
- (BOOL)validateUserInterfaceItem:(id)arg1;	// IMP=0x000000010011f62d
- (BOOL)validateMenuItem:(id)arg1;	// IMP=0x000000010011f585
- (void)synchronizeToolbarReplyWithType:(long long)arg1;	// IMP=0x000000010011f4e2
- (void)_synchronizeChangeReplyItem:(id)arg1 messageType:(long long)arg2;	// IMP=0x000000010011f1a1
- (id)toolbarIdentifier;	// IMP=0x000000010011f182
- (void)_windowDidExitFullScreen:(id)arg1;	// IMP=0x000000010011f143
- (void)_windowWillEnterFullScreen:(id)arg1;	// IMP=0x000000010011f0ed
- (void)_setupToolbar;	// IMP=0x000000010011ef44
- (void)_addOrRemoveNewTabButtonInToolbarIfNecessary;	// IMP=0x000000010011eba5
@property(readonly, copy, nonatomic) NSString *title;
- (void)windowDidLoad;	// IMP=0x000000010011e927
@property(retain) ComposeViewController *contentViewController;
@property(retain) FullScreenModalCapableWindow *window;
- (id)windowNibName;	// IMP=0x000000010011e5b1
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010011e4e2
- (id)initWithWindow:(id)arg1;	// IMP=0x000000010011e413
- (id)init;	// IMP=0x000000010011e2ff

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

