//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

////#import "NSObject.h"
//
//#import "NSCopying.h"

#import "CDStructures.h"

@class Conversation, MCMessage, MCMessageHeaders, MUIWebDocument, NSArray, NSData, NSDate, NSIndexSet, NSMutableArray, NSMutableSet, /*NSObject<SGSuggestionsServiceMailProtocol>,*/ NSOperationQueue, NSString, WebDocumentGenerator;

@interface ConversationMember : NSObject <NSCopying>
{
    NSMutableSet *_primitiveMessages;	// 8 = 0x8
    NSMutableSet *_primaryMessages;	// 16 = 0x10
    NSMutableSet *_hiddenMessages;	// 24 = 0x18
    NSMutableArray *_asyncLoadCompletionHandlers;	// 32 = 0x20
    BOOL _isPrimary;	// 40 = 0x28
    BOOL _isDeleted;	// 41 = 0x29
    MCMessage *_originalMessage;	// 48 = 0x30
    BOOL _senderIsVIP;	// 56 = 0x38
    int _conversationPosition;	// 60 = 0x3c
    BOOL _primitiveIsUnread;	// 64 = 0x40
    BOOL _primitiveIsFlagged;	// 65 = 0x41
    NSIndexSet *_primitiveFlagColors;	// 72 = 0x48
    long long _primitiveJunkStatus;	// 80 = 0x50
    MUIWebDocument *_webDocument;	// 88 = 0x58
    WebDocumentGenerator *_documentGenerator;	// 96 = 0x60
    BOOL _startedLoad;	// 104 = 0x68
    BOOL _messageDataCached;	// 105 = 0x69
    BOOL _registeredForNotifications;	// 106 = 0x6a
    BOOL _inJunkMailbox;	// 107 = 0x6b
    MCMessageHeaders *_headers;	// 112 = 0x70
    Conversation *_conversation;	// 120 = 0x78
    NSArray *_messages;	// 128 = 0x80
    NSString *_messageURLString;	// 136 = 0x88
    NSArray *_intelligentSuggestions;	// 144 = 0x90
    NSOperationQueue *_intelligentSuggestionsQueue;	// 152 = 0x98
//    NSObject<SGSuggestionsServiceMailProtocol> *_intelligentSuggestionsService;	// 160 = 0xa0
}

+ (id)keyPathsForValuesAffectingJunkStatus;	// IMP=0x000000010004a6fd
+ (id)keyPathsForValuesAffectingFlagColors;	// IMP=0x0000000100048377
+ (id)keyPathsForValuesAffectingIsFlagged;	// IMP=0x0000000100048397
+ (id)keyPathsForValuesAffectingIsUnread;	// IMP=0x0000000100048602
+ (BOOL)automaticallyNotifiesObserversOfPrimitiveJunkStatus;	// IMP=0x000000010012b14a
+ (BOOL)automaticallyNotifiesObserversOfPrimitiveFlagColors;	// IMP=0x000000010012b142
+ (BOOL)automaticallyNotifiesObserversOfPrimitiveIsFlagged;	// IMP=0x000000010012b13a
+ (BOOL)automaticallyNotifiesObserversOfPrimitiveIsUnread;	// IMP=0x000000010012b132
+ (id)keyPathsForValuesAffectingMemberIndex;	// IMP=0x000000010012b09e
+ (BOOL)automaticallyNotifiesObserversOfConversationPosition;	// IMP=0x000000010012b096
+ (BOOL)automaticallyNotifiesObserversOfSenderIsVIP;	// IMP=0x000000010012b08e
+ (BOOL)automaticallyNotifiesObserversOfOriginalMessage;	// IMP=0x000000010012b086
+ (BOOL)automaticallyNotifiesObserversOfIsDeleted;	// IMP=0x000000010012b07e
+ (BOOL)automaticallyNotifiesObserversOfIsPrimary;	// IMP=0x000000010012b076
+ (id)keyPathsForValuesAffectingSignerNames;	// IMP=0x000000010012af2f
+ (id)keyPathsForValuesAffectingSigners;	// IMP=0x000000010012ade8
+ (id)keyPathsForValuesAffectingIsSigned;	// IMP=0x000000010012adc8
+ (id)keyPathsForValuesAffectingIsEncrypted;	// IMP=0x000000010012ada8
+ (id)keyPathsForValuesAffectingAttachmentSize;	// IMP=0x000000010012ad88
+ (id)keyPathsForValuesAffectingNumberOfAttachments;	// IMP=0x0000000100047613
+ (id)keyPathsForValuesAffectingMailboxName;	// IMP=0x0000000100048622
+ (id)keyPathsForValuesAffectingDateReceived;	// IMP=0x0000000100048357
+ (id)keyPathsForValuesAffectingSubject;	// IMP=0x000000010012ac37
+ (id)keyPathsForValuesAffectingSubjectWithoutPrefix;	// IMP=0x000000010012ab6f
+ (id)keyPathsForValuesAffectingBccRecipients;	// IMP=0x000000010012aa1e
+ (id)keyPathsForValuesAffectingCcRecipients;	// IMP=0x000000010012a8cd
+ (id)keyPathsForValuesAffectingToRecipients;	// IMP=0x000000010012a77c
+ (id)keyPathsForValuesAffectingSender;	// IMP=0x000000010012a75c
+ (id)keyPathsForValuesAffectingMessageIDHeaderDigest;	// IMP=0x000000010012a73c
+ (id)flagsAffectingConversationMember;	// IMP=0x0000000100057f73
@property(nonatomic) BOOL inJunkMailbox; // @synthesize inJunkMailbox=_inJunkMailbox;
//@property(readonly, nonatomic) NSObject<SGSuggestionsServiceMailProtocol> *intelligentSuggestionsService; // @synthesize intelligentSuggestionsService=_intelligentSuggestionsService;
@property(readonly, nonatomic) NSOperationQueue *intelligentSuggestionsQueue; // @synthesize intelligentSuggestionsQueue=_intelligentSuggestionsQueue;
@property(copy, nonatomic) NSArray *intelligentSuggestions; // @synthesize intelligentSuggestions=_intelligentSuggestions;
@property(copy, nonatomic) NSString *messageURLString; // @synthesize messageURLString=_messageURLString;
@property(nonatomic) BOOL registeredForNotifications; // @synthesize registeredForNotifications=_registeredForNotifications;
@property(nonatomic) BOOL messageDataCached; // @synthesize messageDataCached=_messageDataCached;
@property(nonatomic) BOOL startedLoad; // @synthesize startedLoad=_startedLoad;
@property(copy, nonatomic) NSArray *messages; // @synthesize messages=_messages;
@property(nonatomic) __weak Conversation *conversation; // @synthesize conversation=_conversation;
@property(retain, nonatomic) MCMessageHeaders *headers; // @synthesize headers=_headers;
//- (void).cxx_destruct;	// IMP=0x000000010012c795
@property(readonly, copy, nonatomic) NSArray *messagesForFlagState;
@property(readonly, copy, nonatomic) NSArray *messagesInSameMailboxAsOriginalMessage;
- (BOOL)isPrimaryMessage:(id)arg1;	// IMP=0x0000000100086a4a
- (void)unhideMessage:(id)arg1;	// IMP=0x000000010012c355
- (void)hideMessage:(id)arg1;	// IMP=0x000000010012c0eb
- (void)removeMessage:(id)arg1;	// IMP=0x0000000100087cb3
- (void)addMessage:(id)arg1 isPrimary:(BOOL)arg2;	// IMP=0x0000000100058b65
- (id)_preferredOriginalMessage;	// IMP=0x000000010003dde8
- (void)_reloadOriginalMessage;	// IMP=0x0000000100076289
- (BOOL)_messageIsInSent:(id)arg1;	// IMP=0x0000000100056f26
- (BOOL)_messageIsInTrashJunkOrOutbox:(id)arg1;	// IMP=0x000000010003dd8e
- (BOOL)_messageIsDeleted:(id)arg1;	// IMP=0x000000010003dd22
- (BOOL)_shouldDisplayMessage:(id)arg1;	// IMP=0x000000010003dc4a
- (void)markAsPrinted;	// IMP=0x000000010012c075
- (void)updateLastViewedDate;	// IMP=0x000000010012bf2c
- (void)_reloadSenderIsVIP;	// IMP=0x000000010004dbb5
- (void)_VIPSendersDidChange:(id)arg1;	// IMP=0x000000010009d05c
- (void)_reloadValuesForAggregateFlags;	// IMP=0x000000010004d3e3
- (void)flagsChangedForMessage:(id)arg1;	// IMP=0x0000000100087522
@property(nonatomic) long long junkStatus;
@property(copy, nonatomic) NSIndexSet *flagColors;
@property(nonatomic) BOOL isFlagged;
@property(nonatomic) BOOL isUnread;
- (void)_asyncLoadIntelligentSuggestionsWithMessage:(id)arg1 htmlString:(id)arg2;	// IMP=0x000000010012b347
- (void)_sharedPreferencesDidChange:(id)arg1;	// IMP=0x000000010012b29b
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010012b152
@property(nonatomic) long long primitiveJunkStatus;
@property(copy, nonatomic) NSIndexSet *primitiveFlagColors;
@property(nonatomic) BOOL primitiveIsFlagged;
@property(nonatomic) BOOL primitiveIsUnread;
@property(readonly, nonatomic) unsigned long long memberIndex;
@property(nonatomic) int conversationPosition;
@property(nonatomic) BOOL senderIsVIP;
@property(retain, nonatomic) MCMessage *originalMessage;
@property(nonatomic) BOOL isDeleted;
@property(nonatomic) BOOL isPrimary;
@property(readonly, nonatomic) NSArray *signerNames;
@property(readonly, nonatomic) NSArray *signers;
@property(readonly, nonatomic) BOOL isSigned;
@property(readonly, nonatomic) BOOL isEncrypted;
@property(readonly, nonatomic) unsigned long long attachmentSize;
@property(readonly, nonatomic) unsigned long long numberOfAttachments;
@property(readonly, copy, nonatomic) NSString *mailboxName;
@property(readonly, nonatomic) NSDate *dateReceived;
@property(readonly, copy, nonatomic) NSString *subject;
@property(readonly, copy, nonatomic) NSString *subjectWithoutPrefix;
@property(readonly, copy, nonatomic) NSArray *bccRecipients;
@property(readonly, copy, nonatomic) NSArray *ccRecipients;
@property(readonly, copy, nonatomic) NSArray *toRecipients;
@property(readonly, copy, nonatomic) NSString *sender;
@property(readonly, copy, nonatomic) NSData *messageIDHeaderDigest;
@property(retain, nonatomic) MUIWebDocument *webDocument;
@property(retain, nonatomic) WebDocumentGenerator *documentGenerator;
- (void)cancelLoad;	// IMP=0x00000001000570e7
- (void)reloadIntelligentSuggestions;	// IMP=0x000000010012a42a
- (void)asyncLoadAllowingRemoteFetch:(BOOL)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100129bc0
- (void)invalidate;	// IMP=0x000000010005883c
- (id)debugDescription;	// IMP=0x000000010012986b
- (id)description;	// IMP=0x0000000100129796
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010012978b
- (void)_setTemporaryHeaders;	// IMP=0x0000000100129602
- (void)dealloc;	// IMP=0x0000000100058941
- (id)initWithMessages:(id)arg1 primaryMessages:(id)arg2 forConversation:(id)arg3;	// IMP=0x000000010003d69d
- (id)initWithMessage:(id)arg1 isPrimary:(BOOL)arg2 forConversation:(id)arg3;	// IMP=0x000000010012942d
- (id)init;	// IMP=0x000000010012935e

@end

