//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPopUpButton.h"

@interface DefaultApplicationPopUpButton : NSPopUpButton
{
    long long _indexOfSelectedHandler;	// 184 = 0xb8
}

@property(nonatomic) long long indexOfSelectedHandler; // @synthesize indexOfSelectedHandler=_indexOfSelectedHandler;
- (void)_selectApplication:(id)arg1;	// IMP=0x0000000100146c46
- (void)_setDefaultEmailHandler:(id)arg1;	// IMP=0x0000000100146b98
- (void)_selectHandlerWithBundleIdentifier:(id)arg1 url:(id)arg2;	// IMP=0x00000001000a28ea
- (long long)_addHandlerWithBundleIdentifier:(id)arg1 url:(id)arg2;	// IMP=0x00000001000a24bd
- (void)_populateMenu;	// IMP=0x00000001000a20d3
- (void)refreshApplicationList;	// IMP=0x00000001000a200d

@end

