//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class MFMailbox, NSOperationQueue;

@interface DockCountController : NSObject
{
    MFMailbox *_mailBadgeMailbox;	// 8 = 0x8
    long long _mailBadgeScope;	// 16 = 0x10
    NSOperationQueue *_workQueue;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x000000010005017d
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010014d23f
@property(readonly, nonatomic) NSOperationQueue *workQueue; // @synthesize workQueue=_workQueue;
@property(nonatomic) long long mailBadgeScope; // @synthesize mailBadgeScope=_mailBadgeScope;
- (void).cxx_destruct;	// IMP=0x000000010014d64a
- (void)setMailBadgeScope:(long long)arg1 mailbox:(id)arg2;	// IMP=0x000000010014d509
- (void)unreadCountChanged:(id)arg1;	// IMP=0x00000001000504cf
- (void)_setMailBadgeMailbox:(id)arg1;	// IMP=0x000000010014d49a
@property(readonly, nonatomic) MFMailbox *mailBadgeMailbox;
- (void)_mailboxWillBeInvalidated:(id)arg1;	// IMP=0x000000010009d489
- (void)_setDockBadgeForCount:(id)arg1;	// IMP=0x000000010008829d
- (void)clearCountAndStopUpdating;	// IMP=0x00000001000bb29d
- (void)dealloc;	// IMP=0x000000010014d305
- (id)init;	// IMP=0x000000010005023c

@end

