//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DOMNode.h"

@class DOMElement, DOMHTMLElement, NSArray, NSDictionary, NSString;

@interface DOMNode (MailExtras)
- (void)insertAsSiblingAfterNode:(id)arg1;	// IMP=0x0000000100152d85
- (void)insertAsSiblingBeforeNode:(id)arg1;	// IMP=0x0000000100152d02
- (void)convertBackgroundImageURLsUsingDictionary:(id)arg1;	// IMP=0x0000000100152797
- (BOOL)convertInlineStationeryBackgroundImageURL;	// IMP=0x00000001001520f7
- (void)addInlineBackgroundImageURLToArray:(id)arg1;	// IMP=0x000000010006ebe9
- (id)findElementWithTag:(id)arg1 className:(id)arg2 andIdName:(id)arg3;	// IMP=0x000000010006d278
- (id)findElementWithTag:(id)arg1 andClass:(id)arg2;	// IMP=0x000000010006d21d
- (void)_stationeryAttachmentPlaceholderNodes:(id *)arg1;	// IMP=0x0000000100151fae
@property(readonly, copy, nonatomic) NSArray *stationeryAttachmentPlaceholderNodes;
- (void)_objectElementChildNodes:(id *)arg1;	// IMP=0x0000000100151e75
@property(readonly, copy, nonatomic) NSArray *objectElementChildNodes;
- (void)_descendants:(id *)arg1 withClassName:(id)arg2;	// IMP=0x0000000100151ccd
- (id)descendantsWithClassName:(id)arg1;	// IMP=0x0000000100151c8f
@property(readonly, nonatomic) DOMNode *lastEditableElement;
- (void)_editableElements:(id *)arg1;	// IMP=0x00000001001518ac
@property(readonly, copy, nonatomic) NSDictionary *editableElements;
@property(readonly, nonatomic) DOMHTMLElement *tilingDiv;
@property(readonly, copy, nonatomic) NSArray *tilingElements;
- (void)_stationeryDynamicElementNodes:(id *)arg1;	// IMP=0x0000000100151409
@property(readonly, copy, nonatomic) NSArray *stationeryDynamicElementNodes;
- (BOOL)convertInternalImagesToObjectsIsStationery:(BOOL)arg1;	// IMP=0x0000000100150c21
- (id)attributedStringWithDocument:(id)arg1;	// IMP=0x0000000100150b4d
- (void)fixParagraphsAndQuotesFromMicrosoft;	// IMP=0x0000000100150920
- (void)fixParagraphsAndQuotesFromMicrosoftNodesToRemove:(id)arg1;	// IMP=0x0000000100150442
- (void)recursivelyFixParagraphs;	// IMP=0x000000010006a350
- (void)recursivelyRemoveMailAttributes;	// IMP=0x0000000100150423
- (void)restoreEditableElementsEdited:(id *)arg1 unedited:(id *)arg2;	// IMP=0x0000000100150387
- (void)recursivelyRemoveMailAttributes:(BOOL)arg1 convertObjectsToImages:(BOOL)arg2 convertEditableElements:(BOOL)arg3 removeDefaultColorStyle:(BOOL)arg4;	// IMP=0x000000010006ad5b
- (BOOL)_isAppleStringAttachmentSpan;	// IMP=0x000000010006ac8e
- (BOOL)containsRichTextForMessageFont:(id)arg1;	// IMP=0x0000000100078292
@property(readonly, nonatomic) DOMHTMLElement *containingListElement;
@property(readonly, nonatomic) BOOL containsOnlySelectionMarkers;
@property(readonly, nonatomic) BOOL isInEditableRegion;
@property(readonly, nonatomic) DOMNode *topmostEditableAncestor;
@property(readonly, nonatomic) long long outlineNestingLevel;
@property(readonly, nonatomic) DOMNode *precedingListItem;
@property(readonly, nonatomic) DOMNode *containingListItem;
- (id)topmostContainingNodeWithNameInArray:(id)arg1;	// IMP=0x000000010014fb01
- (id)firstContainingNodeWithNameInArray:(id)arg1;	// IMP=0x000000010014f9a9
- (id)descendantNamed:(id)arg1;	// IMP=0x000000010014f88f
@property(readonly, nonatomic) DOMElement *nestedListElement;
- (BOOL)isAtEndOfContainerNode:(id)arg1;	// IMP=0x000000010014f539
- (BOOL)isAtBeginningOfContainerNode:(id)arg1;	// IMP=0x000000010014f498
- (unsigned int)offsetOfChild:(id)arg1;	// IMP=0x000000010014f3b5
- (id)commonAncestorWithNode:(id)arg1;	// IMP=0x000000010007b9e8
- (BOOL)isDescendantOfNode:(id)arg1;	// IMP=0x000000010014f328
@property(readonly, nonatomic) DOMNode *firstDescendantBlockQuote;
@property(readonly, nonatomic) DOMNode *highestContainingBlockQuote;
@property(readonly, nonatomic) DOMNode *containingBlockQuote;
@property(readonly, nonatomic) long long quoteLevelDelta;
@property(readonly, nonatomic) long long quoteLevel;
@property(readonly, nonatomic) BOOL hasNoSignificantContentsOtherThanAttachments;
@property(readonly, nonatomic) BOOL hasNoSignificantContentsOrWhitespace;
@property(readonly, nonatomic) BOOL hasNoSignificantContents;
- (BOOL)_hasNoSignificantContentsOrWhitespace:(BOOL)arg1 orAttachments:(BOOL)arg2;	// IMP=0x000000010014ec22
@property(readonly, nonatomic) BOOL hasNoContents;
@property(readonly, nonatomic) BOOL isListElement;
@property(readonly, nonatomic) BOOL isBody;
@property(readonly, nonatomic) BOOL isNodeThatAffectsTyping;
@property(readonly, nonatomic) DOMElement *elementAncestor;
@property(readonly, nonatomic) DOMNode *blockNodeAncestor;
@property(readonly, nonatomic) BOOL isBlockLevelElement;
- (id)appendBlockPlaceholder;	// IMP=0x000000010014e32d
@property(readonly, copy, nonatomic) NSString *stringValue;
- (id)_mail_traversePreviousNode;	// IMP=0x000000010014e23c
- (id)_mail_traverseNextSiblingStayingWithin:(id)arg1;	// IMP=0x000000010014e0ad
- (id)_mail_traverseNextNodeStayingWithin:(id)arg1;	// IMP=0x000000010006c5df
@property(readonly, nonatomic) DOMNode *previousNode;
@property(readonly, nonatomic) DOMNode *nextNode;
@property(readonly, nonatomic) DOMNode *nextSiblingOrAunt;
@property(readonly, nonatomic) BOOL _mail_isAttached;
@property(readonly, nonatomic) BOOL isTemporaryCursorMarker;
- (void)removeStrayLinefeeds;	// IMP=0x000000010014dde2
- (void)_removeStrayLinefeedsAtBeginning;	// IMP=0x000000010014dc47
- (void)_removeStrayLinefeedsAtEnd;	// IMP=0x000000010014daac
- (id)XPathRelativeTo:(id)arg1;	// IMP=0x000000010014d74b
@end

