//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VerticallyCenteredTextFieldCell.h"

@interface FlatTableViewDataCell : VerticallyCenteredTextFieldCell
{
}

- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;	// IMP=0x0000000100183571
- (id)textColor;	// IMP=0x0000000100183510

@end

