//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "MailDimmingWindowDelegate-Protocol.h"
//#import "NSAnimationDelegate.h"

@class CALayer, MailWindowShadowLayer, MessageViewer, ModalDimmingWindow, NSString, NSWindow;

@interface FullScreenWindowController : NSObject <NSAnimationDelegate, MailDimmingWindowDelegate>
{
    MessageViewer *_messageViewer;	// 8 = 0x8
    struct CGImage *_mainWindowNonFullScreenSnapshot;	// 16 = 0x10
    struct CGImage *_modalWindowNonFullScreenSnapshot;	// 24 = 0x18
    long long _activeAnimationType;	// 32 = 0x20
    ModalDimmingWindow *_modalDimmingWindow;	// 40 = 0x28
    NSWindow *_coverExitAnimationWindow;	// 48 = 0x30
    CALayer *_mainWindowAnimationLayer;	// 56 = 0x38
    CALayer *_modalWindowAnimationLayer;	// 64 = 0x40
    MailWindowShadowLayer *_mainShadowLayer;	// 72 = 0x48
    MailWindowShadowLayer *_modalShadowLayer;	// 80 = 0x50
    struct CGRect _nonFullScreenWindowFrame;	// 88 = 0x58
}

+ (void)waitForFullScreenSpaceSwitchIfNeeded;	// IMP=0x00000001001863de
+ (BOOL)isFrontmostMessageViewerInFullScreen;	// IMP=0x000000010005c35c
+ (BOOL)preventCreationOfViewerOfClass:(Class)arg1;	// IMP=0x000000010018632d
@property(nonatomic) struct CGRect nonFullScreenWindowFrame; // @synthesize nonFullScreenWindowFrame=_nonFullScreenWindowFrame;
@property(retain, nonatomic) MailWindowShadowLayer *modalShadowLayer; // @synthesize modalShadowLayer=_modalShadowLayer;
@property(retain, nonatomic) MailWindowShadowLayer *mainShadowLayer; // @synthesize mainShadowLayer=_mainShadowLayer;
@property(retain, nonatomic) CALayer *modalWindowAnimationLayer; // @synthesize modalWindowAnimationLayer=_modalWindowAnimationLayer;
@property(retain, nonatomic) CALayer *mainWindowAnimationLayer; // @synthesize mainWindowAnimationLayer=_mainWindowAnimationLayer;
@property(retain, nonatomic) NSWindow *coverExitAnimationWindow; // @synthesize coverExitAnimationWindow=_coverExitAnimationWindow;
@property(retain, nonatomic) ModalDimmingWindow *modalDimmingWindow; // @synthesize modalDimmingWindow=_modalDimmingWindow;
@property(nonatomic) long long activeAnimationType; // @synthesize activeAnimationType=_activeAnimationType;
//- (void).cxx_destruct;	// IMP=0x000000010018bf46
- (void)dimmingWindowClicked;	// IMP=0x000000010018bcfa
- (void)_exitAnimationFinished:(id)arg1;	// IMP=0x000000010018bb45
- (void)startExitAnimationWithDuration:(double)arg1;	// IMP=0x000000010018b73c
- (void)_animateModalWindow:(id)arg1;	// IMP=0x000000010018b157
- (void)_animateMainWindow;	// IMP=0x000000010018ab69
- (id)prepareExitAnimation;	// IMP=0x0000000100189fad
- (struct CGImage *)_newModalWindowSnapshot:(id)arg1;	// IMP=0x0000000100189f55
- (void)_animateModalWindow:(id)arg1 minimized:(BOOL)arg2;	// IMP=0x0000000100189382
- (void)resizeModalWindowForFullScreenSplit:(id)arg1;	// IMP=0x0000000100189185
- (void)restoreMinimizedModalWindow:(id)arg1;	// IMP=0x0000000100189078
- (void)minimizeModalWindow:(id)arg1;	// IMP=0x0000000100188f2b
- (id)appearanceTimingFunction;	// IMP=0x0000000100188ef7
//- (void)_animateModalWindowSend:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100188859
//- (void)_animateModalWindowClose:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010018824c
- (void)_animateModalWindowOpen:(id)arg1;	// IMP=0x0000000100187c64
- (void)windowWillExitFullScreen;	// IMP=0x0000000100187b5f
- (void)windowWillEnterFullScreen;	// IMP=0x0000000100187ac5
- (void)_setupDimmingWindow;	// IMP=0x000000010018796e
- (void)_cleanUpAfterModalWindowClose;	// IMP=0x000000010018786e
- (void)_closeModalWindow:(id)arg1;	// IMP=0x000000010018779b
- (void)_modalWindowWillClose:(id)arg1;	// IMP=0x0000000100187650
- (struct CGRect)modalWindowRectWithParentWindow:(id)arg1;	// IMP=0x000000010018746e
- (void)_prepareModalWindowForNonFullScreen:(id)arg1;	// IMP=0x0000000100187191
- (double)_titleBarHeight;	// IMP=0x00000001001870e5
- (void)prepareWindowForFullScreen:(id)arg1;	// IMP=0x0000000100187030
- (void)presentModalWindow:(id)arg1;	// IMP=0x0000000100186761
//- (void)closeModalWindow:(id)arg1 forcibly:(BOOL)arg2 animate:(BOOL)arg3 animationType:(long long)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x00000001001860f9
- (BOOL)_isFullScreen;	// IMP=0x0000000100186087
- (id)_parentWindow;	// IMP=0x0000000100186041
@property(nonatomic) __weak MessageViewer *messageViewer;
- (void)dealloc;	// IMP=0x0000000100185dfe

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

