//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextView.h"

@interface HeaderTextView : NSTextView
{
    BOOL _shouldClearSelectionOnFocusChange;	// 160 = 0xa0
    id <NSTextAttachmentCell> _attachmentCell;	// 168 = 0xa8
    struct CGSize _contentSize;	// 176 = 0xb0
    struct CGRect _attachmentCellRect;	// 192 = 0xc0
}

@property(nonatomic) BOOL shouldClearSelectionOnFocusChange; // @synthesize shouldClearSelectionOnFocusChange=_shouldClearSelectionOnFocusChange;
@property(nonatomic) struct CGSize contentSize; // @synthesize contentSize=_contentSize;
@property(nonatomic) struct CGRect attachmentCellRect; // @synthesize attachmentCellRect=_attachmentCellRect;
@property(retain, nonatomic) id <NSTextAttachmentCell> attachmentCell; // @synthesize attachmentCell=_attachmentCell;
- (void).cxx_destruct;	// IMP=0x0000000100195ade
- (BOOL)writeSelectionToPasteboard:(id)arg1 type:(id)arg2;	// IMP=0x00000001000961d9
- (id)_selectedAttributedString;	// IMP=0x00000001000964fd
- (id)writablePasteboardTypes;	// IMP=0x0000000100095f72
- (void)mouseMoved:(id)arg1;	// IMP=0x0000000100054816
- (void)mouseExited:(id)arg1;	// IMP=0x0000000100054c3b
- (void)keyDown:(id)arg1;	// IMP=0x000000010019598c
- (void)mouseEntered:(id)arg1;	// IMP=0x000000010005423d
- (void)rightMouseDown:(id)arg1;	// IMP=0x0000000100195764
- (void)mouseDown:(id)arg1;	// IMP=0x0000000100059ad7
- (void)cursorUpdate:(id)arg1;	// IMP=0x0000000100054727
- (id)_attachmentCellForCharacterAtIndex:(unsigned long long)arg1;	// IMP=0x000000010005460c
- (unsigned long long)_glyphIndexForPoint:(struct CGPoint)arg1 glyphRect:(struct CGRect *)arg2;	// IMP=0x0000000100054415
- (void)resetCursorRects;	// IMP=0x000000010004c4a2
- (struct CGSize)intrinsicContentSize;	// IMP=0x000000010004af51
- (void)setConstrainedFrameSize:(struct CGSize)arg1;	// IMP=0x0000000100040d5d
- (BOOL)respondsToSelector:(SEL)arg1;	// IMP=0x00000001001956fa
- (BOOL)autoscroll:(id)arg1;	// IMP=0x00000001001955fc
- (BOOL)resignFirstResponder;	// IMP=0x00000001000886b3
- (BOOL)canBecomeKeyView;	// IMP=0x0000000100088962

@end

