//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LoadRemoteContentBannerViewController.h"

@class NSButton, NSTextField;

@interface JunkMailBannerViewController : LoadRemoteContentBannerViewController
{
    NSTextField *_messageField;	// 104 = 0x68
    NSButton *_moveMessageButton;	// 112 = 0x70
    NSButton *_notJunkButton;	// 120 = 0x78
}

@property(retain, nonatomic) NSButton *notJunkButton; // @synthesize notJunkButton=_notJunkButton;
@property(retain, nonatomic) NSButton *moveMessageButton; // @synthesize moveMessageButton=_moveMessageButton;
@property(nonatomic) __weak NSTextField *messageField; // @synthesize messageField=_messageField;
- (void).cxx_destruct;	// IMP=0x00000001001b21d2
- (void)moveMessageToInbox:(id)arg1;	// IMP=0x00000001001b1fd1
- (void)moveMessageToJunk:(id)arg1;	// IMP=0x00000001001b1e77
- (void)markNotJunk:(id)arg1;	// IMP=0x00000001001b1e0b
- (void)updateBannerContents;	// IMP=0x00000001001b1b3c
- (void)updateWantsDisplay;	// IMP=0x000000010004a59e
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010004d0e0
- (void)setRepresentedObject:(id)arg1;	// IMP=0x000000010004a471
- (BOOL)shouldDisplayToLoadRemoteContent;	// IMP=0x00000001001b1b34
- (id)backgroundColor;	// IMP=0x00000001001b1aff
- (void)dealloc;	// IMP=0x00000001000b5e3e

@end

