//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class NSDate;

@interface MailActivityNotifier : NSObject
{
    NSDate *_activityStartDate;	// 8 = 0x8
}

@property(retain, nonatomic) NSDate *activityStartDate; // @synthesize activityStartDate=_activityStartDate;
- (void).cxx_destruct;	// IMP=0x00000001001b80ea
- (void)_activityCompletionDidChange:(BOOL)arg1;	// IMP=0x00000001001b7fa8
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001001b7e44
- (void)dealloc;	// IMP=0x00000001001b7dc7
- (id)init;	// IMP=0x00000001001b7d35

@end

