//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "StackDataSource.h"
#import "StackDelegate.h"

@class CALayer, NSArray, NSImage, NSMutableDictionary, NSMutableSet, NSString, NSView, StackController, _StackContainerView;

@interface MailStackViewController : NSObject <StackDataSource, StackDelegate>
{
    NSMutableDictionary *_messageViewControllers;	// 8 = 0x8
    NSMutableDictionary *_messageLayers;	// 16 = 0x10
    NSMutableSet *_snapshotWindows;	// 24 = 0x18
    BOOL _initialLoadCompleted;	// 32 = 0x20
    BOOL _performingAsynchronousAnimation;	// 33 = 0x21
    NSArray *_messagesOrConversations;	// 40 = 0x28
    NSImage *_topLayerSnapshot;	// 48 = 0x30
    NSView *_containerView;	// 56 = 0x38
    _StackContainerView *_stackContainerView;	// 64 = 0x40
    CALayer *_stackContainerLayer;	// 72 = 0x48
    StackController *_stackController;	// 80 = 0x50
}

@property(retain, nonatomic) StackController *stackController; // @synthesize stackController=_stackController;
@property(retain, nonatomic) CALayer *stackContainerLayer; // @synthesize stackContainerLayer=_stackContainerLayer;
@property(retain, nonatomic) _StackContainerView *stackContainerView; // @synthesize stackContainerView=_stackContainerView;
@property(readonly, nonatomic) NSView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) NSImage *topLayerSnapshot; // @synthesize topLayerSnapshot=_topLayerSnapshot;
@property(nonatomic) BOOL performingAsynchronousAnimation; // @synthesize performingAsynchronousAnimation=_performingAsynchronousAnimation;
@property(retain, nonatomic) NSArray *messagesOrConversations; // @synthesize messagesOrConversations=_messagesOrConversations;
@property(nonatomic) BOOL initialLoadCompleted; // @synthesize initialLoadCompleted=_initialLoadCompleted;
- (void).cxx_destruct;	// IMP=0x00000001001ebf39
- (void)stackController:(id)arg1 willRemoveLayerForItem:(id)arg2;	// IMP=0x00000001001ebda0
- (void)stackController:(id)arg1 willDisplayLayer:(id)arg2 forItem:(id)arg3;	// IMP=0x00000001001ebd9a
- (void)stackController:(id)arg1 willStackLayer:(id)arg2 forItem:(id)arg3;	// IMP=0x00000001001ebd94
- (void)stackControllerDidStopStackingLayers:(id)arg1;	// IMP=0x00000001001ebb65
- (void)stackControllerWillStartStackingLayers:(id)arg1;	// IMP=0x00000001001ebb5f
- (void)stackController:(id)arg1 loadDataForItem:(id)arg2 inLayer:(id)arg3;	// IMP=0x00000001001ebb59
- (BOOL)stackController:(id)arg1 isDataLoadedForItem:(id)arg2 inLayer:(id)arg3;	// IMP=0x00000001001ebb4e
- (id)stackController:(id)arg1 layerForItem:(id)arg2;	// IMP=0x00000001001eb9be
- (id)stackContainerLayerForStackController:(id)arg1;	// IMP=0x00000001001eb9ac
- (id)_messageOrConversationListFromSelection:(id)arg1;	// IMP=0x00000001001eb6eb
- (void)updateDisplayForSelection:(id)arg1;	// IMP=0x00000001001eb5c2
- (id)_stackControllerCreateIfNeeded:(BOOL)arg1;	// IMP=0x00000001001eb34f
- (void)_abortAnimations;	// IMP=0x00000001001eb2e5
- (void)mui_prepareToLayoutSynchronously:(CDUnknownBlockType)arg1;	// IMP=0x00000001001eae83
- (void)mui_performAnimation;	// IMP=0x00000001001ea75f
- (void)mui_prepareToAnimate:(CDUnknownBlockType)arg1;	// IMP=0x00000001001ea69f
- (void)_viewDidEndLiveResize:(id)arg1;	// IMP=0x00000001001ea38d
- (void)_viewFrameDidChange:(id)arg1;	// IMP=0x00000001001e9d50
- (void)_resizeMessageViewWithID:(id)arg1 toSize:(struct CGSize)arg2 animating:(BOOL)arg3;	// IMP=0x00000001001e9a51
- (void)_messageViewControllerDidFinishLoading:(id)arg1;	// IMP=0x00000001001e9742
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001001e95d9
- (void)_takeSnapshotOfMessageViewForController:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001001e92c8
- (void)_removeMessageViewForItem:(id)arg1;	// IMP=0x00000001001e91cb
- (void)_createMessageViewForItem:(id)arg1;	// IMP=0x00000001001e8e99
- (void)_detachMessageViewFromIndividualWindow:(id)arg1;	// IMP=0x00000001001e8da0
- (void)_attachMessageViewToIndividualWindow:(id)arg1;	// IMP=0x00000001001e8aee
- (void)setStackVisible:(BOOL)arg1 animates:(BOOL)arg2;	// IMP=0x00000001001e8a47
- (void)dealloc;	// IMP=0x00000001001e8856
- (id)init;	// IMP=0x00000001001e8787
- (id)initWithContainerView:(id)arg1;	// IMP=0x00000001001e8611

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

