//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class NSArray, NSConditionLock, NSMutableDictionary, NSMutableSet, NSSet;

@interface MailboxesOutlineViewStateStorage : NSObject
{
    NSConditionLock *_shouldShowVariablesLock;	// 8 = 0x8
    unsigned long long _shouldShowVariablesToUpdate;	// 16 = 0x10
    unsigned long long _shouldShowVariablesToReset;	// 24 = 0x18
    BOOL _shouldShowOutbox;	// 32 = 0x20
    BOOL _shouldShowDrafts;	// 33 = 0x21
    BOOL _shouldShowTrash;	// 34 = 0x22
    BOOL _shouldShowJunk;	// 35 = 0x23
    BOOL _shouldShowFlags;	// 36 = 0x24
    BOOL _shouldShowArchive;	// 37 = 0x25
    BOOL _shouldShowVIPs;	// 38 = 0x26
    NSMutableSet *_visibleFlagMailboxes;	// 40 = 0x28
    id _firstUpdateLock;	// 48 = 0x30
    BOOL _firstUpdate;	// 56 = 0x38
    id _isListeningForVariablesLock;	// 64 = 0x40
    BOOL _isListeningForDocumentEditorNotifications;	// 72 = 0x48
    BOOL _isListeningForMessagesAdded;	// 73 = 0x49
    BOOL _isListeningForFlagUpdates;	// 74 = 0x4a
    id _sectionItemsLock;	// 80 = 0x50
    NSArray *_sectionItems;	// 88 = 0x58
    NSArray *_visibleSectionItems;	// 96 = 0x60
    NSArray *_visibleMailboxes;	// 104 = 0x68
    id _defaultSectionItemsLock;	// 112 = 0x70
    id _activityMonitorMailboxMapsLock;	// 120 = 0x78
    NSMutableDictionary *_mailboxesPerActivityMonitor;	// 128 = 0x80
    NSMutableDictionary *_activityMonitorsPerMailbox;	// 136 = 0x88
    NSMutableDictionary *_finishedActivityMonitorCountPerMailbox;	// 144 = 0x90
    NSConditionLock *_changedMailboxesLock;	// 152 = 0x98
    NSMutableSet *_changedMailboxes;	// 160 = 0xa0
    NSArray *_draggedMailboxes;	// 168 = 0xa8
    NSSet *_observedTaskNames;	// 176 = 0xb0
}

+ (id)sharedInstance;	// IMP=0x000000010000d908
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001001de967
@property(readonly, copy, nonatomic) NSSet *observedTaskNames; // @synthesize observedTaskNames=_observedTaskNames;
@property(retain) NSArray *draggedMailboxes; // @synthesize draggedMailboxes=_draggedMailboxes;
- (void).cxx_destruct;	// IMP=0x00000001001dfbb4
- (BOOL)_archiveMessagesOrSubmailboxesExist;	// IMP=0x000000010001f5b9
@property(readonly, nonatomic) BOOL flagsExist;
@property(readonly, nonatomic) BOOL draftsExist;
- (void)_accountInitializedMailboxList:(id)arg1;	// IMP=0x00000001001dfa71
- (id)copyActivityMonitorsForMailboxes:(id)arg1 finishedCount:(unsigned long long *)arg2;	// IMP=0x00000001001df62e
- (void)_postChangedMailboxesNotification;	// IMP=0x00000001000382ce
- (void)_notifyChangedMailboxes;	// IMP=0x0000000100033c82
- (void)_setNeedsToNotifyChangedMailboxes:(id)arg1;	// IMP=0x00000001000339c1
- (void)_triggerChangedMailboxesNotification;	// IMP=0x0000000100033c15
- (BOOL)_removeActivityMonitor:(id)arg1 fromMailbox:(id)arg2;	// IMP=0x0000000100034d04
- (BOOL)_addActivityMonitor:(id)arg1 toMailbox:(id)arg2;	// IMP=0x00000001000338b1
- (id)_copyMailboxesForActivityMonitor:(id)arg1;	// IMP=0x0000000100032f07
- (void)_monitoredActivityChanged:(id)arg1;	// IMP=0x00000001000328ba
- (id)_copyKeyForObject:(id)arg1;	// IMP=0x0000000100032eaf
@property BOOL shouldShowVIPs;
@property BOOL shouldShowArchive;
@property BOOL shouldShowFlags;
@property BOOL shouldShowJunk;
@property BOOL shouldShowTrash;
@property BOOL shouldShowDrafts;
@property BOOL shouldShowOutbox;
- (void)_setShouldShowVariable:(char *)arg1 withMask:(unsigned long long)arg2 to:(BOOL)arg3;	// IMP=0x000000010004cc2c
@property(readonly, copy) NSArray *visibleMailboxes;
@property(readonly, copy) NSArray *visibleSectionItems;
@property(readonly, copy) NSArray *sectionItems;
- (void)_mailboxDisplayCountChanged:(id)arg1;	// IMP=0x0000000100039057
- (void)_allViewersDidClose:(id)arg1;	// IMP=0x00000001000b9e7d
- (void)_mailboxListingDidChange:(id)arg1;	// IMP=0x0000000100035520
- (void)_editorUserSaved:(id)arg1;	// IMP=0x00000001001df3b7
- (void)_editorClosed:(id)arg1;	// IMP=0x0000000100074b4d
- (void)_viewerPreferencesChanged:(id)arg1;	// IMP=0x00000001000a8e21
- (void)_mailAccountsChanged:(id)arg1;	// IMP=0x0000000100036a5f
- (void)_handleOutboxCountChange;	// IMP=0x0000000100087f42
- (void)_outboxCountDidChange:(id)arg1;	// IMP=0x000000010007f303
- (void)_deliveryFailureHappened:(id)arg1;	// IMP=0x00000001001df3a0
- (void)_VIPsChanged:(id)arg1;	// IMP=0x000000010004cb6f
- (void)_messageFlagsChanged:(id)arg1;	// IMP=0x0000000100040854
- (void)_messagesWereAddedToMailboxes:(id)arg1;	// IMP=0x000000010007f39b
- (void)moveSectionItem:(id)arg1 beforeItem:(id)arg2;	// IMP=0x00000001001def9e
- (void)_updateSectionItemsWithNewlyVisibleFlagMailboxes:(id)arg1;	// IMP=0x000000010000e73f
- (void)_writeVisibleFlagsMailboxesToDefaults;	// IMP=0x000000010001f459
- (void)_readVisibleFlagsMailboxesFromDefaults;	// IMP=0x000000010000f7fe
- (void)_writeSectionItemsToDefaults;	// IMP=0x00000001001dedfd
- (void)_writeSectionItems:(id)arg1 toDefaultsWithKey:(id)arg2;	// IMP=0x00000001001deb33
- (void)_readSectionItemsFromDefaults;	// IMP=0x000000010000e088
- (id)_sectionItemsFromDefaultSectionItems:(id)arg1;	// IMP=0x000000010000e434
- (void)_updateIsListeningForVariables;	// IMP=0x000000010000fba9
- (void)_updateShouldShowVariables;	// IMP=0x000000010001012c
- (void)_setNeedsToResetShouldShowVariablesWithMask:(unsigned long long)arg1;	// IMP=0x000000010000fa58
- (void)_setNeedsToUpdateShouldShowVariablesWithMask:(unsigned long long)arg1;	// IMP=0x0000000100036a97
- (void)_setShouldShowVariablesNeedUpdateWithUpdateMask:(unsigned long long)arg1 resetMask:(unsigned long long)arg2;	// IMP=0x000000010000fa6d
- (void)_triggerShouldShowVariablesUpdate;	// IMP=0x000000010000fb0c
- (void)dealloc;	// IMP=0x00000001001dea2d
- (id)init;	// IMP=0x000000010000d9c7

@end

