//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FilesystemEmailImporter.h"

@interface MboxEmailImporter : FilesystemEmailImporter
{
}

+ (id)explanatoryText;	// IMP=0x00000001001f6c3b
+ (id)name;	// IMP=0x00000001001f6c1c
- (char *)fromString;	// IMP=0x00000001001f6cfc
- (void)prepareForImport;	// IMP=0x00000001001f6ca8

@end

