//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "NSAccessibilityGroup.h"

@class NSString;

@interface MessageListContainerView : NSView <NSAccessibilityGroup>
{
}

- (id)accessibilityIdentifier;	// IMP=0x00000001001fda9b
- (struct CGRect)accessibilityFrame;	// IMP=0x00000001001fd921
- (id)accessibilityLabel;	// IMP=0x00000001001fd8bb
- (BOOL)isAccessibilityElement;	// IMP=0x00000001001fd871

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

