//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class ConversationSet, NSDictionary;

@interface MessageSelection : NSObject
{
    ConversationSet *_conversations;	// 8 = 0x8
    NSDictionary *_focusedMessagesByConversation;	// 16 = 0x10
    NSDictionary *_selectedMessagesByConversation;	// 24 = 0x18
}

@property(readonly, copy, nonatomic) NSDictionary *selectedMessagesByConversation; // @synthesize selectedMessagesByConversation=_selectedMessagesByConversation;
@property(readonly, copy, nonatomic) NSDictionary *focusedMessagesByConversation; // @synthesize focusedMessagesByConversation=_focusedMessagesByConversation;
@property(readonly, copy, nonatomic) ConversationSet *conversations; // @synthesize conversations=_conversations;
- (void).cxx_destruct;	// IMP=0x000000010021dd93
- (id)description;	// IMP=0x000000010021dc92
- (unsigned long long)hash;	// IMP=0x000000010021dbd3
- (BOOL)isEqual:(id)arg1;	// IMP=0x000000010002243c
- (id)init;	// IMP=0x000000010021db04
- (id)initWithConversations:(id)arg1 focusedMessages:(id)arg2 selectedMessages:(id)arg3;	// IMP=0x000000010021da08

@end

