//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableCellView.h"

@class MCMessage, MessageListObjectProxy, NSButton, NSColor;

@interface RichMessageCellBase : NSTableCellView
{
    NSColor *_textColor;	// 200 = 0xc8
    NSButton *_replyButton;	// 208 = 0xd0
}

+ (id)keyPathsForValuesAffectingIsSelected;	// IMP=0x0000000100281e70
+ (id)keyPathsForValuesAffectingTextColor;	// IMP=0x0000000100281d96
+ (id)keyPathsForValuesAffectingMessage;	// IMP=0x0000000100281d26
@property(retain, nonatomic) NSButton *replyButton; // @synthesize replyButton=_replyButton;
- (void).cxx_destruct;	// IMP=0x000000010028208c
- (void)setReplyTarget:(id)arg1;	// IMP=0x0000000100281fdd
- (void)setReplyAction:(SEL)arg1;	// IMP=0x0000000100281f91
- (void)setFrameSize:(struct CGSize)arg1;	// IMP=0x0000000100281f06
@property(readonly, nonatomic) BOOL isSelected;
@property(retain, nonatomic) NSColor *textColor; // @synthesize textColor=_textColor;
@property(readonly, nonatomic) MCMessage *message;
- (void)setBackgroundStyle:(long long)arg1;	// IMP=0x0000000100281caa
@property(retain) MessageListObjectProxy *objectValue;

@end

