//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "SlidingAnimationDelegate.h"

@class ClippedItemsIndicator, NSMutableArray, NSString, NSView<NSCopying>, SlidingAnimation;

@interface SlidingViewsBar : NSView <SlidingAnimationDelegate>
{
    unsigned long long _dropIndex;	// 152 = 0x98
    unsigned long long _dragSourceIndex;	// 160 = 0xa0
    ClippedItemsIndicator *_rightClipIndicator;	// 168 = 0xa8
    NSMutableArray *_buttons;	// 176 = 0xb0
    SlidingAnimation *_animation;	// 184 = 0xb8
    double _draggedItemWidth;	// 192 = 0xc0
}

+ (double)buttonBottomOffset;	// IMP=0x00000001002a1637
@property(nonatomic) double draggedItemWidth; // @synthesize draggedItemWidth=_draggedItemWidth;
@property(retain, nonatomic) SlidingAnimation *animation; // @synthesize animation=_animation;
@property(retain, nonatomic) NSMutableArray *buttons; // @synthesize buttons=_buttons;
@property(readonly, nonatomic) ClippedItemsIndicator *rightClipIndicator; // @synthesize rightClipIndicator=_rightClipIndicator;
@property(nonatomic) unsigned long long dragSourceIndex; // @synthesize dragSourceIndex=_dragSourceIndex;
- (void).cxx_destruct;	// IMP=0x00000001002a3359
- (void)_ensureButtonIsInViewHierarchy:(id)arg1;	// IMP=0x00000001002a31ff
- (void)_mainStatusDidChange:(id)arg1;	// IMP=0x000000010003976a
- (BOOL)isFlipped;	// IMP=0x000000010000d475
- (void)viewWillBeginDragging:(id)arg1;	// IMP=0x00000001002a3129
@property(readonly, nonatomic) NSView<NSCopying> *viewPinnedToOverflowIndicator;
- (void)moveSlidingViewToCurrentDropIndex:(id)arg1;	// IMP=0x00000001002a3060
@property(readonly, nonatomic) BOOL isSliding;
- (void)draggingEnded:(id)arg1;	// IMP=0x00000001002a301c
- (unsigned long long)draggingUpdated:(id)arg1;	// IMP=0x00000001002a300a
- (void)draggingExited:(id)arg1;	// IMP=0x00000001002a2fee
- (unsigned long long)draggingEntered:(id)arg1;	// IMP=0x00000001002a2f14
- (unsigned long long)updateDropTarget:(id)arg1;	// IMP=0x00000001002a2f0c
- (double)slidingWidthForView:(id)arg1;	// IMP=0x00000001002a2eca
- (double)widthOfDraggingInfo:(id)arg1;	// IMP=0x00000001002a2ec1
- (void)resumeAnimation;	// IMP=0x00000001002a2ea4
- (void)pauseAnimation;	// IMP=0x00000001002a2e87
- (BOOL)reorderSlidingView:(id)arg1 fromMouseDownEvent:(id)arg2;	// IMP=0x00000001002a27bf
- (id)_lastDraggedOrUpEventFollowing:(id)arg1;	// IMP=0x00000001002a26af
- (id)_lastDraggedEventFollowing:(id)arg1;	// IMP=0x00000001002a259f
@property(nonatomic) unsigned long long dropIndex;
- (void)slideButtonsIntoPlace;	// IMP=0x00000001002a19b8
- (unsigned long long)dropIndexFromLocalPoint:(struct CGPoint)arg1;	// IMP=0x00000001002a1692
- (unsigned long long)dropIndexFromDraggingInfo:(id)arg1;	// IMP=0x00000001002a1652
- (void)refreshButtons;	// IMP=0x00000001002a164c
- (void)draggedSlidingView:(id)arg1;	// IMP=0x00000001002a1646
- (void)reorderedSlidingView:(id)arg1;	// IMP=0x00000001002a1640
@property(readonly, nonatomic) double paddingBetweenButtons;
- (struct CGRect)_constrainProposedButtonFrame:(struct CGRect)arg1;	// IMP=0x00000001002a1533
@property(readonly, nonatomic) double minSlidingViewX;
@property(readonly, nonatomic) double minButtonX;
@property(readonly, nonatomic) double maxButtonX;
@property(readonly, nonatomic) double maxButtonXWithClipIndicator;
@property(readonly, nonatomic) double maxButtonXWithoutClipIndicator;
@property(readonly, nonatomic) unsigned long long lastNonSlidingViewIndex;
- (void)dealloc;	// IMP=0x00000001002a13f1
- (void)_slidingViewsBarCommonInit;	// IMP=0x000000010000cfd4
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001002a13ac
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010000cf6c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

