//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TabBarViewButton.h"

@class NSArray, NSImage, NSLayoutConstraint, NSMutableArray, NSString, NSTextField, NSView, RolloverImageButton;

@interface TabButton : TabBarViewButton
{
    NSMutableArray *_accessoryViews;	// 176 = 0xb0
    double _buttonWidthForTitleLayout;	// 184 = 0xb8
    double _mainContentContainerCenterOffset;	// 192 = 0xc0
    double _titleTextFieldCenterOffset;	// 200 = 0xc8
    BOOL _showingCloseButton;	// 208 = 0xd0
    id <TabBarViewItem> _tabBarViewItem;	// 216 = 0xd8
    RolloverImageButton *_closeButton;	// 224 = 0xe0
    SEL _closeAction;	// 232 = 0xe8
    SEL _becomeFirstResponderAction;	// 240 = 0xf0
    NSArray *_accessoryViewConstraints;	// 248 = 0xf8
    NSString *_title;	// 256 = 0x100
    NSImage *_image;	// 264 = 0x108
    NSView *_titleContainerView;	// 272 = 0x110
    NSTextField *_titleTextField;	// 280 = 0x118
    NSView *_focusRingView;	// 288 = 0x120
    NSView *_mainContentContainer;	// 296 = 0x128
    NSView *_mainContentClippingContainer;	// 304 = 0x130
    NSView *_accessoryViewsContainer;	// 312 = 0x138
    NSLayoutConstraint *_mainContentContainerWidthConstraint;	// 320 = 0x140
    NSLayoutConstraint *_mainContentContainerLeftConstraint;	// 328 = 0x148
    NSLayoutConstraint *_mainContentContainerRightConstraint;	// 336 = 0x150
    NSLayoutConstraint *_mainContentContainerHorizontalCenteringConstraint;	// 344 = 0x158
    NSLayoutConstraint *_titleContainerViewHorizontalCenteringConstraint;	// 352 = 0x160
}

+ (id)titleFont;	// IMP=0x00000001002f0120
+ (double)titleWidthForButtonWidth:(double)arg1;	// IMP=0x00000001002f0112
@property(retain, nonatomic) NSLayoutConstraint *titleContainerViewHorizontalCenteringConstraint; // @synthesize titleContainerViewHorizontalCenteringConstraint=_titleContainerViewHorizontalCenteringConstraint;
@property(retain, nonatomic) NSLayoutConstraint *mainContentContainerHorizontalCenteringConstraint; // @synthesize mainContentContainerHorizontalCenteringConstraint=_mainContentContainerHorizontalCenteringConstraint;
@property(retain, nonatomic) NSLayoutConstraint *mainContentContainerRightConstraint; // @synthesize mainContentContainerRightConstraint=_mainContentContainerRightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *mainContentContainerLeftConstraint; // @synthesize mainContentContainerLeftConstraint=_mainContentContainerLeftConstraint;
@property(retain, nonatomic) NSLayoutConstraint *mainContentContainerWidthConstraint; // @synthesize mainContentContainerWidthConstraint=_mainContentContainerWidthConstraint;
@property(readonly, nonatomic) NSView *accessoryViewsContainer; // @synthesize accessoryViewsContainer=_accessoryViewsContainer;
@property(readonly, nonatomic) NSView *mainContentClippingContainer; // @synthesize mainContentClippingContainer=_mainContentClippingContainer;
@property(readonly, nonatomic) NSView *mainContentContainer; // @synthesize mainContentContainer=_mainContentContainer;
@property(readonly, nonatomic) NSView *focusRingView; // @synthesize focusRingView=_focusRingView;
@property(readonly, nonatomic) NSTextField *titleTextField; // @synthesize titleTextField=_titleTextField;
@property(readonly, nonatomic) NSView *titleContainerView; // @synthesize titleContainerView=_titleContainerView;
@property(readonly, nonatomic) NSImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSArray *accessoryViewConstraints; // @synthesize accessoryViewConstraints=_accessoryViewConstraints;
@property(nonatomic) BOOL showingCloseButton; // @synthesize showingCloseButton=_showingCloseButton;
@property(nonatomic) SEL becomeFirstResponderAction; // @synthesize becomeFirstResponderAction=_becomeFirstResponderAction;
@property(nonatomic) SEL closeAction; // @synthesize closeAction=_closeAction;
@property(readonly, nonatomic) RolloverImageButton *closeButton; // @synthesize closeButton=_closeButton;
@property(readonly, nonatomic) id <TabBarViewItem> tabBarViewItem; // @synthesize tabBarViewItem=_tabBarViewItem;
- (void).cxx_destruct;	// IMP=0x00000001002f0e8c
- (BOOL)resignFirstResponder;	// IMP=0x00000001002f0bb9
- (BOOL)becomeFirstResponder;	// IMP=0x00000001002f0abf
- (void)updateLayer;	// IMP=0x00000001002f095b
- (void)setState:(long long)arg1;	// IMP=0x00000001002f0876
- (void)setTitle:(id)arg1;	// IMP=0x00000001002f07fd
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
- (id)tabDragImageOfSize:(struct CGSize)arg1;	// IMP=0x00000001002f0487
- (id)_titleStringAttributesForMainWindow:(BOOL)arg1 activeTab:(BOOL)arg2;	// IMP=0x00000001002f0175
- (void)_updateTitleTextField;	// IMP=0x00000001002effd9
- (void)updateCloseButtonImages;	// IMP=0x00000001002eff29
- (void)setHasPressedHighlight:(BOOL)arg1;	// IMP=0x00000001002efd8b
- (void)setHasMouseOverHighlight:(BOOL)arg1 shouldAnimateCloseButton:(BOOL)arg2;	// IMP=0x00000001002efc95
- (void)_closeButtonClicked:(id)arg1;	// IMP=0x00000001002efc00
- (void)_updateAccessibilityAttributes;	// IMP=0x00000001002ef98e
- (void)_updateConstraints;	// IMP=0x00000001002ef64f
- (void)_setUpConstraints;	// IMP=0x00000001002ee989
- (void)_updateTitleContainerConstraints;	// IMP=0x00000001002ee7ce
- (void)setActive:(BOOL)arg1;	// IMP=0x00000001002ee76b
- (void)setTitleTextFieldCenterOffset:(double)arg1 animated:(BOOL)arg2;	// IMP=0x00000001002ee68c
@property(nonatomic) double titleTextFieldCenterOffset;
- (void)setMainContentContainerCenterOffset:(double)arg1 animated:(BOOL)arg2;	// IMP=0x00000001002ee469
@property(nonatomic) double mainContentContainerCenterOffset;
- (void)setAlignment:(unsigned long long)arg1;	// IMP=0x00000001002ee3e5
- (void)setButtonWidthForTitleLayout:(double)arg1 animated:(BOOL)arg2;	// IMP=0x00000001002ee306
@property(nonatomic) double buttonWidthForTitleLayout;
- (void)_updateAccessoryViews;	// IMP=0x00000001002edc49
@property(copy, nonatomic) NSArray *accessoryViews;
- (void)dealloc;	// IMP=0x00000001002ed7dc
- (void)_tabButtonCommonInitWithtabBarViewItem:(id)arg1;	// IMP=0x00000001002ecefc
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001002ece2d
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001002ecde6
- (id)initWithFrame:(struct CGRect)arg1 tabBarViewItem:(id)arg2;	// IMP=0x00000001002ecd5b

@end

