//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "NSStreamDelegate.h"

@class ComposeViewController, NSMutableData, NSOutputStream, NSString, NSTimer, SingleMessageViewer;

@interface UserActivityHandler : NSObject <NSStreamDelegate>
{
    BOOL _applicationHasFinishedLaunching;	// 8 = 0x8
    BOOL _draftDataComplete;	// 9 = 0x9
    NSString *_waitingForActivityOfType;	// 16 = 0x10
    SingleMessageViewer *_viewerBeingContinued;	// 24 = 0x18
    NSString *_messageURLString;	// 32 = 0x20
    NSTimer *_timeoutTimer;	// 40 = 0x28
    ComposeViewController *_composeController;	// 48 = 0x30
    unsigned long long _continuationDataLength;	// 56 = 0x38
    NSOutputStream *_continuationReplyStream;	// 64 = 0x40
    NSMutableData *_continuationDraftData;	// 72 = 0x48
}

+ (id)activityContinuationLog;	// IMP=0x000000010030f3a6
@property(nonatomic) BOOL draftDataComplete; // @synthesize draftDataComplete=_draftDataComplete;
@property(retain, nonatomic) NSMutableData *continuationDraftData; // @synthesize continuationDraftData=_continuationDraftData;
@property(retain, nonatomic) NSOutputStream *continuationReplyStream; // @synthesize continuationReplyStream=_continuationReplyStream;
@property(nonatomic) unsigned long long continuationDataLength; // @synthesize continuationDataLength=_continuationDataLength;
@property(retain, nonatomic) ComposeViewController *composeController; // @synthesize composeController=_composeController;
@property(retain, nonatomic) NSTimer *timeoutTimer; // @synthesize timeoutTimer=_timeoutTimer;
@property(retain) NSString *messageURLString; // @synthesize messageURLString=_messageURLString;
@property(retain, nonatomic) SingleMessageViewer *viewerBeingContinued; // @synthesize viewerBeingContinued=_viewerBeingContinued;
@property(retain, nonatomic) NSString *waitingForActivityOfType; // @synthesize waitingForActivityOfType=_waitingForActivityOfType;
@property(nonatomic) BOOL applicationHasFinishedLaunching; // @synthesize applicationHasFinishedLaunching=_applicationHasFinishedLaunching;
- (void).cxx_destruct;	// IMP=0x0000000100310d50
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;	// IMP=0x000000010031077b
- (void)_timeout:(id)arg1;	// IMP=0x00000001003106a8
- (void)_libraryMessagesUpdated:(id)arg1;	// IMP=0x0000000100310348
- (void)_populateDraftWindow;	// IMP=0x00000001003101da
- (void)_showContinuedMessage;	// IMP=0x000000010030fdef
- (void)_prepareWindowForActivity;	// IMP=0x000000010030fca8
- (void)didFailToContinueUserActivityWithType:(id)arg1 error:(id)arg2;	// IMP=0x000000010030fad9
- (BOOL)continueUserActivity:(id)arg1 restorationHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010030f589
- (BOOL)willContinueUserActivityWithType:(id)arg1;	// IMP=0x000000010030f543
- (void)_applicationDidFinishLaunching:(id)arg1;	// IMP=0x000000010030f497
- (id)init;	// IMP=0x000000010030f405

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

